### ISSUE TITLE
Using body-parser in express route specific got empty request body

### ISSUE THREAD

**Issue by chandara** [expressjs/body-parser#101]
I tried to apply the the body parser into a specific router, and I always get empty request body.

the following is my code:
```javascript
var express = require('express');
var bodyParser = require('body-parser');

var jsonParser = bodyParser.json({ type: 'application/*+json'});
var router = express.Router();

router.post('/', jsonParser, function(req, res) {
  if(!req.body || req.body.length === 0) {
    console.log('request body not found');
    return res.sendStatus(400);
  }
  var user = req.body;
  console.log('request body : ' + JSON.stringify(user));
  });
});

module.exports = router;
```

The same request was tried with the express app with both generic and express route specific as in the example here https://github.com/expressjs/body-parser#examples and it works fine.

**Comment by dougwilson** [comment]
Can you post the request headers you're sending? My guess is your `Content-Type` header is not matching the `type` you have set there.

**Comment by chandara** [comment]
I used postman to send the request, and this is the curl I got from postman:

curl 'http://localhost:3000/test' -H 'Cache-Control: no-cache' -H 'Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36' -H 'Content-Type: application/json' --data-binary '{"_id": "chandara.sang@gmail.com", "name": "chandara","password": "12345678"}' --compressed

but the thing is that the same request works fine when I used express app as the example in the body-parser git home page.

**Comment by dougwilson** [comment]
Right, but you see, you are sending the header `Content-Type: application/json`, but in your code above, you are setting `type: 'application/*+json'`. `application/json` does not match `application/*+json`, which is why nothing is happening. You want to just remove the `type` option all together unless there is a specific reason you have that there.

**Comment by chandara** [comment]
Thanks @dougwilson, it is now working.

**Comment by dougwilson** [comment]
:+1:

**Comment by nakirekantisaikumar** [comment]
you should not do JSON.stringify   the data while send through AJAX..

**Comment by yles9056** [comment]
@nakirekantisaikumar 

I am using ajax now, but get empty body

Client side:
```javascript
someData = { 'foo': 'bar', 'testProperty': false };
$.ajax({
  url: '/api/items', 
  dataType: 'json',
  data: someData ,
  success: function (data) {
    // do something
  }
});
```

Server side:
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const router = express.Router();
const jsonParser = bodyParser.json();

router.get('/items', jsonParser, function (req, res) {
  console.log(req);
  console.log(req.body); // body is empty
});

app.use('/api', router);
```
