### ISSUE TITLE
Newline characters and additional braces added to JSON in request body

### ISSUE THREAD

**Issue by loosebruce** [expressjs/body-parser#103]
Please see the Stackoverflow question I asked

http://stackoverflow.com/questions/30427176/body-parse-in-node-js-not-escaping-new-line-chars-in-request-body-json

**Comment by dougwilson** [comment]
The reason that happens is because you need to send the header

Content-Type: application/json

But instead your client is incorrectly sending the header

Content-Type: application/x-www-form-urlencoded
