### ISSUE TITLE
[Bug][Fatal] Req.Body starts with 0

### ISSUE THREAD

**Issue by 5punk** [expressjs/body-parser#110]
Hi,
Trying to make a drop in replacement service for a legacy client. I need to parse JSON and have set the mode to non strict
`app.use(bodyParser.json({strict: false}));`

`router.post('/services/getId', function(req, res) ` fails instantly, if the req.body starts with a `0` value. If the req.body starts with any other number, I can read the req.body just fine.
0112 -> fails
4210 -> pass
1252 -> pass

Can anyone provide guidance?

**Comment by dougwilson** [comment]
Interesting. All we are doing is calling JSON.parse(body). I haven't tried yet, but what error specifically does this module give? What is the result of JSON.parse('0112') ?

**Comment by 5punk** [comment]
`JSON.parse('0220');`
(program):1 Uncaught SyntaxError: Unexpected number
    at Object.parse (native)
    at <anonymous>:2:6
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)(anonymous function) @ VM13933:2InjectedScript._evaluateOn @ VM13628:895InjectedScript._evaluateAndWrap @ VM13628:828InjectedScript.evaluate @ VM13628:694

`JSON.parse('1220');`
1220

Weirdest thing ever.

**Comment by dougwilson** [comment]
Looks like it truely is invalid JSON. Check out RFC 7159 sec 6: http://tools.ietf.org/html/rfc7159#section-6

> Leading zeros are not allowed.

**Comment by dougwilson** [comment]
The best I can offer you is to not use the JSON parser for that endpoint. In order for you to do this, if the incoming `Content-Type` is `application/json`, is to change your app to follow the pattern at https://github.com/expressjs/body-parser#express-route-specific and then implement your route as follows:
```js
var bodyParser = require('body-parser')
var express = require('express')

var app = express()
var numberBodyParser = [bodyParser.text({ type: 'json' }), parseNumberTextBody]

app.post('/services/getId', numberBodyParser, function (req, res, next) {
  // route code
})

function parseNumberTextBody(req, res, next) {
  req.body = req.body ? parseInt(req.body, 10) : NaN
  next()
}
```
