### ISSUE TITLE
Please enable option strictNullHandling of qs

### ISSUE THREAD

**Issue by leonciokof** [expressjs/body-parser#111]
To parse values without = back to null use the strictNullHandling flag:

```
Qs.parse('a&b=', { strictNullHandling: true });
// { a: null, b: '' } 
```

**Comment by dougwilson** [comment]
Unfortunately `strictNullHandling` was not added until 3.0, as 3.0 is a breaking change, so we are unlikely to make the jump from 2.x to 3.x for a long, long time. If you can get `qs` to issue a 2.x version with the `strictNullHandling` feature, we could certainly consider it :)

**Comment by leonciokof** [comment]
You can get the name of the empty inputs in the body object. Ex

```html
<form method="post">
<textarea name="obs"></textarea>
</form>
```
```js
console.log(req.body);
{ obs: '' }
```

**Comment by dougwilson** [comment]
Sure? By my point is that we don't even use a version of the `qs` module that has the `strictNullHandling` feature, so there is nothing we can even do here. `qs` would need to issue a 2.x release with the `strictNullHandling` for us to offer it.

**Comment by voodee** [comment]
any progress?
