### ISSUE TITLE
Request Aborted Error

### ISSUE THREAD

**Issue by slickplaid** [expressjs/body-parser#112]
Apologies if this is an easily solvable issue, but I seem to not be able to properly catch the "request aborted" error thrown in a JSON body POST/PUT.

I've reference issue #93 and understand that it's purpose is to keep the connection from hanging, but when I encounter it, the request doesn't make it down to where Express should be handling the error. It is thrown much earlier in the stack.

Example exception:
```
Error: request aborted
    at makeError (/home/ra/xx/node_modules/body-parser/node_modules/raw-body/index.js:139:15)
    at IncomingMessage.onAborted (/home/ra/xx/node_modules/body-parser/node_modules/raw-body/index.js:237:10)
    at IncomingMessage.emit (events.js:92:17)
    at abortIncoming (http.js:1916:11)
    at CleartextStream.serverSocketCloseListener (http.js:1928:5)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:694:10
    at process._tickCallback (node.js:442:13)
```

I am using version `1.13.1` and using an encrypted `HTTPS` connection through Express 4.

My usage of `body-parser` in the appropriate Express routes:
`bodyParser.json({ parameterLimit: 100, limit: '1mb' })`
`bodyParser.urlencoded({ extended: true, parameterLimit: 100, limit: '1mb' })`

We have a rather large form that has an autosave feature. In the XHR request, if they make two quick changes, we'll abort the previous request purposely and resubmit with the new data. In some circumstances this causes the whole body not to be sent, and the above error thrown.

My error condition in Express 4 is as follows (simplified from production):
```javascript
  app.use(function(err, req, res, next){
      if(err.status && err.status < 500) {
        return res.status(400).send('Request Aborted');
      }

      console.log('Type of Error:', typeof err);
      console.log('Error: ', err.stack);

      if(req.xhr) {
        res.partial('500', { error: err });
      } else {
        res.render('500', { error: err });
      }
  });
```

Nothing I do there seems to matter as the error is being thrown much earlier than that express exception handling.

Am I doing something wrong, or might there be something I'm not following in the code to make that happen?

Thanks!

**Comment by dougwilson** [comment]
Silly question: is your `app.use(function(err, req, res, next){` physically below your routes in your server or above them? Express only sends errors downward, so if you defined your error handler before you defined your routes, that error handler would not see those errors.

**Comment by slickplaid** [comment]
Very last route :+1:

**Comment by dougwilson** [comment]
Gotcha. Unfortunately I'm able to catch it just fine with an error handler. Would you be able to share the complete code I can use to reproduce?

**Comment by dougwilson** [comment]
Perhaps another thing you can do is explain how you know your error handler is not being called? It's important to note that under a request abort condition in Node.js, you cannot write a response to the client, because the TCP connection is already closed. Are you basing your error handler calling off those two `console.log` statements, or what the HTTP behavior is?

**Comment by slickplaid** [comment]
Sorry about the late response. Got busy at work.

> Perhaps another thing you can do is explain how you know your error handler is not being called?
Just due to the code in that block not being run. We have no other error handlers (for express) in the program, and I have verified that it's the last route in the chain of middleware and/or routes.

> cannot write a response to the client
That's understood and perfectly fine. The problem is that under load we have had processes spawning other programs and waiting for their response to send to other clients. The error thrown seems to pass right past our error handler and actually throw, causing the thread to restart itself and the output from the spawned process is orphaned. No dropped connections, just a client waiting for a response doesn't get what they want intermittently.

> Are you basing your error handler calling off those two console.log statements
Yes, plus the fact the thread gets killed and restarted instead of caught and handled properly.

Unfortunately the code is not open source, but I'll try and post a lot more in-depth code examples of what we're doing. Give me a few and I'll respond back with some examples.

**Comment by dougwilson** [comment]
> Unfortunately the code is not open source, but I'll try and post a lot more in-depth code examples of what we're doing. Give me a few and I'll respond back with some examples.

That's what I was afraid of. Unless the examples throw the `request aborted` error, they won't help, unfortunately. What you can do, though, is perhaps iterate on the below recorded session, which includes a Express app that clearly catches the `request aborted` error in the Express error handler, complete with making and aborting a request to itself for demonstration purposes.

```
$ npm i express body-parser
body-parser@1.13.1 node_modules\body-parser
+-- content-type@1.0.1
+-- bytes@2.1.0
+-- depd@1.0.1
+-- qs@2.4.2
+-- on-finished@2.3.0 (ee-first@1.1.1)
+-- raw-body@2.1.1 (unpipe@1.0.0)
+-- http-errors@1.3.1 (statuses@1.2.1, inherits@2.0.1)
+-- debug@2.2.0 (ms@0.7.1)
+-- iconv-lite@0.4.10
+-- type-is@1.6.4 (media-typer@0.3.0, mime-types@2.1.2)
express@4.13.0 node_modules\express
+-- escape-html@1.0.2
+-- merge-descriptors@1.0.0
+-- range-parser@1.0.2
+-- cookie-signature@1.0.6
+-- cookie@0.1.3
+-- utils-merge@1.0.0
+-- content-type@1.0.1
+-- array-flatten@1.1.0
+-- fresh@0.3.0
+-- methods@1.1.1
+-- etag@1.7.0
+-- vary@1.0.0
+-- path-to-regexp@0.1.6
+-- parseurl@1.3.0
+-- content-disposition@0.5.0
+-- serve-static@1.10.0
+-- depd@1.0.1
+-- qs@2.4.2
+-- on-finished@2.3.0 (ee-first@1.1.1)
+-- finalhandler@0.4.0 (unpipe@1.0.0)
+-- debug@2.2.0 (ms@0.7.1)
+-- proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
+-- send@0.13.0 (destroy@1.0.3, statuses@1.2.1, mime@1.3.4, ms@0.7.1, http-errors@1.3.1)
+-- type-is@1.6.4 (media-typer@0.3.0, mime-types@2.1.2)
+-- accepts@1.2.10 (negotiator@0.5.3, mime-types@2.1.2)

$ cat test.js
var bodyParser = require('body-parser')
var express = require('express')
var http = require('http')

var app = express()

app.use(function (req, res, next) {
  console.log('incoming request for ' + req.url)
  next()
})

app.use(bodyParser.json())

app.use(function (req, res) {
  console.log('success!')
  res.end()
})

app.use(function (err, req, res, next) {
  console.log('oh no, an error i caught: ' + err.stack)
  req.destroy()
})

var server = http.createServer(app)

server.listen(function () {
  var port = server.address().port
  var res = http.request({
    headers: { 'content-type': 'application/json' },
    method: 'POST',
    port: port
  })

  res.write('{')
  res.on('error', function () {})

  // after some time, client aborts
  setTimeout(function () {
    res.destroy()
  }, 1000)
})

$ node test.js
incoming request for /
oh no, an error i caught: Error: request aborted
    at makeError (D:\Users\Douglas\Desktop\bp-test\node_modules\body-parser\node_modules\raw-body\index.js:139:15)
    at IncomingMessage.onAborted (D:\Users\Douglas\Desktop\bp-test\node_modules\body-parser\node_modules\raw-body\index.js:237:10)
    at IncomingMessage.emit (events.js:92:17)
    at abortIncoming (http.js:1915:11)
    at Socket.serverSocketCloseListener (http.js:1927:5)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:465:12)
```

**Comment by slickplaid** [comment]
Sounds good. I appreciate you taking the time to look into this with me. I'll keep going through it on our end since it definitely looks like the problem is in our source somewhere. We just got a new developer and he rewrote some of the error handler, so I'm going to assume something in that code is what is causing this and not something else.

Thanks!

**Comment by dougwilson** [comment]
No problem! I'm always listening in here, so feel free to make additional comments here and I can even re-open if necessary :)

**Comment by slickplaid** [comment]
Found it! Our new developer did a strict type comparison to the types of errors he thought we would see for some reason. Because `raw-body` creates a new Error object and changes it's type, he had it throwing the exception like it was fatal to restart the process and prevent an unstable state.

Thanks again for the help!

**Comment by dougwilson** [comment]
Interesting. So you can always find detailed information about the errors this module will forward at https://github.com/expressjs/body-parser#errors but as far that logic, it makes sense, but you may be able to make it a little more resilient by treating `err.status >= 400 && err.status < 600` as "safe" exceptions you don't need to restart on from within an Express ecosystem.

**Comment by vijayaraman555** [comment]
Error: request aborted
    at IncomingMessage.onAborted
i have installed body-parser already

**Comment by Ingosmar89219** [comment]
hey friends what can i do whit this problem? when im trying to install express in a polymers project i get this error. im using windows 8 
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ..\..\node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── content-type@1.0.2
├── encodeurl@1.0.1
├── merge-descriptors@1.0.1
├── etag@1.7.0
├── methods@1.1.2
├── cookie@0.3.1
├── path-to-regexp@0.1.7
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── range-parser@1.2.0
├── vary@1.1.0
├── serve-static@1.11.1
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── fresh@0.3.0
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-error
s@1.5.0)
