### ISSUE TITLE
rawData also needed

### ISSUE THREAD

**Issue by KingMario** [expressjs/body-parser#114]
I should have read the documents more.
Issue is closing.

**Comment by KingMario** [comment]
Use the verify option:

        verify: function (req, res, buf, encoding) {
            req.rawBody = buf;
        }

**Comment by dougwilson** [comment]
You got it! Also, be extra careful, as that will use 2x the memory as normal.

**Comment by KingMario** [comment]
Thanks for the reminding.

In my project, I need the rawBody for a particular route path to authenticate the request. To avoid 2x-ed memory occupation, maybe I should do the authentication right inside the verify callback, but don't know how to reject the request if it's not authenticated.

**Comment by dougwilson** [comment]
Ah. Yes, that is pretty much what the verify function is there for: to verify the body using a signature or similar.

To reject the request from the verify function, simply throw an error. We will catch it and issue a 403 response by default.
