### ISSUE TITLE
Problem with array parsing

### ISSUE THREAD

**Issue by viniciusbo** [expressjs/body-parser#115]
Hi,
When I post `<input name="order[1]" value="0">` it gets parsed as `{ order: [ '0' ] }` instead of `{ order: ['', '0'] }`, when there is no input named `order[0]`.
Have been trying to track it down, but I'm not sure if this issue is related to body-parser or raw-body package.
Any thoughts on this?

**Comment by dougwilson** [comment]
It would be from the Qs module, which does the parsing for urlencoded bodies.

**Comment by dougwilson** [comment]
https://github.com/hapijs/qs

**Comment by viniciusbo** [comment]
I see. Just found #40 which is the same as I'm facing. Sorry for the duplicate.
