### ISSUE TITLE
Strict JSON validation failure could throw a SyntaxError for consistency with JSON.parse()

### ISSUE THREAD

**Issue by carlbennettnz** [expressjs/body-parser#119]
If my body is "`bad`" an `Error` is sent, but if my body is "`{bad`" a `SyntaxError` is sent.

**Comment by dougwilson** [comment]
Hi! I'm unsure of what you are asking, unfortunately. We do throw a `SyntaxError`, at least with the most recent version. Can you elaborate more on the issue, provide a PR, provide a test case, or something else?

**Comment by dougwilson** [comment]
Oh, are you talking about https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L83 ? If so, we cannot change that to `throw SyntaxError`, as we used to, but not all JS platforms allow you to throw an instance of that error :(

**Comment by dougwilson** [comment]
Well, I think in 2.0, we can make this change, since we'll just say we're not going to support those platforms any longer!

**Comment by carlbennettnz** [comment]
Awesome :+1:

**Comment by dougwilson** [comment]
I'm reclassifying this as a bug and releasing in the 1.x series :) Please test out the fix on the `master` branch and let me know if it matches your expectations.

**Comment by carlbennettnz** [comment]
Thanks, that works prefectly :)

**Comment by dougwilson** [comment]
This as been published to npm as 1.14.0
