### ISSUE TITLE
body-parser does not work with browserify

### ISSUE THREAD

**Issue by tardyp** [expressjs/body-parser#120]
browserify is useful to package apps even at node level.

It can turn a 200MB dependency installation into a 2MB minified file.

The following code:
```
var parsersDir = path.join(__dirname, 'lib', 'types')

/**
 * Auto-load bundled parsers with getters.
 */

fs.readdirSync(parsersDir).forEach(function onfilename(filename) {
  if (!/\.js$/.test(filename)) return

  var loc = path.resolve(parsersDir, filename)
  var mod
  var name = path.basename(filename, '.js')

  function load() {
    if (mod) {
      return mod
    }

    return mod = require(loc)
  }

  Object.defineProperty(exports, name, {
    configurable: true,
    enumerable: true,
    get: load
  })
})
```
dynamically compute require input while there are only 4 modules to discover.

**Comment by 0xR** [comment]
+1 also doesn't work with webpack, I have been trying to fix it with the `webpack.ContextReplacementPlugin` but I've been unsuccessful so far.

**Comment by koistya** [comment]
:+1: bumped into this issue as well.

**Comment by dougwilson** [comment]
@tardyp , the code you are referring to does not exist any longer; you need to upgrade to version 1.13.0 or higher of this module.

**Comment by dougwilson** [comment]
1.13.0 was release June 14 :)

**Comment by tardyp** [comment]
indeed. Actually my problem is in tiny-lr, which depends on ~1.8.0, and should probably have written ^1.8.0

**Comment by elwayman02** [comment]
@tardyp I have forked tiny-lr due to apparenty project abandonment. I submitted your change as a PR and will be releasing it tonight, pending CI build success. Feel free to update to the latest release after that!
