### ISSUE TITLE
Latest BodyParser does not work with Express 4.13.3 static views

### ISSUE THREAD

**Issue by samuelkilada** [expressjs/body-parser#124]
I have a web app set up with express.static as the rendering engine. Anytime I do a form POST, whether I handle it or not I get:

"TypeError: Cannot call method 'toLowerCase' of undefined"
...at line 169 of urlencoded.js.

If I revert to bodyparser 1.6.7 it works just fine.

**Comment by dougwilson** [comment]
Hi! If you look at that line, throwing is perfectly expected: we catch the exception and ignore it (see https://github.com/expressjs/body-parser/blob/1.13.3/lib/types/urlencoded.js#L169). If this is not working for you, your Node.js must be really broken.

What version of Node.js are you using?
Can you provide me with full script and request to replicate the issue?

**Comment by samuelkilada** [comment]
Hi Doug,

Thanks for the fast response. I did actually have a really old version of node and so I updated it, but it's still throwing the error. Here is my main server.js. If you run the server and put an index.html file in a sub "views" folder with a form that has a POST action, it will throw the error:

    // Load modules
    var http = require('http');
    var express = require('express')
    var users = require('./routes/users.js');
    var passport = require('passport');
    var LocalStrategy = require('passport-local').Strategy;
    var bodyParser = require('body-parser');

    // App settings
    var app = express();
    app.set('env', 'development');
    app.set('port', 1337);
    app.use(express.static(__dirname + '/views'));
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: true }));
    var router = express.Router();
    app.use('/', router);
    
    // Start the server
    http.createServer(app).listen(app.get('port'), function () {
        console.log('Express server listening on port ' + app.get('port'));
    });

**Comment by dougwilson** [comment]
Hi @samuelkilada , can you tell me the exact version of Node.js and all the modules you are requiring so I can replicate it? Also, `require('./routes/users.js');` does not work for me, since i don't have the code from there. Can you remove that and validate that you can still reproduce even with it not there?

**Comment by dougwilson** [comment]
I'm sorry, given all the information, I cannot reproduce. Here is a log of my session you can use to validation and tweak until there is something I can reproduce. The problem with your report is that what is thrown is _expected and the try-catch around it should always catch it_, thus producing no error. If it is not, you have something really bad going on in your runtime.
```
$ node -v
v0.10.33

$ npm i express body-parser
body-parser@1.13.3 node_modules\body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.0.1
├── qs@4.0.0
├── raw-body@2.1.2 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── debug@2.2.0 (ms@0.7.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── iconv-lite@0.4.11

express@4.13.3 node_modules\express
├── methods@1.1.1
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── cookie-signature@1.0.6
├── array-flatten@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── utils-merge@1.0.0
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-disposition@0.5.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── serve-static@1.10.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── qs@4.0.0
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, mime@1.3.4, ms@0.7.1, http-errors@1.3.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.6)

$ cat app.js
// Load modules
var http = require('http');
var express = require('express')
var bodyParser = require('body-parser');

// App settings
var app = express();
app.set('env', 'development');
app.set('port', 1337);
app.use(express.static(__dirname + '/views'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
var router = express.Router();
app.use('/', router);
router.post('/', function (req, res){
	res.send('got: ' + JSON.stringify(req.body))
})

// Start the server
http.createServer(app).listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
});

$ cat views/index.html
<h1>hi!</h1>
<form method=post>
<input name="yes">
<input type=submit value=Go>

$ node app.js
Express server listening on port 1337
```

Loading http://127.0.0.1:1337/ from the above session gives me the form and typing "no" into the input and clicking on "Go" gives me the following page:
```
got: {"yes":"no"}
```

**Comment by samuelkilada** [comment]
Sorry about that, yes I removed that users.js file and it still occurs.

I have the latest version of node, 4.0.0.
The modules:

Express: 4.13.3
Passport: 0.3.0
Passwort-Local: 1.0.0

**Comment by dougwilson** [comment]
Cool, I'll try io.js 4.0 real quick, though we do not actually support it (yet), as it take time to get everything fully tested.

**Comment by dougwilson** [comment]
Just tried Node.js 4.0 and it works 100% OK as well, I still cannot reproduce:
```
$ node -v
v4.0.0

$ npm i express body-parser
body-parser@1.13.3 node_modules\body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.0.1
├── qs@4.0.0
├── raw-body@2.1.2 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── debug@2.2.0 (ms@0.7.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── iconv-lite@0.4.11

express@4.13.3 node_modules\express
├── methods@1.1.1
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── cookie-signature@1.0.6
├── array-flatten@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── utils-merge@1.0.0
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── etag@1.7.0
├── content-disposition@0.5.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── serve-static@1.10.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── qs@4.0.0
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, mime@1.3.4, ms@0.7.1, http-errors@1.3.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.6)

$ cat app.js
// Load modules
var http = require('http');
var express = require('express')
var bodyParser = require('body-parser');

// App settings
var app = express();
app.set('env', 'development');
app.set('port', 1337);
app.use(express.static(__dirname + '/views'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
var router = express.Router();
app.use('/', router);
router.post('/', function (req, res){
    res.send('got: ' + JSON.stringify(req.body))
})

// Start the server
http.createServer(app).listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
});

$ cat views/index.html
<h1>hi!</h1>
<form method=post>
<input name="yes">
<input type=submit value=Go>

$ node app.js
Express server listening on port 1337
```

Loading http://127.0.0.1:1337/ from the above session gives me the form and typing "no" into the input and clicking on "Go" gives me the following page:
```
got: {"yes":"no"}
```

Unfortunately I'll have to keep this issue for two reasons:

1. I cannot reproduce at all, given all the information so far. I tried to provide as complete information on exactly how I am reproducing as possible, so I don't have much to do unless you can return the favor :)
2. There is no way `try { throw new Error() } catch (e) { return }` can ever throw an error in JavaScript. If it does, something is seriously broken on your end...

Let me know how I can reproduce the issue, and we can proceed further :)!

**Comment by samuelkilada** [comment]
Thanks Doug. I agree, something must be wrong on my end if it's crashing on a try / catch. I'll look into this and reply back once I figure it out!

**Comment by samuelkilada** [comment]
Well, I just tried this on another machine (exact same project) running VS 2015. Works just fine! I hvae VS 2013 Ultimate on this machine that has the issue. I'm just going to install the latest version of VS and hope that clears up whatever is throwing this off. Thanks for your help.

**Comment by dougwilson** [comment]
Interesting. Are you compiling Node.js from source?
