### ISSUE TITLE
Allow override maxKeys in querystring.parse

### ISSUE THREAD

**Issue by medikoo** [expressjs/body-parser#127]
I've just approached an issue, where part of request body was not parsed, due to default internal limit of 1000 keys within node's [querystring.parse](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options), which can be overriden with `maxKeys` option.

Still I don't see a possiblity to pass it to underlying querystring, with current logic -> https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L75

Maybe it would be good that options provided to urlencode are also passed to querystring. I'll be happy to provide a pull request if that's acceptable approach in your opinion

**Comment by dougwilson** [comment]
Does the `parameterLimit` (https://github.com/expressjs/body-parser#parameterlimit) option not work?

**Comment by dougwilson** [comment]
Example (requires `body-parser` 1.7.0+):
```js
app.use(bodyParser.urlencoded({ parameterLimit: 2000 }))
```

**Comment by medikoo** [comment]
Yes, indeed it fixes my issue. Sorry for bothering
