### ISSUE TITLE
Support for application/vnd.api+json

### ISSUE THREAD

**Issue by digitalsadhu** [expressjs/body-parser#131]
Would you be open to supporting application/vnd.api+json (JSON API) out of the box?

**Comment by dougwilson** [comment]
We used to when it was part of `connect`, but removed it on purpose because it was too surprising and caused issues for people who did not expect it. Simply provide the `type` option to the parser, which is the purpose of the option.

https://github.com/expressjs/body-parser#type

```js
app.use(bodyParser.json({ type: 'application/vnd.api+json' }))
```
