### ISSUE TITLE
500 Error Parsing JSON With Arrays of Objects

### ISSUE THREAD

**Issue by Luke-Niwranski** [expressjs/body-parser#136]
This JSON string produces a 500 error when attempting to parse using the JSON parser:
```
'{"triangles":[{ "indices": [0, 1, 2] },{ "indices": [2, 3, 0] }], "positions": [{ "position": [0.0, 0.0, 0.0] },{ "position": [1.0, 0.0, 0.0] },{ "position": [1.0, 1.0, 0.0] },{ "position": [0.0, 1.0, 0.0] }]}'
```
However, simply renaming one of the properties of one of the objects in one of the arrays allows the string to parse successfully.  So this string will parse:
```
'{"triangles":[{ "indices1": [0, 1, 2] },{ "indices": [2, 3, 0] }], "positions": [{ "position": [0.0, 0.0, 0.0] },{ "position": [1.0, 0.0, 0.0] },{ "position": [1.0, 1.0, 0.0] },{ "position": [0.0, 1.0, 0.0] }]}'
```
Is there a workaround for this?  I need the property names of my arrayed objects to be consistent.

**Comment by dougwilson** [comment]
Hi! I wasn't able to reproduce for whatever reason. Can you paste on what the specific error was with the stack trace? Also the version of Node.js you are using and the version of this module.

**Comment by Luke-Niwranski** [comment]
I tried writing a quick app to show the error, but I'm unable to reproduce it on this computer!  I suspect it may be a version issue with one of the modules.  When I get back to the office on Monday, I'll post the module version numbers I was using at the office and try updating them to see if that resolves the issue.

Thanks!

**Comment by Luke-Niwranski** [comment]
Hello,

I tried this again from my office and the error happened again.  But, I cleaned out all the modules that I'm not using and I'm no longer receiving the error.  The modules I removed are jade, serve-favicon, and jayschema.  I'm not even convinced this was a bug with any of the modules as it is most likely it was a bug within my own module.

Either way, I'm getting the results I want now, so I'm closing this.

Please let me know if you would like any more info about it.

**Comment by dougwilson** [comment]
Gotcha, good to know it's gone now :) The only useful info I can really use would be a complete stack trace of the error, but really only if it leads back into this module.
