### ISSUE TITLE
content type like 'application/x-www-form-urlencoded; text/html; charset=UTF-8' can't be parsed

### ISSUE THREAD

**Issue by loulin** [expressjs/body-parser#137]
This is a callback from [Alipay](http://doc.open.alipay.com/doc2/detail?spm=0.0.0.0.diVxJy&treeId=62&articleId=103743&docType=1) and the form is not parsed.
```
alipay callback headers { host: 'www.test.com',
  'x-real-ip': '110.75.225.212',
  'x-forwarded-for': '110.75.225.212',
  'x-forwarded-proto': 'http',
  connection: 'close',
  'content-length': '773',
  'content-type': 'application/x-www-form-urlencoded; text/html; charset=UTF-8',
  'user-agent': 'Mozilla/4.0' }
```

The typeis can't parse this type, so I think it's malformed. Should I use the `type` option to parse it?

**Comment by dougwilson** [comment]
Correct, it is malformed, so we will always reject it. You can always provide the `type` option (https://github.com/expressjs/body-parser#type) a function to parse the type however you need, though:
```js
app.use(bodyParser.urlencoded({ type: isAlipayType }))

function isAlipayType(req) {
  return req.headers['content-type'] === 'application/x-www-form-urlencoded; text/html; charset=UTF-8'
}
```

**Comment by loulin** [comment]
So it is Alipay's bug. Thanks!

**Comment by dougwilson** [comment]
Sure, though I doubt they'll change it any time soon :) I've gotten a few report about this over time as well.

If you were interested, you can see the ABNF for the `Content-Type` header value at https://tools.ietf.org/html/rfc7231#section-3.1.1.1 The Alipay header becomes invalid like so:
```
application/x-www-form-urlencoded; text/html; charset=UTF-8
                                            ^
                                            Invalid character, expected 0x20 or 0x3D
```
