### ISSUE TITLE
example for deflate / gzip?

### ISSUE THREAD

**Issue by Krisa** [expressjs/body-parser#138]
I'm having a hard time to find out a client side library, which may work with the decompression lib (zlib) used by body-parser. 
I'm usually ending with this error:
```
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17) 
```
I know this is not a body-parser issue, but it would be great to get a working example from a valid client side request.

**Comment by Krisa** [comment]
For anyone having eventually the same issue...

Finally, got it working with pako, it's as simple as that `var body = pako.deflate( JSON.stringify(...) )`. I specified `'Content-Encoding': 'deflate'` and `'Content-Type': 'application/json'` in the headers. 

But actually, my main problem was that I used that with Angular and Angular transform automatically the request into a json based on the content type, hence ... it's necessary to set `transformRequest: []`

**Comment by rjsteinert** [comment]
@Krisa @apitts I created a very basic deflate example for express bodyParser.

https://github.com/rjsteinert/express-client-side-deflate-example

Unfortunately it results in the same error it looks like you were facing. An idea what might be causing it? I filed an issue [here](https://github.com/expressjs/body-parser/issues/292) on the matter.
