### ISSUE TITLE
How to tell if a request doesn't have a body?

### ISSUE THREAD

**Issue by apechimp** [expressjs/body-parser#139]
I use the json parser as middleware in an express app, but for all requests (even with `Content-Type: text/plain`), the parser will set `req.body` to an empty object, so I can't use that to see if the request has a body. The json parser [sets  `req.body`](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L96) before deciding to parse it. What's the best way to determine whether or not a request has a body when using this middleware?

**Comment by dougwilson** [comment]
https://github.com/expressjs/body-parser/issues/128#issuecomment-141500274
