### ISSUE TITLE
`allowDots` option for the extended parser

### ISSUE THREAD

**Issue by fatfisz** [expressjs/body-parser#140]
Would it be a good / bad idea to add the `allowDots` option for the `qs` parser?

This is not a lot of work (I could do that), and the default value would be `false`, as to not break existing stuff.

**Comment by fiznool** [comment]
Maybe there could be a way to pass any arbitrary option to the `qs` library?

``` js
bodyParser.urlencoded({
  extended: {
    allowDots: true,
    depth: 10,
    /// etc.
  }
});
```

Backwards compatibility could be preserved (using `true`, `false` instead of an object should still work).

**Comment by fatfisz** [comment]
Sorry, didn't notice that there's already a PR for that: #98, so I'll close this issue.
