### ISSUE TITLE
How can I parse this JSON payload?

### ISSUE THREAD

**Issue by codecowboy** [expressjs/body-parser#141]
I receive the following from a webhook:

```
{"tweet":"<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Clevertech: Native iOS Leader – <a href="https://t.co/oA3p1VY0Sv">https://t.co/oA3p1VY0Sv</a></p>&mdash; We Work Remotely (@weworkremotely) <a href="https://twitter.com/weworkremotely/status/667170234613264384">November 19, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>"}
```

However, I get an unexpected token error t. I think this is because the the contents of tweet is not correctly escaped. Is there a way to prevent body-parser from throwing this error? Altering the payload is problematic as I don't have access to the code which generates it.

```
var express = require('express');
var app = express();

var bodyParser = require('body-parser');
var multer = require('multer'); // v1.0.5
var upload = multer(); // for parsing multipart/form-data

app.use(bodyParser.json()); // for parsing application/json

app.post('/tweet', upload.array(), function ( req, res, next) {
    console.log(req.body);
    res.send('Hello post endpoint for tweets!');

});

var server = app.listen(3000, function () {


    var host = server.address().address;
    var port = server.address().port;
    console.log(server.address());

    console.log('Example app listening at http://%s:%s', host, port);
});
```

**Comment by dougwilson** [comment]
Hi! All this module does is call JSON.parse on the string. That example is impossible to parse and would be very hard to correctly fix up before parse. Sorry, but that we hook simply needs to send you valid JSON.

**Comment by dougwilson** [comment]
Something you could do, though, is remove

    app.use(bodyParser.json());

From your code above and then change your route definition to the following:

    app.post('/tweet', bodyParser.text({ type: 'json' }), upload.array(), function ( req, res, next) {

And then req.body will simply be the string that was posted to you and you can try to parse it or fix it up somehow in your route.
