### ISSUE TITLE
add a json5 parser

### ISSUE THREAD

**Issue by johanlelan** [expressjs/body-parser#142]
I would like to be flexible on submitted JSON in request body. (allowing some mistakes)
To do this, i would like to use the [JSON5](https://github.com/aseemk/json5) parser instead of JSON one. I looked for an option to add external parsers but it seems that it does not exist.
What do you think about this new feature?

**Comment by dougwilson** [comment]
Hi! This is a great suggestion and something we are tracking under #22

**Comment by dougwilson** [comment]
Hi! This is a good idea, but we really don't want to keep pulling in more and more dependencies. We should really put the effort towards implementing #22 which would make implementing this in user-land or even as an add-on module trivial.
