### ISSUE TITLE
Error: unsupported charset "UTF-8" on Linux machines

### ISSUE THREAD

**Issue by DominikPalo** [expressjs/body-parser#144]
Today I've updated the Body Parser module in my project (from version 1.13.3 to the latest version 1.14.1) and suddenly unit tests starts to fail with error `"unsupported charset "UTF-8""`.  This problem occurs only on Linux machines, on Windows all works fine.

**Comment by dougwilson** [comment]
Hi! All our tests run on Travis CI, which is a linux machine, and do not have this issue. Can you provide any more information?

**Comment by DominikPalo** [comment]
Thanks, it seems that problem was on the Codeship side, after I reseted the dependency cache all works fine.

**Comment by DominikPalo** [comment]
Sorry, it seems that problem is on our test service (Codeship) with their dependency cache... it randomly switches the version of body-parser between v1.12 (I don't know why exactly this version, because I updated the module from version 1.13.3 not 1.12... and 1.12 causes this UTF8 problem) and 1.14.1 version. So I have to reset the dependency cache multiple times, until the version 1.14.1 is installed on VM and then run tests...
