### ISSUE TITLE
Body defaults to `{}` even if type fn returns false

### ISSUE THREAD

**Issue by danpaz** [expressjs/body-parser#146]
What is the expected behavior if the content type of the request doesn't match the type option in the text parser? I think my expectation is that the parser should do nothing; `req.body` should not be populated and should remain `undefined`. 

However, based on [this test](https://github.com/danpaz/body-parser/blob/master/test/text.js#L206-L212) and [this code](https://github.com/expressjs/body-parser/blob/master/lib/types/text.js#L62) it looks like `req.body` gets set to `{}` by default.

This caused a bug in my application because further down the middleware chain I check for the truthiness of `req.body`, and empty object happens to be truthy.
```
!!{} // true
```

**Comment by d6u** [comment]
I think the expected behavior is that if bodyparser is not parsing anything, nothing should be touched.

**Comment by dougwilson** [comment]
You need to use the 2.x branch until it is released. This issue has already been fixed, but 2.x is not yet complete.

    npm install expressjs/body-parser#2.x

Be aware that the current 2.x line does not yet have all the features of 1.x, as we are working on it.

**Comment by dougwilson** [comment]
You can find a previous answer I gave at https://github.com/expressjs/body-parser/issues/128#issuecomment-141500274 if it helps explain more.

I closed this issue because there isn't work to do to fix it, as the work has already been done, just not yet released due to some edge case bugs still being addressed.

**Comment by danpaz** [comment]
Sounds good, thank you!

**Comment by dougwilson** [comment]
I'm going to work tonight on getting a proper alpha published to npm as well.
