### ISSUE TITLE
unable to install body-parser via "npm install body-parser --save"

### ISSUE THREAD

**Issue by malikasinger1** [expressjs/body-parser#147]
npm is saying:

```
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

```

![screenshot 6](https://cloud.githubusercontent.com/assets/14273842/11897045/e5c59df4-a5ad-11e5-9712-9ffce1c1bc46.png)

**Comment by dougwilson** [comment]
The error message indicates that not only is the issue not with this module, but your npm cache is just corrupted. Running `npm cache clean` and trying the install again should fix the issue.

**Comment by WendyMunmunWang** [comment]
I tried to do npm cache clean but still unable to install:

`ERWaitingTime@1.0.0 /Users/wendywang/Documents/CS304/ERWaitingTime
├── angular-timer@1.3.3  extraneous
├── mysql@2.10.2  (git://github.com/felixge/node-mysql.git#1720920f7afc660d37430c35c7128b20f77735e3)
└── node-uuid@1.4.7 

npm WARN ERWaitingTime@1.0.0 No repository field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "body-parser"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.5
npm ERR! path /Users/wendywang/Documents/CS304/ERWaitingTime/node_modules/body-parser
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/wendywang/Documents/CS304/ERWaitingTime/node_modules/body-parser' -> '/Users/wendywang/Documents/CS304/ERWaitingTime/node_modules/.body-parser.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wendywang/Documents/CS304/ERWaitingTime/server/npm-debug.log`

**Comment by dougwilson** [comment]
Hi @WendyMunmunWang, I'm sorry to hear you are having issues using npm, but the error is nothing I can really help with from a module author's point of view. I would suggest reporting the error according to the instructions at the bottom of the message you pasted here.

**Comment by HtooLLwin** [comment]
PS D:\MTU Web\mtu_backend\myapp> npm i sequelize
npm WARN myapp@1.0.0 No description
npm WARN myapp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ sequelize@4.42.0
updated 1 package and audited 2445 packages in 6.544s
found 0 vulnerabilities

**Comment by HtooLLwin** [comment]
i can't solve it
plz help!
