### ISSUE TITLE
Text parser is returning empty object when no body is provided

### ISSUE THREAD

**Issue by mauvm** [expressjs/body-parser#149]
I'm parsing the body as plain text. If no content is provided `req.body === {}`. Why is this? I was expecting an empty string.

See: https://github.com/expressjs/body-parser/blob/7847af6e5a36129eea0e0becfbcc521b839313ae/lib/types/text.js#L62

**Comment by dougwilson** [comment]
https://github.com/expressjs/body-parser/issues/128#issuecomment-141500274

**Comment by mauvm** [comment]
Oops. Forgot to check the closed issues. Sorry for that!

I wish you a Merry Christmas.

**Comment by dougwilson** [comment]
It's no problem at all :) You too.
