### ISSUE TITLE
Application crushes when emoji is passed in request ? 

### ISSUE THREAD

**Issue by igor-yamshchykov** [expressjs/body-parser#150]
Hello, when I'm using json parser and someone pass me a json that contains emoji, the whole application fails and I can't even get stack trace for that error.
I have in my express setup
```javascript
    app.use(bodyParser.json());
```

The JSON example is 

```javascript
{
    "message": " Hello my json  😒"
}
```

I've tried to remove the json parser and app is not crashing, however I need to parse the json anyway, so I think the problem might be somewhere inside the json body parser ?

**Comment by dougwilson** [comment]
Hi! Can you define what application crashes means? Is that a 500 response? 400 response? An uncaught exception or assertion printing to STDERR (and if so, can you paste it here) before the process exits?

For JSON parsing, all we do is take the body and pass it to `JSON.parse`, which is built-in to V8, so if that is what is throwing an exception, I'm not sure there is much we can do.

I tried your body you pasted above and it parsing just fine on Node.js 0.10.38 and 1.14.2 of this library. Are you using different versions from this, and if so, what versions are you using?

Can you provide me with a compete application file to run, the versions of any modules it would need, and the exact call I need to make to reproduce the issue? Alternatively, without that information, I would have to lean on you to just issue us a pull request that fixes the issue.

**Comment by igor-yamshchykov** [comment]
My apologies, It's Web Storm fail, in debug mode it fails when emoji passed in request. Body-parser works very well with those.

**Comment by dougwilson** [comment]
Ah, I see! Thanks for the update :)
