### ISSUE TITLE
can I make a form submit to be parsed into a nested object?

### ISSUE THREAD

**Issue by littlee** [expressjs/body-parser#151]
```html
<form>
    <input type="text" name="a[prop1]" value="12">
    <input type="text" name="a[prop2]" value="34">
</form>
```
and then req.body will look like:
```js
{
    a: {
        prop1: 12,
        prop2: 34
    }
}
```

**Comment by dougwilson** [comment]
Hi! That is the default behavior. Are you unable to get that to work? If so, would you mind showing the relevant bits of your server code?

**Comment by littlee** [comment]
I forget to set extend option to true.
my fault

**Comment by dougwilson** [comment]
It's no problem! That's weird, because the `extend` option defaults to true; it should only not be true is you explicitly set it to false in your own code?

**Comment by littlee** [comment]
Because I use express-generator, the code it generates will set the extend option to false :joy:

**Comment by dougwilson** [comment]
Ah, I see (https://github.com/expressjs/generator/blob/master/templates/js/app.js#L21). Ok, that would explain it :) Eventually this module will default to false on the next major (and just having it on when you didn't intend it can result in some security issues if you expected `req.body` to only be a certain way), so I guess it makes sense for it to default to `false` there.
