### ISSUE TITLE
Test Suite failing on Node.js Master

### ISSUE THREAD

**Issue by TheAlphaNerd** [expressjs/body-parser#155]
Hey all. The latest version of citgm is showing that the test suite for body-parser is not passing on the current master of Node.js

The test suite is passing on all major releases afaik.

Here is the output of the failure

```shell
  176 passing (494ms)
  1 failing

  1) bodyParser.urlencoded() with parameterLimit option with extended: false should work with Infinity limit:

      AssertionError: 0 == 10000
      + expected - actual

      -0
      +10000

      at test/urlencoded.js:666:12
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1525:8)
```

I'm going to dig in and see what we changed that caused this

**Comment by TheAlphaNerd** [comment]
Looks like it is due to a change in querystring. Digging deeper

**Comment by TheAlphaNerd** [comment]
Broken in this PR
https://github.com/nodejs/node/pull/2288
By This Commit
https://github.com/nodejs/node/commit/27def4faf2fb0c759b7e8800f91627cbbca5fdba

Reverting this commit on master allows the test suite for body-parser to work

**Comment by TheAlphaNerd** [comment]
So it looks like this is a regression on master. I'll close this when it has been fixed on master

**Comment by TheAlphaNerd** [comment]
This has been fixed on master in https://github.com/nodejs/node/commit/878bcd43f8f9d3ec0d3403cb1bbe1ba6201a6d84

**Comment by dougwilson** [comment]
Hi @TheAlphaNerd, thanks for the heads-up! I'm glad my tests could be of service :) and I'm happy to hear Node.js pro-actively testing modules and even reaching out :)

**Comment by TheAlphaNerd** [comment]
My pleasure... and kind of my job :smile:

**Comment by dougwilson** [comment]
P.S. @TheAlphaNerd a whole slew of my tests on this module are now failing with the newest Node.js 0.10.42 and 0.12.10. Seems like some kind of breaking change with those security fixes?

**Comment by dougwilson** [comment]
P.S. @TheAlphaNerd a whole slew of my tests on this module are now failing with the newest Node.js 0.10.42 and 0.12.10. Seems like some kind of breaking change with those security fixes?

/cc @jasnell

**Comment by dougwilson** [comment]
Ok, apparently it was https://github.com/nodejs/node/commit/375f35514c51fa603dae9fac86bb61c0503cb678 . Ugh killing the connection vs. at least trying to send back a 400 Bad Request like nginx or something would.

**Comment by TheAlphaNerd** [comment]
@dougwilson I think it would make sense to file this on https://github.com/nodejs/http-parser/issues

**Comment by jasnell** [comment]
Unfortunately yes. The error handling on this is in line with existing
error handling in http-parser but that's still not a great answer. I
definitely plan to revisit this. Error handling on http connections in
general needs to improve significantly.
