### ISSUE TITLE
Parsing outside of the scope of a router?

### ISSUE THREAD

**Issue by sqrtofsaturn** [expressjs/body-parser#156]
Hey, everyone - 

I'm working on a project in which I've defined a bunch of routes in an express router. I also "use" bodyParser in this context.

The problem I'm having is that the bodyparser seems to parse the body of requests that aren't defined in the router.

I'm trying to proxy any requests the router doesn't recognize to a different service, and now that the request stream has been consumed, I can't pipe the request, or use middleware such as express-http-proxy to forward the request.

My understanding is that when I router.use() middleware, that that middleware is scoped to the router. Is this correct?

Attached is code I'm having trouble with. The console.log for req.body will return an object if the router object above "uses" bodyParser, even though the routes are unrelated.

Thanks for your fantastic work, and your time.

    router.use bodyParser.urlencoded limit: '50mb', extended : true
    router.use bodyParser.json limit : '50mb'

    router.get '/v2/devices/:uuid/subscriptions', @subscriptionsController.list
    router.get '/v2/whoami', @whoamiController.show
    router.get '/devices/:uuid', @deviceV1Controller.get
    router.get '/devices/:uuid/publickey', @deviceV1Controller.getPublicKey
    router.get '/v2/devices/:uuid', @deviceV2Controller.get
    router.get '/v3/devices/:uuid', @deviceV3Controller.get
    router.post '/authenticate', @authenticateController.create
    router.post '/search/devices', @searchDeviceController.search
    router.post '/messages', @messagesController.create
    router.delete '/devices/:uuid/tokens', @tokenController.revokeByQuery

    app.use router

    app.use proxy(@meshbluHost, port: @meshbluPort, forwardPath: (req, res) =>
      console.log req.originalUrl
      console.log req.body
      req.originalUrl
    )

**Comment by jordonias** [comment]
I think this is working as expected. The api docs state `A router behaves like middleware itself`.
http://expressjs.com/en/api.html#router

You can test this behavior:

```
var express = require('express');

var app = express();
var router = express.Router();

router.use(function(req, res, next) {
  req.test = 'foo';
  next();
});

app.use(router);

app.get('/', function(req, res, next) {
  console.log(req.test);
  res.end();
});

app.listen(3000);
```

Output: `foo`

But if you set a path on `.use()`:

```
router.use('/somepath', function(req, res, next) {
  req.test = 'foo';
  next();
});
```

Output: `undefined`

**Comment by redaphid** [comment]
Alright. Thanks for looking into it! I was just trying different methods of excluding only the catchall route from bodyParser.
