### ISSUE TITLE
I can't seem to be able to use UTF-8 values

### ISSUE THREAD

**Issue by Nesh108** [expressjs/body-parser#157]
Hello,

I am using body-parser and express for my API.
Here is my current setup (quite standard):

```
app.use(bodyParser.urlencoded({ extended : true }));
app.use(bodyParser.json());

// other

.post(function(req, res) {
    console.log(req.body.strings);
}
```

I am sending UTF-8 values as a POST request:

e.g.

{
"strings: {"Test": "Сущая", "Test2", "Следующаяующая"}
}

I tried setting the content-type header to charset=utf-8, using bodyParser.text and much more. How can I handle UTF-8 properly with bodyParser?

**Comment by dougwilson** [comment]
Hi @Nesh108, sorry I didn't respond earlier! I'm glad to hear you were able to resolve your issue!
