### ISSUE TITLE
req.body undefined

### ISSUE THREAD

**Issue by adals** [expressjs/body-parser#158]
here is my code  and I used postman in chrome in post verb to add json like `{aaa:'bbb'}` but always the result is `{}`
```js
var express=require('express'),
    bodyParser = require('body-parser'),
    mongoose=require('mongoose'),
    app=express(),
    port=process.env.PORT||3000;

var jsonParser = bodyParser.json({ type: 'application/*+json' } );
var productsRouter=express.Router();


productsRouter.post('/add',jsonParser,function(req,res){
       res.send(req.body);
});
app.use('/products',productsRouter);

app.listen(port,function(){
    console.log('your server is running');
});
```

**Comment by dougwilson** [comment]
Hi @adals, this is because the type you set in your code, `application/*+json`, does not match the type you are sending from postman in Chrome.

By default, postman will use the default Content-Type `application/json` unless you set a `Content-Type` header yourself to a different value.

There are two possible solutions for you here, depending on if you really wanted to use the type `application/*+json` or it was included in your code by accident:

1. If you need to use the type `application/*+json` for some reason, you just need to use a different type in postman. You can do this by adding the `Content-Type` header with a value like `application/vnd+json`.
2. If you included `application/*+json` in your code by accident, just remove that. Your code will become simply `bodyParser.json()`.

**Comment by adals** [comment]
thank you very much for your reply
here is my code after editing

var express=require('express'),
    bodyParser = require('body-parser'),
    mongoose=require('mongoose'),
    app=express(),
    port=process.env.PORT||3000;

var jsonParser = bodyParser.json();
var productsRouter=express.Router();


productsRouter.post('/add',jsonParser,function(req,res){
    res.send(req.body);
});
app.use('/products',productsRouter);

app.listen(port,function(){
    console.log('your server is running');
});

and I sent json {aaa:'bbb'}   and result still empty {}

**Comment by dougwilson** [comment]
Hi @adals, sorry to hear that, but unfortunately there isn't enough information for me to provide any additional help. The only thing that sticks out is that `{aaa:'bbb'}` is not valid JSON, it would need to be `{"aaa":"bbb"}` to work. But even then, you'd get a 400 back. What are you setting the `Content-Type` header to in your Postman request?

**Comment by adals** [comment]
I got 200 response

**Comment by tunniclm** [comment]
@adals I tried running the code in your comment above on the current express, body-parser and mongoose and got the following:

```
$ nc localhost 3000
POST /products/add HTTP/1.1
Content-Type: application/json
Content-Length: 11

{aaa:'bbb'}
HTTP/1.1 400 Bad Request
X-Powered-By: Express
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 980
Date: Tue, 23 Feb 2016 17:28:16 GMT
Connection: keep-alive

SyntaxError: Unexpected token a<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/home/tunniclm/Projects/expresstst/body-parser-158/node_modules/body-parser/lib/types/json.js:88:17)<br> &nbsp; &nbsp;at /home/tunniclm/Projects/expresstst/body-parser-158/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/home/tunniclm/Projects/expresstst/body-parser-158/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/home/tunniclm/Projects/expresstst/body-parser-158/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/tunniclm/Projects/expresstst/body-parser-158/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at emitNone (events.js:80:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:179:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:906:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:474:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:388:17)
```

and:

```
$ nc localhost 3000
POST /products/add HTTP/1.1
Content-Type: application/json
Content-Length: 13

{"aaa":"bbb"}
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 13
ETag: W/"d-lvT6GYhl1+ZUaoEncD318Q"
Date: Tue, 23 Feb 2016 17:30:47 GMT
Connection: keep-alive

{"aaa":"bbb"}
```

I ran on Linux with Node.js v5.5.0, body-parser@1.15.0, express@4.13.4, mongoose@4.4.4.

If we can work out what is different between your test and mine it will help get to the bottom of the problem.

**Comment by adals** [comment]
thanks for your help 

the problem was solved but its strange I think its a bug at postman because I must put Content-Type in the header which already exist 

here is the result when I put Content-Type at the header and it works and I got my json

X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 16
ETag: W/"10-b02PSFe4pgHN9I1MAdW30A"
Date: Tue, 23 Feb 2016 18:16:58 GMT
Connection: keep-alive

but when I remove Content-Type from the header but it still exist as shown below the result will be with empty {}


X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 2
ETag: W/"2-mZFLkyvTelC5g8XnyQrpOw"
Date: Tue, 23 Feb 2016 18:19:22 GMT
Connection: keep-alive

**Comment by dougwilson** [comment]
Hi @adals, you are looking at the `Content-Type` header in the HTTP response from the server, which has nothing to do with the `Content-Type` Postman send to the server. When you remove the `Content-Type` from postman, it's not sending it, thus why you get the empty `{}` response.

**Comment by adals** [comment]
thanks for your help
