### ISSUE TITLE
JSON.parse failed in case of non ASCII characters in body

### ISSUE THREAD

**Issue by yarax** [expressjs/body-parser#159]
Hi everyone!

In JSON parse as reviver function is used _urlencoded, which escapes non URL characters with backslashes and they are of course not JSON friendly

Is it possible to avoid such behavior with existing methods without PR?

**Comment by dougwilson** [comment]
Hi @yarax, I'm not sure what you're asking, I'm sorry. Can you elaborate, or provide an example, please?

**Comment by yarax** [comment]
Sorry, it seems that the problem is in the client library, that set wrong content-length because of such characters.

**Comment by yarax** [comment]
@dougwilson sorry seems that the problem is in the library that set wrong content-length because of these symbols

**Comment by dougwilson** [comment]
Ah, gotcha! Yea, that seems to be a fairly common problem in clients, where they incorrectly calculate the value for `Content-Length` based on characters of glyphs instead of bytes after encoding.
