### ISSUE TITLE
body-parser for json behaves differently in 1.4.3 and in later versions

### ISSUE THREAD

**Issue by anuradhag** [expressjs/body-parser#164]
When I use body-parser 1.4.3, the request body retains boolean and array values.

For later versions (I tested with 1.9 and later), converts boolean to string and array to comma delimited strings. 

Is this expected behavior?

**Comment by dougwilson** [comment]
Hi @anuradhag, no that is not expected, and I'm not able to reproduce. All the JSON parser does is just use `JSON.parse(str)` on your platform, nothing else. I would suggest you either look at making a pull request to fix the issue, or you can provide the following information for us to look into:

1. Version of Node.js
2. Version of this module 
3. Complete code that reproduces the issue. It needs to be a single file and I will copy paste it and run it. Please do not use any other modules besides this one and Node.js core modules, unless you are trying to demonstrate this module not working with another.
4. Complete steps to run that script, how to reproduce the issue, and how to know I am reproducing it.

**Comment by anuradhag** [comment]
@dougwilson  As you rightly said, this is not a body-parser issue. We sanitize incoming requests using google-caja which messes up with the json. Need to fix that.
Thank you for your time.

**Comment by dougwilson** [comment]
Ah, glad you figured it out! No problem :)
