### ISSUE TITLE
Content-Type appears case-sensitive

### ISSUE THREAD

**Issue by adamierymenko** [expressjs/body-parser#165]
It seems like body-parser doesn't recognize the content-type header unless it is *exactly* `Content-Type`. Mixed case like `Content-type` or `content-type` doesn't seem to work. According to the HTTP spec it should be case insensitive, though nearly all browsers send `Content-Type`.

**Comment by dougwilson** [comment]
All of our tests send the header with the capital C and capital T and they work. It sounds like something else is going wrong in your code.

If you think there is an issue with this module, then I'll need the following:
1.Version of Node.js
2.Version of this module 
3.Complete code that reproduces the issue. It needs to be a single file and I will copy paste it and run it. Please do not use any other modules besides this one and Node.js core modules, unless you are trying to demonstrate this module not working with another.
4.Complete steps to run that script, how to reproduce the issue, and how to know I am reproducing it.

**Comment by dougwilson** [comment]
> All of our tests send the header with the capital C and capital T and they work. It sounds like something else is going wrong in your code.

Sorry, I misunderstood your statement initially. Please provide all four pieces of information so I can reproduce the issue. I just tried all lower case locally and it worked just fine.
