### ISSUE TITLE
Display error 'request aborted', get or post request is too large?

### ISSUE THREAD

**Issue by a348730140** [expressjs/body-parser#171]
```javascript
Error: request aborted
    at IncomingMessage.onAborted (C:\Users\Administrator\node_modules\body-parser\node_modules\raw-body\index.js:269:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.serverSocketCloseListener (_http_server.js:293:5)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

my code:
```javascript
var express = require('express');
var app = express();
var bodyParser = require('body-parser');

app.listen(570);
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.get('/', function (req, res) {
   ...
});
app.post('/', function (req, res) {
   ...
});
```

But I guess the request does not exceed 100kb

**Comment by dougwilson** [comment]
Hi @a348730140! The error `Error: request aborted` is somewhat expected, as that error is from Node.js telling us that the TCP socket has closed before we finished reading the request. This does not mean that request is too large, though. The most common causes for this:

1. User is submitting a form and closes the web browser/browser tab.
2. User is uploading using a command line tool like cURL and presses Ctrl+C to kill the process.
3. Some network issue that kills the TCP connection.

I hope this helps!

**Comment by AskYous** [comment]
Hey @dougwilson, I'm trying to get a better understanding of how this works. Does this mean that multiple messages are sent between the server and the client when the client send an HTTP POST message to a server? Meaning the messages are (for example):

1. Client to server: 'Hey, I'm making an HTTP POST call, get ready.'
2. Server to client: 'I'm ready, send it.'
3. *User ends his web session*
4. Client to server: 'Nevermind.'
5. Server: 'Ok, throwing an error.'

Is that the right idea?

**Comment by dougwilson** [comment]
Hi @AskYous, that can be a scenario. If you are getting the error, a capture of the request/response with a tool like Wireshark can shed light on exactly which side and for what reason the request is being aborted.

**Comment by robvandjdk** [comment]
Thought I would mention this as a weird gotcha that had me stuck for a while.  I was using PostMan and copied the headers from a browser request in order to get the authorization token.   
The Content-Length: 58 portion of the header caused this error somehow.  It was a strange error and took me several hours of pulling my hair out before I found it.  Maybe recording this here saves someone some time?

**Comment by TotallWAR** [comment]
I have the same issue when i send post request by Postman

**Comment by Setitch** [comment]
IS there a way to sign up to this error and not show it as it's done but wrap it into my own error handler?

**Comment by kevintanhongann** [comment]
I was writing a JVM based reverse proxy and did a POST request to an ExpressJS endpoint and had this error. What should I do to the reverse proxy so that I can send the request over properly?

**Comment by robertvandewater** [comment]
kevintanhongann,

I would try changing the headers that the JVM server puts on the request to the ExpressJS endpoint.

**Comment by kevintanhongann** [comment]
@robertvandewater I didn't recall I set anything to the header as well. Strange.

**Comment by Eksapsy** [comment]
I had this error just today, and as it seems it was because of **Internet Explorer**. When my client tried it on **Chrome**, it worked fluently, but on **IE** there were this Request Interruptions which immediately caused this Request Aborted error.

How can this be fixed? Any idea?
