### ISSUE TITLE
Cannot install body-parser using npm

### ISSUE THREAD

**Issue by msoula** [expressjs/body-parser#175]
Hi guys, i'm not sure this is the place for this kind of issue.

I can't install body-parser module using npm, here is what npm returned:
$ npm install body-parser --save
> npm WARN package.json mongodb@2.1.18 No README data
> npm ERR! cb() never called!
> npm ERR! not ok code 0

node version is: 0.10.29
npm version is: 1.4.21

**Comment by msoula** [comment]
Well i guess it was temporary: i can"t reproduce it.

**Comment by dougwilson** [comment]
Hi @msoula, the `npm ERR! cb() never called!` is a typical race condition you can encounter in the version of the `npm` you are using. If you are able, you may want to consider upgrading your npm, or retry installations when that occurs.

**Comment by msoula** [comment]
Ok @dougwilson, thank you for your answer. I finally installed body-parser, but i'll try to upgrade npm to prevent more similar problems.
