### ISSUE TITLE
Missing documentation for error situations

### ISSUE THREAD

**Issue by paulrutter** [expressjs/body-parser#177]
I've encountered a production issue where requests would stay open and deduced it to be caused by the bodyParser "limit" feature.
In the end, it was my own fault, because the requests that were bigger than the limit were never explicitly ended, causing them to use up memory.

My code:

```
// parses the body when its content-type header is "application/json"
// Set the body size limit to 1mb, because the default 100kb is too small
app.use(/\/((?!abc).)*/, bodyParser.json({
  limit: '1mb'
}));

// some more middleware

// add catch-all error handler
app.use(function(err, req, res, next) {
  if (err && err.status === 413) {
    console.warn("Request entity too large encountered for request");
  } else {
    // other errors just bubble through
    next(err);
  }
});
```

The code misses the line were it explicitly ends the request:
```
// add catch-all error handler
app.use(function(err, req, res, next) {
  if (err && err.status === 413) {
    console.warn("Request entity too large encountered for request.");

    // Explicitly end the request in that case
    res.status(err.status).end();
  } else {
    // other errors just bubble through
    next(err);
  }
});
```

Maybe we can make this more clear in the documentation?
When using a "catch-all" error handler, make sure you end the request yourself!
What do you think? Great stuff by the way.

**Comment by dougwilson** [comment]
Hi! Unfortunately I am not going to add that. This module works on more than just express and how to create proper express error handlers is something express should be documenting, not every single express middleware.

**Comment by paulrutter** [comment]
Hmm you're right, i didn't think of the fact that this module runs on more than express.
Although, it might be worth mentioning that this module does not end the request; it just indicates that there is an error.

**Comment by dougwilson** [comment]
> Although, it might be worth mentioning that this module does not end the request; it just indicates that there is an error.

Again, sorry, no. For express middleware that is a given. No middleware ever ends the response unless it explicitly says so. That is the difference between a "middleware" and a "handler" in express. This module is a middleware and does errors like every single express middleware ever.

**Comment by paulrutter** [comment]
Ok, thanks for the clarification :)

**Comment by dougwilson** [comment]
So I looked and here is the documentation for error handlers: http://expressjs.com/en/guide/error-handling.html

Though they do it in all examples, I didn't see anywhere in writing explicitly call out that you need to write a response if you don't call "next(err)".

If you like, at the bottom of the page is an edit this page link to make a pull request to their repo to make the addition you're looking for, otherwise you can file an issue at https://github.com/expressjs/expressjs.com

**Comment by paulrutter** [comment]
Thanks, i will!

**Comment by paulrutter** [comment]
Done: https://github.com/expressjs/expressjs.com/pull/656
