### ISSUE TITLE
Maximum call stack issue with meteor.

### ISSUE THREAD

**Issue by CaptainChemist** [expressjs/body-parser#183]
There seems to be an issue where when I use body-parser in a meteor project, and then try to add meteor-node-stubs package I get the following error:
`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

I can reproduce this issue by installing:
`git clone https://github.com/themeteorchef/base.git 
`
then running:
```
meteor npm install --save body-parser
meteor npm install --save meteor-node-stubs
```

Anyone know why that would happen?

**Comment by dougwilson** [comment]
Hi @CaptainChemist, I really have no idea and there is not enough information for me to help you. I tried to at least run the commands you gave, but get the following error:
```
$ meteor npm install --save body-parser
bash: meteor: command not found
```

How can I proceed?

**Comment by CaptainChemist** [comment]
I'll close this issue but the reason why you got that error is that you didn't install meteor:

curl https://install.meteor.com/ | sh

**Comment by dougwilson** [comment]
Thanks, @CaptainChemist! I'd be happy to investigate, but I've just never used meteor before, so I had no idea how to install it, and really, have no idea if the issue you posted is truly from this module. I tried the command you gave, but it doesn't work on my Windows machine. Maybe it could be easier just to attach a debugger to the instance you are running that has the issue and just track down the cause of the error? That is what I would do here once I can get it running.
