### ISSUE TITLE
json parser won't parse simple number

### ISSUE THREAD

**Issue by ReinsBrain** [expressjs/body-parser#185]
body-parser is throwing a SyntaxError when a simple type is submitted as JSON... for example a simple number: 1 throws SyntaxError message "Unexpected token 1"

Early versions of JSON (such as specified by RFC 4627) required that a valid JSON "document" must consist of only an object or an array type, which could contain other types within them. This restriction was removed starting with RFC 7158, so that a JSON document may consist entirely of any possible JSON typed value.

The issue occurs here: https://github.com/expressjs/body-parser/blob/bd386d3a7d540bac90bbdaff88f653414f6647fc/lib/types/json.js#L78

We can get around it by passing strict:false to the bodyParser.json constructor. I would like to suggest that instead strict:false is the default. Or perhaps even remove the strict thingy entirely because I can't think of any reason why it needs to exist.

**Comment by dougwilson** [comment]
Thanks for the feedback, @ReinsBrain! The document RFC 7158 is listed as published March 2013, while that restriction was contributed to this module in Feb 2012 (commit https://github.com/senchalabs/connect/commit/ff0637cb52dfdd171664211f4b53883310682ccd). We can definitely bring this module to up date to the new standards with the next major version!

**Comment by GrosSacASac** [comment]
this change is a breaking change for some

**Comment by blakeembrey** [comment]
@GrosSacASac There's no change here. Can you please provide more information to go on?

**Comment by imZack** [comment]
just bumped into this issue, this should have a quick fix.

**Comment by phra** [comment]
related to #279

**Comment by ReinsBrain** [comment]
I'm going to close this issue because the change recommended is not backwards-compatible and, while not completely intuitive, passing strict:false to the bodyparser constructor solves the problem.
