### ISSUE TITLE
Getting `genres[]` as key

### ISSUE THREAD

**Issue by franciscop** [expressjs/body-parser#186]
I am getting this:

```js
{ 
  // ...

  'genres[]': 'test',
  'genres[]': 'test1',
  'genres[]': ''
}
```

With this jade:

```jade
input(name='genres[]' type='text')
input(name='genres[]' type='text')
input(name='genres[]' type='text')
```

And this:

```js
{
  // ...
  'genres[0]': 'test',
  'genres[1]': 'test1',
  'genres[2]': '',
}
```

With this jade:

```jade
input(name='genres[0]' type='text')
input(name='genres[1]' type='text')
input(name='genres[2]' type='text')
```

***

I am using Node.js V6.2.2, with this in my app.js:

```js
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
```

The problem seems to be mentioned [in this issue](https://github.com/expressjs/body-parser/issues/25), however it was about another thing so it's not really addressed.

**Comment by blakeembrey** [comment]
@franciscop Non-extended body parsing uses the built-in node querystring parser. It does not support any square bracket notation. Can you specify the issue you are reporting?

For now I'll assume you want to report that it should be an array. The node querystring parser does not transform square bracket notation and treats it all as a key, so your output is expected. If the key is repeated, it becomes an array automatically. If you wish to access the key, you need to use JavaScript's square bracket notation - `req.body['genres[]']`, but I'd recommend you just use a normal key `genres` and use a util like `arrify` to always treat it as an array.

**Comment by franciscop** [comment]
I was reporting that I thought it'd be parsed as `genres` instead of `genres[]` inside `req.body`, sorry for not being clear. AFAIK, the extended is to allow only strings and arrays to avoid some vulnerabilities, and this *is* an array, that's why I expected it to be converted automatically.

However, if that is by design, I will just add a small fix in my code. I add it here for anyone who might be interested:

```js
app.use(function(req, res, next){
  if (req.body) {
    for (var key in req.body) {
      if (/\[\]$/.test(key)) {
        req.body[key.replace(/\[\]$/, '')] = req.body[key];
        delete req.body[key];
      }
    }
  }
  next();
});
```

It just changes all the `req.body` variables that end up with `[]` with a key with the same name but without the `[]`. Of course it's not bulletproof, just what it works for my case.

**Comment by blakeembrey** [comment]
It is by design of node-core. Extended mode uses the `qs` module instead, which does support the notation you want: https://www.npmjs.com/package/qs. The code you posted just wipes out each previous key to without the bracket notation. Seems like overhead when it's the same thing to use `req.body['genre[]']` to access it. However, I'd do as I mentioned above.
