### ISSUE TITLE
raw() parser: if body is empty, req.body is set to empty object

### ISSUE THREAD

**Issue by Olivier-OH** [expressjs/body-parser#187]
I think the correct behaviour should be to have an empty string body.

**Comment by dougwilson** [comment]
Hi @Olivier-OH, defaulting to a string in the raw parser does not make sense, since a successful raw parse results in a `Buffer` object, not a string. Besides, we actually went ahead and fixed these semantics in the 2.0 branch. Please go ahead and check out the proposed 2.0 release in #66 :)

**Comment by molomby** [comment]
@dougwilson: You're right that defaulting to a string doesn't make sense but the issue @Olivier-OH reported is still valid.

The [docs](https://www.npmjs.com/package/body-parser#bodyparserrawoptions) indicate the raw body parser should always produce a body object that is a Buffer. In the current version (v1.15.2) this is not the case.

Specifically, when the raw parser is used, requests with an empty/zero-length body (eg. `GET` requests), result in the body object being an empty `Object`.

Surely, in this case, the body should be an empty `Buffer`.
