### ISSUE TITLE
Return error from verify 

### ISSUE THREAD

**Issue by ugolas** [expressjs/body-parser#189]
Is there a way to propagate an error from the verify method (i'm using express)?

I want to block requests which contain duplicate properties (the json body parser does not fail these requests).

My code:
```js
router.use(bodyParser.json({
  verify: function(req, res, body) {
    if (has_dupes){
        fail with error...
    }
  }
}));
```

**Comment by dougwilson** [comment]
Simply throw the error in the verify function, and we propagate that error.
