### ISSUE TITLE
unsupported charset GBK

### ISSUE THREAD

**Issue by haoyong** [expressjs/body-parser#192]
i got a problem "unsupported charset GBK", how to solve it?

**Comment by dougwilson** [comment]
Hi @haoyong, I am able to use the charset "GBK" just fine. Can you provide the following information to help us look into your issue?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete code that reproduces the issue we can copy and paste and run.
4. Complete instructions of exactly what to do to cause the issue.

**Comment by dougwilson** [comment]
Hi @haoyong, I'm going to close this issue since I haven't heard back in a while. If you reply here, I'll gladly re-open the issue!
