### ISSUE TITLE
Inexplicably hanging

### ISSUE THREAD

**Issue by JustinLivi** [expressjs/body-parser#193]
Hi,

I'm having a tough time tracking down a hanging request in my express application.
I traced it to the bodyParser.json middleware through extensive logging. My error middleware is never hit. Setting the DEBUG env variable to `body-parser:json` gets me the following traces:

```
body-parser:json content-type "application/json" +9ms
body-parser:json content-encoding "identity" +0ms
body-parser:json read body +0ms
*hangs here*
```

As far as I can tell this should look more like this:
```
body-parser:json content-type "application/json" +115ms
body-parser:json content-encoding "identity" +0ms
body-parser:json read body +0ms
body-parser:json parse body +0ms
body-parser:json parse json +0ms
```

The body of my request is very simple: `{ transaction_id: 'project1' }`

The request is proxied through a few node services higher in the stack so it's likely that the source of my error is actually there, but I can't figure out why it would hang here. Is there a recommended approach for debugging this? It concerns me that even if the source of my error is upstream in my own code that an outside request could cause the application to hang like this.

Within the express app the only middleware higher than the body parser is express-session middleware and my own logging middleware which is entirely stateless (as far as I know).

**Comment by dougwilson** [comment]
Hi @JustinLivi, I'm not sure how much help I can be if I'm not able to reproduce the issue. You may want to go as far as either writing your own simple body parser to see if it is an issue with this module or your upstream. You can also try using Wireshark and providing the packet capture as well of the hanging request.

As for hanging, this module does not provide any timeout options currently, so it is up to you to write or use middleware that will keep a request from hanging in your app, as any middleware can cause hanging conditions. Of course "hanging" for a body parser can mean all kinds of things, and it is a difficult problem to solve. Currently this module will simple wait until your Node.js socket timeout occurs, which is 2 minutes by default if I remember correctly. You should probably tune that time to fit your server requirements.

**Comment by JustinLivi** [comment]
Ah as suspected this was entirely my fault. The service was never actually being sent the data because my buffer was empty before the request was actually made so body-parser was just waiting for the data to parse. Many thanks for your help!

**Comment by dougwilson** [comment]
Awesome, I'm glad you were able to figure it out 👍
