### ISSUE TITLE
regex support

### ISSUE THREAD

**Issue by robsilva** [expressjs/body-parser#195]
Hi there,

Does body-parser support Regex?
I need to parse a form where the input names are created dynamically:
e.g.: <input name="question-57c88775992af4c84f99c5d0" type="text"/>

```
var questions =  req.body[/^question-/i];    // something like this

 Answer.findOneAndUpdate({ _user: req.user._id }, {
      _poll               : req.params.poll_id,
      _user               : req.user._id,
      _question         : questions,        // <-- then push array of object Id's here
      answer              : 'test answer',
    }, function(err, poll){
        if(err) return next(err);
        res.redirect('/polls/'+poll.id);
    });

```

Thanks in advance!

**Comment by dougwilson** [comment]
I'm not certain what the question is. Are you asking how to iterate over keys in an object in JavaScript?

**Comment by robsilva** [comment]
Nevermind, I just realized the answer. :)
I can iterate through req.body looking for property names that match my regex.
Thanks for the hint, @dougwilson :)

**Comment by dougwilson** [comment]
No problem!
