### ISSUE TITLE
Document whether the JSON parser will also accept JSON with a text/plain content type

### ISSUE THREAD

**Issue by kevinburke** [expressjs/body-parser#196]
As far as I understand it, API's that accept JSON encoded request bodies are not vulnerable to CSRF attacks, since the only content-types that can be submitted as part of a form are form-urlencoded, multipart, and text/plain. However, [a text/plain request could contain valid JSON](http://stackoverflow.com/a/10788953/329700).

I'm hoping that `bodyParser.json()` only populates `req.body` if the request is submitted with an `application/json` content-type, not from a `text/plain` content-type. It's unclear from the README whether this is true. I'm writing a toy program now to verify it.

**Comment by kevinburke** [comment]
Looks like it just sets req.body to the empty object.

```javascript
express = require('express');
var bodyParser = require('body-parser');
var app = express();
app.use(bodyParser.json());
app.listen(3000);
app.post('/', function(req, res) {
  console.log('body', req.body);
  res.status(200).json(null);
});
```

Request:

```python
import requests
r = requests.post('http://localhost:3000', headers={'Content-Type': 'text/plain'}, data='{"foo": 7}')
print r.status_code
print r.headers
```

```
T ::1:59754 -> ::1:3000 [AP]
  POST / HTTP/1.1..Host: localhost:3000..Connection: keep-alive..Accept-Encoding: gzip, deflate..Accept: */*..User-Agent: python-requests/2.11.1..Content-Type: text/plain..Conten
  t-Length: 10....{"foo": 7}
##
T ::1:3000 -> ::1:59754 [AP]
  HTTP/1.1 200 OK..X-Powered-By: Express..Content-Type: application/json; charset=utf-8..Content-Length: 4..ETag: W/"4-N6YlnMDB2uKZp4Zkid/wvQ"..Date: Fri, 02 Sep 2016 22:50:08 GM
  T..Connection: keep-alive....null
```

**Comment by dougwilson** [comment]
The README for the JSON type already states it only accepts requests with the content type " application/json "
