### ISSUE TITLE
body-parser not works in GET method

### ISSUE THREAD

**Issue by jinchizhong** [expressjs/body-parser#197]
It's look like body parser is disabled in GET methods.
But somebody really use GET methods in this way.
Such vultr API.

curl is also support send body when do get request.
Will consider to fix this problem?

**Comment by dougwilson** [comment]
This module works just fine on the GET method. Can you elaborate on the issue you are having? Perhaps we can help get you working. Our tests verify that all the parsers work on all HTTP methods except the `CONNECT` method.

**Comment by jinchizhong** [comment]
Sorry, my mistake...

I used a wrong curl command.....

Sorry again, for waste your time.

**Comment by dougwilson** [comment]
It's no problem. Glad you got it working :)

**Comment by jinchizhong** [comment]
@dougwilson Thank you.
:)
