### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by ifxsoftware** [expressjs/body-parser#198]
Been getting PUT requests that are large....
addressing this by upping my limits but not knowing the original
length of the message that triggered or if my limit setting is being used
make this tricky.

Would be a nice feature to simply add the length and limit to the error message as seen below.... 

    return done(createError(413, 'request entity too large ' + length + ' ' + limit, 'entity.too.large', {

apologies if this has been discussed already
Thanks!

**Comment by dougwilson** [comment]
The message is meant to be sent back to the user. You should be looking at the `limit` and `length` properties of the error object, as documented at https://github.com/expressjs/body-parser#request-entity-too-large :)
