### ISSUE TITLE
`req.body` never falsy, README example wrong

### ISSUE THREAD

**Issue by gima** [expressjs/body-parser#199]
As per README example in https://github.com/expressjs/body-parser/blame/master/README.md#L375
> ```javascript
> app.post('/api/users', jsonParser, function (req, res) {
>   if (!req.body) return res.sendStatus(400)
>   // create user in req.body
> })
> ```

`req.body` is never falsy, as it's set to empty object (`{}`) in:
- https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L75
- https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L98

**Comment by dougwilson** [comment]
In the example, it is falsy when a non-JSON request was POSTed. i.e. POST with `Content-Type: text/plain`.

**Comment by dougwilson** [comment]
oops, was thinking 2.0. Yes, the example is wrong, if you can make a PR to fix it, please.

**Comment by gima** [comment]
Hands full, I'll pass, apologies.

**Comment by dougwilson** [comment]
No problem! Without a clear owner of who will make the docs changes, I'm going to close the issue.
