### ISSUE TITLE
bodyParser LIMIT option not working

### ISSUE THREAD

**Issue by Miwrzezl** [expressjs/body-parser#202]
I currently have

```js
app.use(bodyParser());
app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
```

but the limit is not being set as I still get `Error: request entity too large`. I've tried setting the limit higher, but no success.

**Comment by dougwilson** [comment]
This is because your first line, `app.use(bodyParser());` is handling all the types first, and you're not setting any custom limit on that line. I recommend simply removing that line.

**Comment by Miwrzezl** [comment]
By doing so, it fixed it! Thanks
