### ISSUE TITLE
body-parser-json with highest integer

### ISSUE THREAD

**Issue by hoanghiep** [expressjs/body-parser#204]
javascript number is in range +/- 9007199254740991.

How can i use body-parser-json in the right way if req.body has a number out of range?

**Comment by dougwilson** [comment]
The module on npm, https://www.npmjs.com/package/body-parser-json , is not this module. Please ask the author to update the metadata on the `body-parser-json` package to point to their own GitHub repository.

**Comment by dougwilson** [comment]
Here is the repository, looking at the author's GitHub profile: https://github.com/iamblue/body-parser
