### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by matthiasg** [expressjs/body-parser#208]
Once body parser does its thing is there a way to access the original e,g, textual content for application/json type requests ?

**Comment by dougwilson** [comment]
Hi @matthiasg , there are a couple different ways, but they would depend on your use-case. Can you explain what you are trying to do with the original content?

**Comment by matthiasg** [comment]
A colleague of mine had the necessity to send a body back exactly as he received it with a prefix prepended (paypal api). It turned out to be sufficient to restringify the parsed body, but it would have been more in line with the specifications to not go through parsing and stringifying for this one route even though all other routes would need the parsed body.

**Comment by dougwilson** [comment]
Gotcha. So I would say for that kind of use-case, especially since it sounds like you didn't need the parsed body for that route at all, would be to change that route to use the `raw` or `text` parser so it can echo back a prefixed string. Very simple example, since I don't have the full details of what you're trying to accomplish:

```js
app.post('/paypal', bodyParser.text({ type: 'json' }), function (req, res) {
  if (typeof req.body !== 'string') return res.send(400)
  res.type('text').send('prefix-' + req.body)
})
```

**Comment by matthiasg** [comment]
@dougwilson i actually do need the parsed body too for some internal computing but we could do that manually of course. I actually did not inspect the internals of the connect pipeline am I correct in assuming that app.use( ... ) of body parser does not preclude the ability to use it in the app post statement directly ?

**Comment by dougwilson** [comment]
> i actually do need the parsed body too for some internal computing but we could do that manually of course

Ah gotcha, I guess I misread your comment, sorry! So what you can do in that case is of course manually `JSON.parse` the text string or some times people will use the `verify` function as a hack to save the raw `Buffer` object on `req`.

> I actually did not inspect the internals of the connect pipeline am I correct in assuming that app.use( ... ) of body parser does not preclude the ability to use it in the app post statement directly ?

It would, which is one of the reasons we try to push people away from that in our documentation:

> This example demonstrates adding body parsers specifically to the routes that need them. In general, this is the most recommended way to use body-parser with Express.

**Comment by matthiasg** [comment]
@dougwilson good to know, thanks :)

**Comment by tybro0103** [comment]
+1 for still having access to the raw request body even after parsing. For example, I want to parse requests from the Slack API, but I also need access to the raw body to verify the signature on the request. ([see here](https://api.slack.com/authentication/verifying-requests-from-slack#verifying-requests-from-slack-using-signing-secrets__a-recipe-for-security__step-by-step-walk-through-for-validating-a-request))

**Comment by dougwilson** [comment]
Hi @tybro0103 the `verify` parameter in each of the body parsers allow you to access the raw body for exactly that purpose.
