### ISSUE TITLE
JSON parser option to not throw error?

### ISSUE THREAD

**Issue by jonathanGB** [expressjs/body-parser#210]
Hi,

I'm using the json parser, like so: `app.use(bodyParser.json())`. However, I've noticed that if you send bad data, the server crashes because the native `JSON.parse()` method throws an error.

Wouldn't it be a good thing to have an option like this:
```javascript
bodyParser.json({
  throwsError: false
})
``` 

If the flag is set to `false`, then the app returns something like `400: Bad Request` when the JSON is not the right format.

**Comment by dougwilson** [comment]
Hi! This module is mot crashing your app by throwing an error on bad data; this module catches the error from JSON.parse and passes it via next(err) like any other middleware. If you do not have any custom error handler, then Express automatically sends back a 400 from this. If you do have a custom error handler, you'll need to code that in.

**Comment by jonathanGB** [comment]
Ok, thanks !
