### ISSUE TITLE
body-parser collapses arrays, cannot handle checkbox arrays on forms

### ISSUE THREAD

**Issue by JC3** [expressjs/body-parser#211]
Consider:

index.js:
```
    var express = require("express");
    var site = express();
    
    site.use(require("body-parser").urlencoded({extended:true}));
    
    site.get("/", function (req, res) {
    	res.sendFile(__dirname + "/test.html");
    });
    
    site.post("/form", function (req, res) {
    	res.json(req.body);
    });
    
    site.listen(8081);
```
test.html:
```
    <html>
    	<body>
    		<form method="post" action="/form">
    			<input type="checkbox" name="option[0]" value="1">
    			<input type="checkbox" name="option[1]" value="1">
    			<input type="checkbox" name="option[2]" value="1"><br>
    			<input type="text" name="text[0]"><br>
    			<input type="text" name="text[1]"><br>
    			<input type="text" name="text[2]"><br>
    			<button type="submit">Submit</button>
    		</form>
    	</body>
    </html>
```
In that example, if I were to check only `option[1]`, I verify that the index is set correctly by inspecting the request in Chrome, body is:

    option[1]:1
    text[0]:
    text[1]:
    text[2]:

Yet body-parser collapses the `option` array and produces the following in `req.body`:

    {"option":["1"],"text":["","",""]}

Similarly, if I were to check `option[0]` and `option[2]`, the request body would look like:

    option[0]:1
    option[2]:1
    text[0]:
    text[1]:
    text[2]:

But it would be parsed to:

    {"option":["1","1"],"text":["","",""]}

I lose all information about which checkbox was checked.

Is this a bug? A feature? If it's a feature, is there a way to make this work? Perhaps a way to disable removal of holes in arrays?

See also http://stackoverflow.com/questions/41092859.

**Comment by dougwilson** [comment]
Hi @JC3 when `extended: true` is given, the parsing is done by the `qs` module (https://www.npmjs.com/package/qs). As far as I know, they collapse holes in arrays in purpose, but I don't really know. I would suggest asking / filing an issue over there. If they make a change, we can of course pull it into this module as an update.

You can see the behavior directly from the `qs` module:
```
$ node -pe 'require("qs").parse("option[1]=1&text[0]=&text[1]=&text[2]=")'
{ option: [ '1' ], text: [ '', '', '' ] }
```

**Comment by dougwilson** [comment]
Yea, the collapsing is definitely intentional by the `qs` module. From their documentation:

> When creating arrays with specific indices, qs will compact a sparse array to only the existing values preserving their order

**Comment by JC3** [comment]
Thanks. I'll hit them up over there. Also if anybody else find this in the future, somebody came up with a clever workaround: http://stackoverflow.com/a/41093135

**Comment by dougwilson** [comment]
Thanks for the follow up, @JC3 ! I didn't even realize it collapsed the array when specific indexes were given until today :) Feel free to send me a ping here or a new issue / PR if the `qs` module changes it's behavior and we can get it updated :D
