### ISSUE TITLE
Undefiend values removed from req.body.

### ISSUE THREAD

**Issue by mtsap** [expressjs/body-parser#216]
Does body-parser automatically remove the undefined values from the request body?
If yes how can I configure it so that it doesn't?

**Comment by dougwilson** [comment]
I'm not sure what you mean. Can you elaborate?

**Comment by mtsap** [comment]
Yes of course!
Lets say that i send the following object with a put request to the express server 
```javascrpit
    {
      name: undefined,
      age: 15
    }
```

when logging the req.body inside the route i get this:
```javascrpit
    {
          age: 15
    }
```
so i would like to know if body-parser is removing the properties with undefined values from the req.body.

Thank you for your time.

**Comment by dougwilson** [comment]
I don't think we are, as all we do is JSON.parse and return that result. Can you show the raw string that is being sent over the network to your Node.Js app? Perhaps it is your client side that is removing it.

**Comment by mtsap** [comment]
Ok. I checked it out. Turns out tha angular is the one removing it. Again, thanks for your time!

**Comment by dougwilson** [comment]
No problem!
