### ISSUE TITLE
DeprecationWarning: `DEBUG_FD`

### ISSUE THREAD

**Issue by Sjonnie2nd** [expressjs/body-parser#217]
Hi,

Just upgraded from 1.15.2 to 1.16.0.
Now node comes with: "DeprecationWarning: `DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function".
The trigger: \node_modules\body-parser\node_modules\debug\src\index.js:9:20: module.exports = require('./node.js'); 

Note: body-parser's HISTORY.md mentions:
1.16.0 / 2017-01-17
  deps: debug@2.6.0
    - Deprecated `DEBUG_FD` environment variable

Any idea?
Greetings, Sjonnie

**Comment by dougwilson** [comment]
One of our dependencies has behavior you can control using the DEBUG_FD environment variable. Due to changes in Node.js they have not been able to support that and have deprecated it's usage. That module will warn you about that when you have that environment variable set.

**Comment by Sjonnie2nd** [comment]
Thnx for the quick answer.
It seems my Jetbrains Webstorm IDE sets the deprecated DEBUG_FD environment variabele.
Jetbrains has planned to correct this in march 2017. 
Hope this helps others..
