### ISSUE TITLE
withCredentials not parsing correctly

### ISSUE THREAD

**Issue by Hosar** [expressjs/body-parser#219]
Sending requests with **withCredentials** option, is not parsing correctly json data. Using as follow:
```
//server
router.use(bodyParser.json()); // to support JSON-encoded bodies
router.use(bodyParser.urlencoded({ // to support URL-encoded bodies
    extended: true
}));
```

```
//client
superagent.post(someUrl)                
		        .withCredentials()
		        .send("{name:'mmmmmm'}")                
		        .then(data => {
		           //do something
		        }, err => {
		           //do something
		        });
```

If I send the data as pure JSON the **req.body** option is **{}** getting **no** data. If I send the JSON as string I'm getting like this **{ '{name:\'mmmmmm\'}': '' }**, in an incorrect format.

If I avoid **withCredentials** then I'm able to get the data correctly.
 sending like this: **.send({name:'mmmmmm'})** <-- as object not a string
 getting: **{name:'mmmmm'}** <-- correct

I have tested with _superagent_ and _axios_, and in both the problem is when I use **withCredentials** option.

Do I need to add something additional when using **withCredentials**?, because other way it works as expected.

Thanks in advance.

**Comment by dougwilson** [comment]
Hi @Hosar I'm not familiar at all with what `withCredentials()` is doing. Can you show a packet capture of the data that is being sent to the server?

**Comment by dougwilson** [comment]
Hi @Hosar I'm going to close this since I haven't heard back in a few weeks.
