### ISSUE TITLE
Errors while installing body-parser. (Node 6.9.4/Express 4.13.4/ Ubuntu 16.04)

### ISSUE THREAD

**Issue by martinmurciego** [expressjs/body-parser#222]
/home/martin/.node-gyp/6.9.4/include/node/openssl/rsa.h:181:18: error: expected identifier before numeric constant
 # define RSA_F4  0x10001L
                  ^
../deps/libmariadbclient/extra/yassl/include/openssl/rsa.h:25:8: note: in expansion of macro ‘RSA_F4’
 enum { RSA_F4 = 1 };
        ^
/home/martin/.node-gyp/6.9.4/include/node/openssl/rsa.h:181:18: error: expected ‘}’ before numeric constant
 # define RSA_F4  0x10001L
                  ^
../deps/libmariadbclient/extra/yassl/include/openssl/rsa.h:25:8: note: in expansion of macro ‘RSA_F4’
 enum { RSA_F4 = 1 };
        ^
/home/martin/.node-gyp/6.9.4/include/node/openssl/rsa.h:181:18: error: expected unqualified-id before numeric constant
 # define RSA_F4  0x10001L
                  ^
../deps/libmariadbclient/extra/yassl/include/openssl/rsa.h:25:8: note: in expansion of macro ‘RSA_F4’
 enum { RSA_F4 = 1 };
        ^
In file included from ../deps/libmariadbclient/extra/yassl/include/openssl/ssl.h:35:0,
                 from ../deps/libmariadbclient/extra/yassl/include/cert_wrapper.hpp:38,
                 from ../deps/libmariadbclient/extra/yassl/include/yassl_int.hpp:31,
                 from ../deps/libmariadbclient/extra/yassl/src/ssl.cpp:35:
../deps/libmariadbclient/extra/yassl/include/openssl/rsa.h:25:19: error: expected declaration before ‘}’ token
 enum { RSA_F4 = 1 };
                   ^
deps/libmariadbclient/extra/yassl/yassl.target.mk:131: fallo en las instrucciones para el objetivo 'Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/ssl.o'
make: *** [Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/ssl.o] Error 1
make: se sale del directorio '/home/martin/Escritorio/form-generator-bookshelf/form-generator/node_modules/mariasql/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/martin/Escritorio/form-generator-bookshelf/form-generator/node_modules/mariasql
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
form-generator@0.0.0 /home/martin/Escritorio/form-generator-bookshelf/form-generator
├─┬ body-parser@1.16.0 
│ ├── debug@2.6.0 
│ ├─┬ http-errors@1.5.1 
│ │ └── setprototypeof@1.0.2 
│ ├── iconv-lite@0.4.15 
│ ├── qs@6.2.1 
│ ├── raw-body@2.2.0 
│ └─┬ type-is@1.6.14 
│   └─┬ mime-types@2.1.14 
│     └── mime-db@1.26.0 
└── UNMET PEER DEPENDENCY graphql@^0.7.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN graphql-bookshelf@0.0.8 requires a peer of graphql@^0.7.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mariasql@0.1.24 (node_modules/mariasql):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mariasql@0.1.24 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by dougwilson** [comment]
The errors in your paste are from your dependency libmariadbclient, not this module.

**Comment by dougwilson** [comment]
That dependency is from the npm module `mariasql` in your graph, which is failing to compile some C code.

**Comment by martinmurciego** [comment]
I investigated it, I thought that this was what caused my real problem expressed later:
https://github.com/expressjs/body-parser/issues/223
