### ISSUE TITLE
 I also can not retrieve the parameters from req.body

### ISSUE THREAD

**Issue by martinmurciego** [expressjs/body-parser#223]
I do not know what to do. I have the same problem that many people had when posting with postman to an app in express and retrieving a req.body = undefined or []. But although I read and try to do what the forums say; I can not retrieve the fields from the req.body.

Although within app.js I have:

`var bodyParser = require ('body-parser');`
`// ...`

`app.use (bodyParser.json ());`

`app.use (bodyParser.urlencoded ({extended: true}));`

In users.js:

`router.post('/test', function (req, res) {`
`      console.log("\nExecute method execution for path: /test \n");`
`      If (typeof req.body === "undefined") {`
`          var error = {error: "empty req.body !!!" }`
`          res.status (400) .json(error);`
`          console.log ("\ nERROR:" + JSON.stringify (error));`
`      }`
`      else {`
`        console.log ({body: req.body});`
`        console.log (req.body);`
`      };`
`});`

Posting with Postman, exporting for simplicity:

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: 1c6f19b3-32c9-9f8b-498f-a7d8a5e90f54" -d '' "http://localhost:3000/usuarios/prueba?nombre=martin&apellido=murciego"`
`
Output:

`Execution of method post () for route: / test

`{body: {}}
{}
POST / users / test? Name = martin & last name = murciego - - ms - -
`

I do not know if it is a problem of asynchrony in the flow of execution and / or lack of timing.
I do not have much time with NodeJS / Express Js but I look for something as elemental as an api post to work for me.

body-parser 1.16.0
Ubuntu 16.04
NodeJS 6.9.4
Express 4.1.13

**Comment by dougwilson** [comment]
Hi @martinmurciego it looks like the issue is you're just not sending a body, which is why it's empty in Express.

Your gave the above cURL command:
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: 1c6f19b3-32c9-9f8b-498f-a7d8a5e90f54" -d '' "http://localhost:3000/usuarios/prueba?nombre=martin&apellido=murciego"
```

The `-d` argument specifies the body to send and that argument is set to `''`, an empty string. You need to send some kind of body to get anything from within your Express application.

**Comment by blakeembrey** [comment]
I don't see any payload in that CURL request, only query parameters. Is that what you're trying to use?

**Comment by martinmurciego** [comment]
Thanks for your help, you're right I needed to fill that argument - and know how to use the postman better.
Y muchas gracias en spanish!!!

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Postman-Token: 815694ff-5734-7fc9-bf8d-56fa386ec6c0" -d '"nombre"="martin"&"apellido"="murciego"' "http://localhost:3000/usuarios/prueba?%22nombre%22=%22martin%22&%22apellido%22=%22murciego%22"`
