### ISSUE TITLE
Error parsing  nested form data when key is a number

### ISSUE THREAD

**Issue by code-smith** [expressjs/body-parser#226]
<img width="607" alt="screen shot 2017-02-11 at 7 10 40 am" src="https://cloud.githubusercontent.com/assets/9841589/22850020/535a07b2-f029-11e6-8a13-f84fdfb0d389.png">
 
The nested formdata as show in the image gets parsed as 
```
{ action: 'edit',
 data: [ { exportPx: '180000', minItemMargin: '10' } ]
 }
```
where as it should have been parse like this.
```
{ action: 'edit',
 data: {
   52:{ exportPx: '180000', minItemMargin: '10' } 
}
}
```

I used the body parser this way: app.use(bodyParser.urlencoded({ extended : true }));
if i append some string to it from server side,  ex: ("id_52")  and use it in form submission then it works fine.
Here 52 represents primary key, and because it is a number the whole thing is getting converted in to an array and not an object as needed.

Is this the right behaviour or is this a bug? would appreciates some help.

**Comment by dougwilson** [comment]
This is how the underlying module, `qs`, functions: it assumes that numeric keys are array indicies and then collapses them to prevent memory exhaustion DoS attacks.

**Comment by dougwilson** [comment]
You can find more about this behavior at https://www.npmjs.com/package/qs#parsing-arrays

**Comment by dougwilson** [comment]
You can find more about this behavior at https://www.npmjs.com/package/qs#parsing-arrays

> Note that the only difference between an index in an array and a key in an object is that the value between the brackets must be a number to create an array. When creating arrays with specific indices, qs will compact a sparse array to only the existing values preserving their order:

**Comment by code-smith** [comment]
Thanks for replying. So  appending some string to the key is the best solution?

**Comment by dougwilson** [comment]
Yes, that, or simply submitting a JSON body if possible is the best way. You can also bring up the issue at the `qs` library, as we'll pull in any changes they make here :)

**Comment by code-smith** [comment]
thanks will do so. pretty trick things this was. thanks again
