### ISSUE TITLE
Z_BUF_ERROR when sending content-encoding gzip

### ISSUE THREAD

**Issue by GreaterThanOrEqual** [expressjs/body-parser#227]
In node v6 the zlib library was changed to be more strict as described here: https://github.com/nodejs/node/issues/8701.

Can we change zlib.createGunzip() to zlib.createGunzip({ finishFlush: zlib.Z_SYNC_FLUSH }) to restore the old behaviour?

**Comment by dougwilson** [comment]
Sure, can do! Would you be interested in putting a PR together for this? Would (1) just hard-code the option in since it seems from reading that thread that's the best thing to just do in the general case and (2) add a test that does not pass without the change.

**Comment by GreaterThanOrEqual** [comment]
It turns out that I was getting this error because of misconfiguration of my parsers. The zlib.createGunzip() works correctly now even for node v6.
