### ISSUE TITLE
How to get the original body

### ISSUE THREAD

**Issue by askucher** [expressjs/body-parser#231]
How to get the original body when `body-parser` finds a mistake in incoming post data and results something like 

```JSON
{ "{ field: \"value\"": "" }
```

P.S. I cannot fix the mistake in post data because another service sends me it like it is.

**Comment by dougwilson** [comment]
When there is an error parsing the body, the error object has a body property, containing the original body. You can read more about error handling and what is available on the error objects in the readme: https://github.com/expressjs/body-parser/blob/master/README.md#errors

**Comment by askucher** [comment]
@dougwilson 

error object is null form me but the body is 

```JSON
"data": {
                    "{\"merchantAccount\":\"cash_u_net2\",\"orderReference\":\"cashu-prod-1489917172266\",\"merchantSignature\":\"aa": ""
                },
```

And I know it is incomplete
