### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by askucher** [expressjs/body-parser#232]
I know that client sends me `text/plain` with JSON data

```
body-parser version is "1.17.1"
```
use as 
```Javascript
app.use(require("body-parser").json())
```

obtain
```JSON
"data": {
                    "{\"merchantAccount\":\"cash_u_net2\",\"orderReference\":\"cashu-prod-1489917172266\",\"merchantSignature\":\"aa": ""
                },
```
And I know it is incomplete but what is wrong?

**Comment by dougwilson** [comment]
Hi @askucher I would love to help, but there is not enough information here for me to understand what you're asking / what is happening in your app. If you're not sure where to start on what to send, answering there would be a good start:

1. The version of Node.js yo are using.
2. A complete Node.js app that reproduces the issue. If you're using any other module besides this one, please note the version(s).
3. Complete instructions for how to make the request to your app that will result in the issue you're describing above.

Thanks!

**Comment by askucher** [comment]
@dougwilson Thank you for reply
1.
```
node -v
v4.4.5
```
2. 
This request is available only in production mode. I am asking `request` owner to provide me an example. Because now I can see only `body-parser` result only.  Then I will provide an repository with steps to run and reproduce.

**Comment by asikk** [comment]
Hi. Y can generate mock request
curl -d '{\"merchantAccount":"cash_u_net2","orderReference":"cashu-pod-1489917172266","merchantSignature":"aa": ""} http://you-site.local

**Comment by dougwilson** [comment]
Thanks, @asikk . @askucher I'm still not understanding the issue you're reporting. Can you perhaps provide the following to go along with that request above?

1. A complete Node.js app that reproduces the issue. If you're using any other module besides this one, please note the version(s).
2. Complete details for what you are seeing and also exactly what you are expecting to see.

Thanks!

**Comment by askucher** [comment]
@dougwilson, I do not understand the suggestion @asikk as well. 

@asikk do you send it in format { "..json...": "" } ?

**Comment by asikk** [comment]
@askucher, yes we send correct json as plain text

**Comment by askucher** [comment]
@asikk at least I expect cardToken there. Can be a problem that body-parser cuts the text?

**Comment by asikk** [comment]
This is correct request:
{"merchantAccount":"cash_u_net2","orderReference":"cashu-prod-1489917172266","merchantSignature":"hidded","amount":6,"currency":"UAH","authCode":"133456,"email":"hided","phone":"hided","createdDate":1489917164,"processingDate":1489917268,"cardPan":"51*******37","cardType":"MasterCard","issuerBankCountry":"Ukraine","issuerBankName":"COMMERCIAL BANK PRIVATBANK","recToken":"58666-77777-hided","transactionStatus":"Approved","reason":"Ok","reasonCode":1100,"fee":0.1,"paymentSystem":"card","clientName":"hided"}
I cut the private data

**Comment by askucher** [comment]
Thank you @asikk I will create a test project for this data

**Comment by asikk** [comment]
@askucher, np. If y have qustion, i can help)

**Comment by askucher** [comment]
@asikk I found the issue in the document 

```JSON
"authCode": "133456,"
```
MIssing `"` after  133456
Is it real issue or typo?

**Comment by askucher** [comment]
@dougwilson 

node, express, body-parser - latest release

Server logic
```Javascript
var http = require('http');


var express = require('express');
var bodyParser = require("body-parser");



var router = express();
router.use(bodyParser.json());
var server = http.createServer(router);

router.post("/payment-service/:transaction", function(req, res) {
  
  console.log(req.body, req._body);
  
})


server.listen(process.env.PORT || 3000, process.env.IP || "0.0.0.0", function(){
  var addr = server.address();
  console.log("Chat server listening at", addr.address + ":" + addr.port);
});

```
Server start
```Bash
node server
```

In another terminal 
```Bash
curl -d "{\"merchantAccount\":\"cash_u_net2\",\"orderReference\":\"cashu-prod-1489917172266\",\"merchantSignature\":\"hidded\",\"amount\":6,\"currency\":\"UAH\",\"authCode\":\"133456,\"email\":\"hided\",\"phone\":\"hided\",\"createdDate\":1489917164,\"processingDate\":1489917268,\"cardPan\":\"51*******37\",\"cardType\":\"MasterCard\",\"issuerBankCountry\":\"Ukraine\",\"issuerBankName\":\"COMMERCIAL BANK PRIVATBANK\",\"recToken\":\"58666-77777-hided\",\"transactionStatus\":\"Approved\",\"reason\":\"Ok\",\"reasonCode\":1100,\"fee\":0.1,\"paymentSystem\":\"card\",\"clientName\":\"hided\"}" http://localhost:3000/payment-service/cashu-prod-1489917172266
```

Result

```JSON
//Actual
req.body // ==> {}
//Expected
"{\"merchantAccount\":\"cash_u_net2\",\"orderReference\":\"cashu-prod-1489917172266\",\"merchantSignature\":\"hidded\",\"amount\":6,\"currency\":\"UAH\",\"authCode\":\"133456,\"email\":\"hided\",\"phone\":\"hided\",\"createdDate\":1489917164,\"processingDate\":1489917268,\"cardPan\":\"51*******37\",\"cardType\":\"MasterCard\",\"issuerBankCountry\":\"Ukraine\",\"issuerBankName\":\"COMMERCIAL BANK PRIVATBANK\",\"recToken\":\"58666-77777-hided\",\"transactionStatus\":\"Approved\",\"reason\":\"Ok\",\"reasonCode\":1100,\"fee\":0.1,\"paymentSystem\":\"card\",\"clientName\":\"hided\"}"
```

**Comment by dougwilson** [comment]
Hi @askucher I think I understand what you're trying to do now, which is you are expecting that cURL command to give you a string in `req.body` with the contents.

So the first thing you need to do is you have to use the `text` parser to get a string of the body, not the `json` parser. The next thing you need to do is configure the `text` parser to look for requests with the `Content-Type` of `application/x-www-urlencoded`, since that is what your cURL command is sending. To put these to changes together you get the following:
```js
var http = require('http');


var express = require('express');
var bodyParser = require("body-parser");



var router = express();
router.use(bodyParser.text({ type: 'application/x-www-urlencoded' }));
var server = http.createServer(router);

router.post("/payment-service/:transaction", function(req, res) {
  
  console.log(req.body);
  
})


server.listen(process.env.PORT || 3000, process.env.IP || "0.0.0.0", function(){
  var addr = server.address();
  console.log("Chat server listening at", addr.address + ":" + addr.port);
});
```

And now when I run your command
```
curl -d "{\"merchantAccount\":\"cash_u_net2\",\"orderReference\":\"cashu-prod-1489917172266\",\"merchantSignature\":\"hidded\",\"amount\":6,\"currency\":\"UAH\",\"authCode\":\"133456,\"email\":\"hided\",\"phone\":\"hided\",\"createdDate\":1489917164,\"processingDate\":1489917268,\"cardPan\":\"51*******37\",\"cardType\":\"MasterCard\",\"issuerBankCountry\":\"Ukraine\",\"issuerBankName\":\"COMMERCIAL BANK PRIVATBANK\",\"recToken\":\"58666-77777-hided\",\"transactionStatus\":\"Approved\",\"reason\":\"Ok\",\"reasonCode\":1100,\"fee\":0.1,\"paymentSystem\":\"card\",\"clientName\":\"hided\"}" http://localhost:3000/payment-service/cashu-prod-1489917172266
```

The Node.js app logs the following to the console:
```
{"merchantAccount":"cash_u_net2","orderReference":"cashu-prod-1489917172266","merchantSignature":"hidded","amount":6,"currency":"UAH","authCode":"133456,"email":"hided","phone":"hided","createdDate":1489917164,"processingDate":1489917268,"cardPan":"51*******37","cardType":"MasterCard","issuerBankCountry":"Ukraine","issuerBankName":"COMMERCIAL BANK PRIVATBANK","recToken":"58666-77777-hided","transactionStatus":"Approved","reason":"Ok","reasonCode":1100,"fee":0.1,"paymentSystem":"card","clientName":"hided"}
```

**Comment by askucher** [comment]
Thank you @dougwilson.  It works!
