### ISSUE TITLE
Operation not permitted after try install body-parser

### ISSUE THREAD

**Issue by Silver360** [expressjs/body-parser#234]
When I tried install body-parser the installation is stoped with error Error: EPERM: operation not permitted, rename. After this i haven't acces to node_modules i can't delete directory "iconv-lite-bc10699f" i can't install another dependencies. I think this can be something with my ESET Smart Security but i haven't idea what can be reason of this.

**Comment by dougwilson** [comment]
Hi @Silver360 the error should provide more details, as well as the URL of where to report issues to are here. The installation process isn't something I really understand to help with, but there are great folks at the help address shown in your error message :) !
