### ISSUE TITLE
SyntaxError on bad input (JSON)

### ISSUE THREAD

**Issue by jessereitsma** [expressjs/body-parser#238]
Hi there,

I'm creating an API, and I use express.js with `bodyParser.json()`.
When I send a request with an invalid JSON input, for example the following:
```json
{
  "test": trueee
}
```

Then I got the following error:
```
SyntaxError: Unexpected token e in JSON at position 16
    at JSON.parse (<anonymous>)
```
in `node_modules/body-parser/lib/types/json.js:88:17)`

Is there any way to prevent this error? Log it, and handle it myself.
I really don't want to send this error to the client.

Thanks

**Comment by jessereitsma** [comment]
I now got the following:

```
app.use(bodyParser.json(bodyLimit));
app.use((error, request, response, next) => {
  if (error !== null) {
    return response.json({ 'invalid': 'json' });
  }
  return next();
});
```

Which seems to work fine for me.
Is this a good way to check for invalid JSON input with bodyParser?

**Comment by dougwilson** [comment]
Hi @jessereitsma so if what you don't want going to the user is a stack trace, you should be setting production mode in Express (`app.set('env', 'production')`). If you really wanted to create your own custom message, you probably need to handle every error we list out in https://github.com/expressjs/body-parser#errors . There isn't currently an easy way to detect specifically that there was a JSON error (see discussion in #122), but you can use the following check: `err instanceof SyntaxError && err.status === 400 && 'body' in err`.
