### ISSUE TITLE
Using body-parser in express got empty request body

### ISSUE THREAD

**Issue by maicss** [expressjs/body-parser#246]
## server code:
```
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.all('*', (req, res) => {

    console.log(req.body);
    res.send(req.body)
});


app.listen(5100);
console.log('http://localhost:5100/');
```
## curl test:

`curl -H 'Host: localhost:5100' -X POST 'http://localhost:5100/?aa=11&bb=12'`

both console and curl get are `{}`

I know this a duplicate question, but I cannot solve it, after the method you gays give before.

I tired `app.use(bodyParser.raw({type: "*/*"}))`, nothing change.

**Comment by maicss** [comment]
```
node: 8.0.0
express: 4.15.3
body-parser: 1.17.2
OS: mac sierra 10.12.5 
```

**Comment by dougwilson** [comment]
Your curl command is not sending any body, thus why req.body is {}.

**Comment by maicss** [comment]
thanks, curl command should be `curl -X POST --data "aa=11&bb=12" localhost:5100`

**Comment by dougwilson** [comment]
Oh, sorry, I didn't think you were expecting the query string in your first example to appear in `req.body`. Yes, that would be the place to put the data to appear in the body :)
