### ISSUE TITLE
Request aborted using bodyParser.json()

### ISSUE THREAD

**Issue by stephen-last** [expressjs/body-parser#249]
I have an ExpressJS API which accepts JSON. The calling application (a NodeJS CLI app) is POSTing JSON which is used to create products in a database. It’s trying to create around 8,000 products, in batches of 50, so 160 API calls, made using `Promise.mapSeries()` ([bluebird](http://bluebirdjs.com)) and [axios](https://github.com/mzabriskie/axios). 

At the moment both the calling application and the API are running on my dev machine, so requests don’t go over any external networks. My dev machine (Windows 7) is not stressed in any way, CPU and memory are fine.

The API is using `bodyParser.json()`, and I’m getting an Express error like:

> Error: request aborted
> at IncomingMessage.onAborted (C:\...\node_modules\raw-body\index.js:269:10)

The `received` count is always less than the `expected` count when it fails. Example: `expected: 52155` and `received: 50695`.

The `request aborted` is happening when the axios timeout occurs, so I know why `body-parser` is giving this error (the request is aborted by the client). However, the problem seems to be that `body-parser` is hanging on to the request, and causing the timeout (I've tried many different timeouts, up to 60 seconds, the average response time for a request that works is around 100 ms (shown by [morgan](https://github.com/expressjs/morgan) logs)).

This error is happening on seemingly random calls, so I’m finding it difficult to track down (the JSON data is different for each batch call). It happens on batch 7, then batch 39, then 103 etc. The incoming JSON validates on https://jsonformatter.curiousconcept.com/. 

I've added some `console.log`'s to middlewares which show that the request stops at `body-parser`.

```js
router.use((req, res, next) => {
  console.log('marker 1', req.header('X-CL-Call'), req.header('Content-Type'), req.header('Content-Length'))
  next()
})
router.use(bodyParser.json({
  type: 'application/json',
  limit: '50mb',
  strict: false,
  verify: (req, res, buf, encoding) => {
    req.rawBody = buf.toString(encoding || 'utf8')
    console.log('marker 2', req.header('X-CL-Call'), req.rawBody.length)
  }
}))
router.use((req, res, next) => {
  console.log('marker 3', req.header('X-CL-Call'))
  next()
})
// api code here...
router.use((err, req, res, next) => {
  console.log('err.status: ' + err.status)
  console.log('err.expected: ' + err.expected)
  console.log('err.received: ' + err.received)
  console.log('err.stack: ' + err.stack)
  req.destroy()
})
```

Example output:

> ...
> marker 1 upsert-products-7/160 application/json;charset=utf-8 47630
> marker 2 upsert-products-7/160 47630
> marker 3 upsert-products-7/160
> marker 1 upsert-products-8/160 application/json;charset=utf-8 52155
> err.status: 400
> err.expected: 52155
> err.received: 50695
> err.stack: Error: request aborted
>    at IncomingMessage.onAborted (C:\[my app]\node_modules\raw-body\index.js:269:10)

So for successful requests I see markers 1, 2 and 3. When it errors I only see marker 1, so the `verify()` function isn't called.

Can anyone help..?

**Comment by stephen-last** [comment]
I've tried changing the batch sizes to change the size of requests:

Batch size: 10

> ...
> marker 1 upsert-products-364/797 application/json;charset=utf-8 cl: 13185
> marker 2 upsert-products-364/797 13185
> marker 3 upsert-products-364/797
> marker 1 upsert-products-365/797 application/json;charset=utf-8 cl: 17463
> err.status: 400
> err.expected: 17463
> err.received: 11610
> err.stack: Error: request aborted

Batch size: 1000

> ...
> marker 1 upsert-products-2/8 application/json;charset=utf-8 cl: 1119940
> marker 2 upsert-products-2/8 1119940
> marker 3 upsert-products-2/8
> marker 1 upsert-products-3/8 application/json;charset=utf-8 cl: 1135726
> err.status: 400
> err.expected: 1135726
> err.received: 1129871
> err.stack: Error: request aborted

The `received` is never `0`, it always seems to be quite close to `expected`, as you can see from the larger `Content-Length` example.

It's like part of the body data is being stripped out, so `body-parser` looks at the `Content-Length` for `expected`, but finds less data when it checks the `received`.

Is there any way to see the data that `received` refers to..? (when the `verify()` func doesn't get called)

**Comment by dougwilson** [comment]
Very odd. Is it possible to get a packet capture of the traffic when this happens? As for seeing what bytes were received, it is not exposed currently, and especially since it's written to an internal decoder of Node.js, we don't want to keep multiple copies of the data to balloon memory. The easiest way to figure this out will be with a packet capture, but otherwise, you can edit the `raw-body` module in your `node_modules` directory, adding a capture in the `onData` function prior to the decoder write (or you can even try just using the `buffer` variable, if you're not concerned with the differences in sizes / contents that can occur when decoding utf-8).

**Comment by stephen-last** [comment]
@dougwilson Thanks for your reply.

I've added a couple of `console.log()`'s to into `raw-body`'s `onData()` func like you suggested. So the logs print for each `chuck`.

These follow this format: `[batch]/[total batches]  [expected]  [received]  [missing/differnce]`

1. `56/160  50603  44749  5854`
2. `55/160 60527 54673 5854`
3. `2/160 40989 39529 1460`
4. `28/160 52775 46921 5854`

Chuck lengths...

**Chuck 1.** `56/160` chuck lengths
  - chuck 1: `10220`
  - chuck 2: `34684`
  - chuck 3: `44749`

**Chuck 2.** `55/160` chuck lengths
  - chuck 1: `10220`
  - chuck 2: `34960`
  - chuck 3: `54673`

**Chuck 3.** `2/160` chuck lengths
  - chuck 1: `32135`
  - chuck 2: `39529`

**Chuck 4.** `28/160` chuck lengths
  - chuck 1: `10220`
  - chuck 2: `34684`
  - chuck 3: `46921`

I have the chuck strings (by using `chunk.toString('utf8')`) in `onData()`. When I concat the strings and compare them to the JSON string POSTed to the server, I can see that there is a section of the first chuck missing, and the missing `length` matches the `[missing/differnce]` value.

Now, `1460 * 4` is `5840`, which is very close to the `5854` missing for test 1, 2 and 4.

Someone here at work has done some research and found that `1460` is the size of a "TCP Segment".

So... Does that mean I'm losing TCP Segments from the steams somehow..?

**Comment by dougwilson** [comment]
Hi @stephen-last I'm not sure, but it looks like your issue is likely outside of these modules and directly with Node.js core itself, as Node.js core code is what interacts with the underlying OS I/O layer and then provides to user-land code (us) the data chunks it received. As far as I know, over TCP it is impossible to get any data after a missing packet, since the low-level network layers (OS, NIC, etc.) guarantee sequential packet ordering.

If you can get a network packet capture on the host machine that is running the Node.js binary with body-parser that would help narrow down if the missing data is actually present in the capture. If the data is not missing from that capture, there is some issue in Node.js / the code you're trying to debug. If the data is missing from that capture, though, perhaps the client itself has an issue. You can then packet capture on the client machine and see if the data is missing from that capture or not to help narrow it down.

**Comment by stephen-last** [comment]
@dougwilson Again, thanks for your time on this, it's much appreciated.

I may have found a solution.

I've added [http Agent](https://nodejs.org/api/http.html#http_new_agent_options) to the API requests via [axios](https://github.com/mzabriskie/axios#request-config). 

This allows specifing the following options:

```js
const agentOptions = {
  keepAlive: true,      // Keep sockets around even when there are no outstanding requests, so they can be used for future requests without having to reestablish a TCP connection. Defaults to false
  keepAliveMsecs: 1000, // When using the keepAlive option, specifies the initial delay for TCP Keep-Alive packets. Ignored when the keepAlive option is false or undefined. Defaults to 1000.
  maxSockets: Infinity, // Maximum number of sockets to allow per host. Defaults to Infinity.
  maxFreeSockets: 256   // Maximum number of sockets to leave open in a free state. Only relevant if keepAlive is set to true. Defaults to 256.
}
...
httpAgent: new http.Agent(agentOptions),
httpsAgent: new https.Agent(agentOptions)
...
```

axios docs say:

> `httpAgent` and `httpsAgent` define a custom agent to be used when performing http and https requests, respectively, in node.js. This allows options to be added like `keepAlive` that are not enabled by default.

Before this, each response contained a connection header like: `connection: 'close'`, and now this connection header is: `connection: 'keep-alive'`. It seems that keep alive is not enabled by default, and it's not something I've had to deal with before.

I'm now making hundreds of API calls, serially, in different batch sizes with different payload lengths, without any errors.

**Comment by dougwilson** [comment]
Hi @stephen-last sorry I didn't reply to your previous comment, as it seemed like you were saying it was resolved. Is this the case?

**Comment by stephen-last** [comment]
Hi @dougwilson, yes it is, sorry about that, I left the issue open. 

Thanks again for your help, it was much appreciated.
