### ISSUE TITLE
Handle gzip encoded requests

### ISSUE THREAD

**Issue by jhihn** [expressjs/body-parser#254]
I have a large >1GB text file that is being uploaded as multi-part form data. It seems too hard to support the case of gzip compressing the file part of the form by itself on the fly, So I've created a request with form-data and compress the whole thing:

    form.pipe(zlib.Gzip()).pipe(request);

Which results in the following headers* (*I have to manually add in the content-encoding header)

    POST / HTTP/1.1
    content-type: multipart/form-data; boundary=--------------------------049179864037623009067437
    Content-Encoding: gzip
    Host: localhost:1337
    Connection: close
    Transfer-Encoding: chunked
    
    [binary chunked content follows]

It would be nice is body-parser saw the CE header and unzipped it before continuing on the callback chain. Currently, I only get the outer request.

**Comment by dougwilson** [comment]
This module has no support for multipart forms, either compressed on uncompressed.

**Comment by dougwilson** [comment]
If you use a type this module supports, then you'll see that we already support content-encoding: gzip by default :) You can even use the `raw` parser if you want to end up with `req.body` as a `Buffer` object containing the un-gziped data that you can do whatever further processing you would like on it :)

**Comment by jhihn** [comment]
If that is the case, content-encoding: gzip is supported, why doesn't it get ungzipped?

It isn't the multipart that is messing it up, AFAICT, I don't need body parser to handle the multi-part-ness, just the gzip-ness.

**Comment by dougwilson** [comment]
The way the middleware works is the first thing it does is filter on the `content-type` coming in. This means that if you don't have a middleware from this module setup to handle the `multipart/form-data` content-type, this middleware will just ignore the request. You can setup a parser like the `raw` one to recognize the `multipart/form-data` as I suggest, of course. Then you'll end up with a `Buffer` that is ungziped in the `req.body` property you can then pass though a multipart parser somehow.

**Comment by jhihn** [comment]
Ah, thank you for that. So it seems that this would go to multer, based on content-type. I'll follow up with them. I'm not that sure of node internals so when you say `somehow` by eyes glaze over.

**Comment by dougwilson** [comment]
Yea, I know the "somehow" is kind of a cop-out, but I've never done it before, so not sure how one would do that, but wanted to leave open that it may be possible to do, just not sure.

**Comment by jhihn** [comment]
This may be off-topic but it seems like to me the processing order should be transfer-encoding first, content-encoding second, then content-type driven 

If you have a transfer-encoded request that absolutely must come first, then if whatever content comes next is either content-encoded or not, then if there are subparts of the main request ("multi-part" encoding) each part is then decoded separately, with optional content-encoding on each part. 

Having content-type be at the top means that everything below it has to implement their own support for transfer encoding and content encoding.

**Comment by dougwilson** [comment]
We could do that, but I'm not sure if it's possible for one module to do the ungzip transparently to another module. If you have any ideas how to implement, I'd love to hear it and would be glad to implement! This module doesn't do that right now because I don't think it's possible, so unless someone can provide a pull request to implement it, not sure how I would approach doing that...

**Comment by dougwilson** [comment]
Also as an side, I would actually log to not implement the content-encoding in this module at all, just like it sounds like you're saying the case is of multer. If there was a middleware that somehow implemented this transparent ungziping, then we could remove the content-encoding from this module and direct the users to use that middleware before this middleware, just as I would assume multer would be doing :) Then that means that all body parsing middleware on npm can automatically, transparently support the content-encoding 🎆

**Comment by jhihn** [comment]
Yes, I think that would be the "proper" approach.

I think it's do-able, but kinda moot at this point. Previously, I had implemented a streaming/async HTTP server in C++ (handling multi-part SOAP XOM/XTOP requests, including files), and the proper pipelining was always:
  rawData.pipe(transferEncoding()).pipe(contentEncoding()).pipe( contentTypeHandler()).pipe(router() )

The only drawback was if you wanted to do some fancy grab-the-gzipped-content trick and store that because that's what you want anyway, but that's rare enough that people doing that can be expected to go out of their way. (Cheap work-around is to just upload the file compressed without the header and implement the skip-unzip in the application handler based on filename)

It would be do-able because middlewares later down the line would have their content-encoding support just go unused. Uncompress and renove the content-encoding header, and they'd be oblivious to the fact it was ever encoded. 

As an aside I could set up nginx or apache to forward the unzipped the request, and pass it to node, but that isn't a total-node solution and introduces another component into the stack.

**Comment by dougwilson** [comment]
Right, I'm sure it's generically doable, but how to do that in Node.js itself is the question. There is no API that is part of the Node.js core HTTP request object that provides a way to add transformations into the stream, so I'm not sure how one would go about implementing that is all, at least not without getting the Node.js core project to add some sort of API first, then userland like this module can then use it.
