### ISSUE TITLE
Uncaught exception when uncompressed JSON body size exceeds limit

### ISSUE THREAD

**Issue by debevv** [expressjs/body-parser#255]
I have an express.js app with body-parser configured like this:
````
const BODY_PARSER_OPTIONS = {
    limit: 100000,
    strict: true,
    type: "application/json"
}
````
I tried to send this request:
````
POST /bomb HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: gzip
[contents of bomb.gz]
````
bomb.gz it's file of 49KB, that when uncompressed becomes 50MB (it's all zeroes)
While uncompressing, the operation stops with this error caught by the express.js error handler
````
ERROR - Error: request entity too large
    at Gunzip.onData (/home/valerio/maconchivado/mccv-node/node_modules/raw-body/index.js:286:12)
    at emitOne (events.js:96:13)
    at Gunzip.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Gunzip.Readable.push (_stream_readable.js:134:10)
    at Gunzip.Transform.push (_stream_transform.js:128:32)
    at Zlib.callback (zlib.js:598:14)
````
This is correct, because the library is enforcing the limit of 100KB

But then another exception is raised, and unless i catch it with `process.on("uncaughtException")`, it crashes my application:
````
ERROR - Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
`````
There are no other ways to catch it from my code, and catching it with the uncaught exception handler of course is not an option

Using
node 6.11.1
express 4.15.3
body-parser 1.17.2

**Comment by dougwilson** [comment]
Yea, that definitely seems to be an issue. I haven't seen it before and a quick try on the versions you provided did not reproduce for me. Would you be willing to make a pull request with a fix? Alternatively if you're not sure how to fix I can take a look, but need the following:

1. Complete code that has the issue.
2. Complete instructions, including the exact request that causes the issue.

I'd be happy to debug through it and get a fix out quickly, but so far I haven't figured out how to reproduce with the information provided.

**Comment by debevv** [comment]
@dougwilson I think i found the problem. In read.js the Inflate and Gunzip streams (in contentstream()) don't have an "error" event listener. Adding it to both streams solved the problem, i will make a PR tomorrow.
I just wanted to know how you would handle this error, given the fact that by the time this is raised, the user has already sent the response or closed the socket (like i do).
Maybe a debug()? Or no logging at all?

**Comment by dougwilson** [comment]
I'm not sure. If you can provide  the following, I can take a look and pole at the issue to see what exact state everything is in at that moment to see what would be appropriate:

1. Complete code that has the issue.
2. Complete instructions, including the exact request that causes the issue.

Thanks!

**Comment by dougwilson** [comment]
P.S. error listeners are added to those streams, it is just added in the raw-body module. You can see them getting added using a debugger.

**Comment by debevv** [comment]
Yes, but after the "request entity too large" error, the "close" listener is called, which is a function that removes all other listeners (the name is cleanup()). So the second exception won't be caught by anyone

**Comment by dougwilson** [comment]
That's right that the listener is removed, but then you can see in the debugger that the on-finished module (through ee-first) adds a new error listener to finish off the stream.

What does the error emit in relation to this second error listener in your issue? Before it gets attacked (it is reattached sync, so it shouldn't), does that second one just never reattach or is the second one attaching, then getting removed and then the error emits?

**Comment by dougwilson** [comment]
Actually, I think that on-finished is not attaching the error to the non-http streams. That may be the root problem (where the symptom can be called by a noop error event as you proposed). I would love to dig into this, but I'm not able to reproduce so don't really have the ability to see the exact behavior.

At the very least if you cannot provide me any code or steps, can you at least send me that "bomb.gz" file?

**Comment by debevv** [comment]
I'm sending you some test code and the exact cURL reproduction of the request

**Comment by debevv** [comment]
[test.zip](https://github.com/expressjs/body-parser/files/1154396/test.zip)

**Comment by dougwilson** [comment]
Awesome, @debevv thanks! For some reason I _still_ cannot reproduce your issue, using exactly what you provided. Here is my environment, perhaps you can help with what I may be doing wrong:
```
$ node -v
v6.11.1
$ npm ls --depth=0
issue-255
+-- body-parser@1.17.2
`-- express@4.15.3
```

I then run `node test.js` in that folder, which doesn't print anything. In another terminal I run `./request.sh` and get the following output:
```
$ bash request.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48872    0     0  100 48872      0   145k --:--:-- --:--:-- --:--:--  145k
```

Then looking back over at the `node test.js` terminal, I see the following:
```
$ node test
Server started on port 8080
Connection from ::1
Error: request entity too large
    at Gunzip.onData (issue-255/node_modules/raw-body/index.js:286:12)
    at emitOne (events.js:96:13)
    at Gunzip.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Gunzip.Readable.push (_stream_readable.js:134:10)
    at Gunzip.Transform.push (_stream_transform.js:128:32)
    at Zlib.callback (zlib.js:598:14)
Connection with ::1 closed
```

The other error never appears, and the `UNCAUGHT EXCEPTION` code block ever runs.

**Comment by debevv** [comment]
Ok, this is getting very strange. After i sent you the test code i couldn't reproduce the issue anymore. At this point i think is a particular combination of stream throwing errors/closing at the right time.
I will try to fiddle with the error handling code and the `limit` parameter, because the issue exists, and if it's so unpredictable it's even worse, at least for me

**Comment by dougwilson** [comment]
Hi @debevv any additional information on this issue?

**Comment by dougwilson** [comment]
Closing since I haven't heard anything back.
