### ISSUE TITLE
custom error handling or less verbose on NODE_ENV production

### ISSUE THREAD

**Issue by msfwebdude** [expressjs/body-parser#256]
Although I may be able to catch errors before they are sent out (handler after next), it would be nice to have either a custom error callback or when NODE_ENV is set, to not send details to client.

These details include file paths and that this is an node / express application (usually hidden by removing x-powered-by.

thank you

**Comment by dougwilson** [comment]
Hi! I think you may have opened this in the wrong repo. All this module does is send an error object to the Express callback; there is no logic for how the error is actually written out to the reponse in this module, nor any knowledge of what the NODE_ENV is set to.

Node.js itself is what is including the file paths in error objects. In addition the main Express.js project has also changed the default behavior for how it writes errors if you don't handle them, though that it outside the scope of this module.

I hope that helps!

**Comment by msfwebdude** [comment]
Sorry, I'm a github noob. Thank you

**Comment by dougwilson** [comment]
It's no problem, just going through all the new issues while I am between planes :) But yea, Express 5 is likely to change the default response to return only the error message and not the staxk trace when NODE_ENV is set, though it is still in the air as we will see if there is any feedback from the userbase on this, especially it's impact to DX.
