### ISSUE TITLE
How could one disable parsing via verify method without throwing an error? Error just stops the middleware chain, not passing it to actual "action" to work with unparsed body.

### ISSUE THREAD

**Issue by idchlife** [expressjs/body-parser#260]

**Comment by dougwilson** [comment]
Not possible currently.

**Comment by idchlife** [comment]
@dougwilson can PR introducing such feature be potentially merged?

**Comment by dougwilson** [comment]
Maybe; I don't understand the use case and the proposed change enough to really be able to say.

**Comment by idchlife** [comment]
I'll try to explain as I see it.
Express is used widely not only like raw framework, but as a core for many other frameworks and projects. Several of them use it underneath not leaving many possibilities to write "actions" like

```javascript
app.get("/kek", middlewaresWithBodyParser, function() {
  // something
});
```

One of the only available exposed express parts are often only at the start of those frameworks.

Like 

```
const app = express();

const framework = createFrameworkWithControllersActionsEtc(app);
```

So usage of such middlewares is not prohibited, but they are often used like generally across an application. Or added via some kind of middleware helpers for that framework, which attach express middlewares for special controllers or actions or views (like django style or something)

like

```
class Controller {
  useMiddlewareBefore: bodyParser.urlencoded()
}
```

This approach in many frameworks build upon express is nice and gives us possibility to use middlewares exactly where we need them.

But bodyParser is different. bodyParser is such library that often comes as de-facto available for all of the application routes. Json powered api server. Or urlencoded. All of the routes should have request parsed.

Sometimes in perfect world there is imperfect situations. One outside api provider sends invalid content-type to api server which uses express and bodyParser.
There are many routes which should parse urlencoded. But because of that one outside api provider which shoots to callbackUrl invalid content-type - one route should just omit  bodyParser.urlencoded() behaviour. And of course as in imperfect world - outside api provider could not in any way fix their behaviour, because well, backward compatibility. Too many companies already catches their invalid content-type (send as urlencoded, but body is raw xml which automatically and invalidly parsed by bodyParser.urlencoded())

One could say - well just catch that error and do something, you know. Error from bodyParser, just add there middleware upon it. Many frameworks which encapsulates express functionality in the core - do not provide possibility to work with actions/controllers express-way. So one cleanest possible way as I see it - to tell bodyParser to omit several routes based on some rules. Just do not parse. Leave request.body intact.

Another option, not implemented in the first place was as I believe for the sake of memory saving - leave something like request.bodyRaw. But this is like duplicating data which of course may not be even needed and will eat those bytes.

I am of course may be mistaken in my ideas, because as I see express philosophy and middlewares are created for the exact sake of using them as parts of the bigger machine and method "verify" itself is some kind of hack because well, don't need bodyParser don't add it to that route etc.

**Comment by dougwilson** [comment]
Does that provide send any other identifying request header? Add `bodyParser.text` before your `.urlencoded` one and then set a custom `type` function to detect when it is the urlencoded request from that provider?

**Comment by dougwilson** [comment]
You can even use the `type` function to only parse for a specific URL (or exclude a specific URL). Does that not work for you? I'm 100% sure there is already a solution you can use, but I don't know your exact situation in order to point you to the right solution, because imo you are looking down the wrong path right now.

**Comment by idchlife** [comment]
@dougwilson yes, this is really possible that I'm digging the wrong hole.
You mean I can pass callback function to type and return false (in bodyParser.urlencoded({ type: req => boolean })) if it should not be parsed?

I can distinguish between need to parse or not - by req.path actually.

**Comment by dougwilson** [comment]
Right, if you return `false` from the `type` function, then parsing will not even be attempted and it'll flow to the next middleware, where parsing can be attempted again. This would allow you to use a text parser before your urlencoded parser, even if the incoming request has the wrong Content-Type.

**Comment by idchlife** [comment]
@dougwilson yep, this is the solution I was looking for! Thanks! Closing issue
