### ISSUE TITLE
v1.18.1 missing from NPM

### ISSUE THREAD

**Issue by simison** [expressjs/body-parser#263]
Currently at npm v1.18.0

**Comment by dougwilson** [comment]
haha, oops, guess I forgot to publish.

**Comment by dougwilson** [comment]
I rolled back the commit and will update the deps and publish later today 👍 Thanks for catching that.

**Comment by dougwilson** [comment]
Published 1.18.1 :tada:

**Comment by simison** [comment]
Cheers! Recommend to have a look at [np](https://www.npmjs.com/package/np) ;-)

**Comment by dougwilson** [comment]
I have to wait for the Travis CI to be green, I can't tell if that will wait for that before publishing, though.
