### ISSUE TITLE
Empty req.body with json parser

### ISSUE THREAD

**Issue by robertsLando** [expressjs/body-parser#264]
After the update from version 1.0.0 to 1.18.1 req.body is empty. 

Request:
```
var data = {email: email, password: pswd};
request = $.ajax({
            type: "POST",
            url: "/login",
            data: JSON.stringify(data),
            contentType: "application/json; charset=utf-8;",
            dataType: "json"
        });
```

Server side init:

```
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
```

**Comment by dougwilson** [comment]
This module is currently version 1.18.1, very different from the version you mentioned. Is that just a typo?

**Comment by robertsLando** [comment]
@dougwilson sorry I wrote 1.0.1 by error, I mean lastest version 1.18.1. If I install the last version the body is always empty. If I downgrade to 1.0.0 everything works.

**Comment by dougwilson** [comment]
Downgrade what to 1.0.0, this module? The code you provided is working for me with your jQuery code in both 1.0.0 and 1.18.1

**Comment by dougwilson** [comment]
Sorry, I made a typo when rewriting your jQuery. The issue is your content typs is invalid.

Instead of

    application/json; charset=utf-8;

It needs to be

    application/json; charset=utf-8

**Comment by robertsLando** [comment]
I try to explain it better. I was using body-parser@1.0.0, I have upgrade it to 1.18.1 (the last version), after the upgrade I had empty body in req.body so I have downgrade body-parser back to 1.0.0 and things started working again. I still don't understand why it works with 1.0.0, was a bug in 1.0.0 version that made it work even with the ';' at the end of content type string or what else?

**Comment by dougwilson** [comment]
That's correct, it was a bug that was fixed.

**Comment by robertsLando** [comment]
Thanks @dougwilson. I have removed that ';' from all jquery requests in my project and now everyting works with lastest version 1.18.1.

**Comment by abhiroopghatak** [comment]
with version "body-parser": "1.18.3", .... sending post request from CLI 
e.g.    curl localhost:3001/adduser -H 'contentType:application/json' -d "{'a' : 'b'}" 

showing request body as empty { }
