### ISSUE TITLE
Body is always empty when has this header, Accept-Encoding: gzip, deflate, br?

### ISSUE THREAD

**Issue by gowtham-sai** [expressjs/body-parser#266]
req.body is always empty object when the header `Accept-Encoding=gzip, deflate, br` set?

```node
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');

app.use(bodyParser.json({
  limit: '50mb'
})); // support json encoded bodies

app.use(bodyParser.urlencoded({
  limit: '50mb',
  extended: true
})); // support encoded bodies

app.use(bodyParser.raw({
  limit: '50mb'
})); // raw body
```

**Comment by dougwilson** [comment]
Addinf that header on the tests doesn't change the parsing, so not sure what is going on. Can you procide all the following so I can reproduce the issue?

1. Version of Node.js
2. Version of this module.
3. Complete app I can run that demonstrates this isue.
4. Complete instructions on how to reproduce (which needs to include the complete request to make to the app).

Thanks!

**Comment by gowtham-sai** [comment]
@dougwilson sorry i'm closing this as it is not the problem with body parser. 

I'm using Postman. And postman is the culprit here. When I tried with curl. It's working fine.
