### ISSUE TITLE
Adding examples in README based on ES6

### ISSUE THREAD

**Issue by itaditya** [expressjs/body-parser#267]
Hi I noticed that all the examples are written in ES5, however it would be much better if people are also provided snippets in ES6 as it is more concise.
For your consideration take this example -
```js
app.post('/login', urlencodedParser, function (req, res) {
  if (!req.body) return res.sendStatus(400)
  res.send('welcome, ' + req.body.username)
})
```
```js
app.post('/login', urlencodedParser, (req, res) => {
  if (!req.body) return res.sendStatus(400);
  res.send(`welcome, ${req.body.username}`);
})
```

**Comment by dougwilson** [comment]
You're welcome to make a pull request, but the difference between those only look like 4 chars, so not sure how that's really any more concise.

**Comment by itaditya** [comment]
Actually I was thinking of taking this as a starting point. After that I would love to contribute by making step by step migration of the project from ES5 to ES6. I hope that would be a good thing

**Comment by dougwilson** [comment]
As long as it continues to work on Node.js 0.10

**Comment by itaditya** [comment]
:cry:
