### ISSUE TITLE
Parsers set body even when they should not parse

### ISSUE THREAD

**Issue by bricka** [expressjs/body-parser#269]
Hello! I just ran into a bug in another piece of software based on an interesting behavior in `body-parser`:
https://github.com/apigee-127/swagger-tools/issues/533

The problem here is that even if a body parser should not parse (e.g. because the content type does not match), the parser still sets `req.body = {}`. This led another tool to think that parsing had already occurred, because `req.body` was defined.

I was wondering if it is possible to not modify the request at all if parsing should not be performed. That is the behavior I would expect.

You can see an example of this behavior in the raw parser here:
https://github.com/expressjs/body-parser/blob/090a92bc9cf7ddac6630b396f5eae0e12e4d67c3/lib/types/raw.js#L62-L78

Thank you!

**Comment by dougwilson** [comment]
This is hoe 2.0 will work; you can test it out at https://github.com/expressjs/body-parser/pull/66

**Comment by dougwilson** [comment]
The current behavior is documented at the top of the readme as well:

> All middlewares will populate the req.body property with the parsed body when the Content-Type request header matches the type option, or an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.

**Comment by dougwilson** [comment]
Closing since I haven't heard anything further.
