### ISSUE TITLE
When body is urlencode,req.body is an object doesn't instanceof Object

### ISSUE THREAD

**Issue by huazhu111** [expressjs/body-parser#273]
'req.body instanceof Object' return false and Object.getPrototypeOf(req.body) return null.

I am using class-transformer which has a code to check if the arg is instanceof Object.

**Comment by dougwilson** [comment]
I'll check it out to see what is going on. Please provide the following:

1. Verson of this module.
2. Version of Node.js
3. Complete source code that reproduces the issue.
4. Complete instructions for running the code and the exact request that needs to be made to the server.

Thank you!

**Comment by huazhu111** [comment]
Module Version :  1.18.2
Node.js Version :  v8.6.0

```
const express = require('express')
const bodyParser = require('body-parser')
const app = express()
app.use(bodyParser.urlencoded({ extended: false }))
app.post('/', function (req, res) {
    console.log(req.body);
    console.log(req.body instanceof Object)
    res.send('YEAH');
})

app.listen(3000, function () {
    console.log('Listening on port 3000!')
})
```
Then I making a POST request to server with form data,the console print my data parsed to object and 'false'

**Comment by dougwilson** [comment]
Looks like this is an issue with Node.js itself. From https://nodejs.org/dist/latest-v8.x/docs/api/querystring.html#querystring_querystring_parse_str_sep_eq_options

> Note: The object returned by the querystring.parse() method does not prototypically inherit from the JavaScript Object. This means that typical Object methods such as obj.toString(), obj.hasOwnProperty(), and others are not defined and will not work.

I'm not sure we can fix this. Looks like older versions of Node.js worked as you are expecting but no longer.

Any ideas for what this module should do?

**Comment by huazhu111** [comment]
An issue with Node.js..

It's not a big problem so I think I could add a middleware to solve this problem.

Thank you very much.
