### ISSUE TITLE
Minimum body size

### ISSUE THREAD

**Issue by dcousens** [expressjs/body-parser#277]
You have `limit`,  why not `minimum`?

**Comment by dougwilson** [comment]
Hi @dcousens sorry I didn't see this issue for some reason come through my email. Yea, we don't have a minimum currently, and I guess it's just never come up as something that anyone wanted / needed before. I'm not quite sure I understand the use-case, though it wouldn't be too difficult to add. The main use case for `limit` if to protect against simple DoS type attacks where a request can allocate all available memory or a very long parse time can occur.

**Comment by dcousens** [comment]
@dougwilson indeed,  but if I have a minimum of 32-bytes,  I could reduce the non-targeted load/DoS of other spammers :+1: .

**Comment by freebeans** [comment]
Perhaps you can roll your own middleware, checking for some header, for example. You could use it to identify your application and immediately drop any connections that don't have it.

**Comment by wesleytodd** [comment]
I am not sure DoS protections via a `min` body size is a good idea.  Preventing resource starvation by parsing a huge request body is an important feature, but the reverse for DoS protection is miss-guided IMO.

It would only provide a false sense of security, where using a service like CloudFlare is a *much* better option.  I have worked on projects which were the target of large scale DDoS attacks, and something as simple as a min body size would have done nothing.

If you have another reason for this feature I might understand it, but for this one use case I don't think it is worth adding.

**Comment by dcousens** [comment]
@wesleytodd I think I simply meant that the request is malformed unless it meets the minimum;  thereby,  I don't need to waste resources on it.
100%, the idea of it preventing denial of service attacks is wrong;  but I still think it can be useful;  in some limited cases.

Is it worth adding?
Probably not;  and I'm happy to close this issue.

**Comment by dougwilson** [comment]
So this issue has generally fizzled out; I know I'm not included to add such a configuration, but that doesn't mean I'm rejecting the idea, only just re-iterating what Wes said above.
