### ISSUE TITLE
sending stringified string make the parser fail

### ISSUE THREAD

**Issue by phra** [expressjs/body-parser#279]
hi, if the payload of a POST request is created in this fashion it will make the parser crash:

```typescript
{
  body: JSON.stringify('BODY')
}
```

a stringified string won't be recognized as valid json due to this line: https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L81
`"` should be a valid first char. i will send a PR to fix that after verifying locally that is working.

**Comment by dougwilson** [comment]
This is already supported: set the option strict: false.
