### ISSUE TITLE
Expose empty object (representing no request body) as a constant

### ISSUE THREAD

**Issue by gajus** [expressjs/body-parser#288]
I should be able to do something along the lines of ...

```js
import bodyParser, {emptyBody} from 'body-parser';

app.use(bodyParser.raw({
  type: 'application/json'
}));

app.use((req, res) => {
  if (req.body === emptyBody) {
    // ...
  }
});

```

Otherwise, unless I am missing something, there is currently no safe way to check if the request body is empty.

**Comment by dougwilson** [comment]
So right now, `req.body` is mutable. If every `req.body` is the same `{}` instance, that would certainly break a lot of apps out there, right?

**Comment by gajus** [comment]
If someone is mutating the empty object that represents no request body, then yes.

I cannot imagine a valid scenario for something like this.

To make this backwards compatible, the said object would need to be exposed as part of the request object, e.g. 

https://github.com/expressjs/body-parser/blob/master/lib/types/raw.js#L62

```js
req.NO_PAYLOAD = {};
req.body = req.body || req.NO_PAYLOAD;

```

**Comment by dougwilson** [comment]
Yea, we could do that. Right now the 2.0 branch is going to just make `req.body = undefined` when there is no body. Is that possibly a solution here?

**Comment by gajus** [comment]
`req.body = undefined` (as a breaking change) sounds reasonable.

**Comment by dougwilson** [comment]
Right, it is a breaking change, yes. 2.0 can come out at any point. The only reason it hasn't come is that there was the strong desire to refactor the internals to support the generic parser case, which is very close to being done (finally!).

FWIW you can accurately detect the body with the additional import of the `type-is` module (which is already a dependency of this module) though `require('type-is').hasBody` export. That is the work-around I'm using within my own code base until 2.0.

I'm going to at least try and rebase the current 2.0 branch tonight and cut an alpha of it to npm to give it the proper push forward it needs at this point. This is just an aside, I'm not saying this would really help you in particular.

**Comment by gajus** [comment]
Thank you.

**Comment by sublimator** [comment]
When is 2.0 out ??

**Comment by indolent-developer** [comment]
So any solution for this out yet. I am not able to check for empty content since body parser always defaults to {} even if client didn't provide any content.

**Comment by harryhazza77** [comment]
i created this middleware

```
const typeis = require("type-is");

module.exports = (req, res, next) => {
  if (typeis.hasBody(req)) {
    req.on("data", function(chunk) {
      try {
        JSON.parse(chunk.toString());
        next();
      } catch (e) {
        res.status(400).json({ message: "valid json required" });
      }
    });
  }
  next();
};

```
and injected it into the pipeline **before** `app.use(express.json());`

**Comment by harryhazza77** [comment]
i created this middleware and added it **before** `app.use(express.json());`
```
const typeis = require("type-is");

module.exports = (req, res, next) => {
  if (typeis.hasBody(req)) {
    req.on("data", chunk => {
      try {
        JSON.parse(chunk.toString());
      } catch (e) {
        res.status(400).json({ message: "valid json required" });
      }
    });
  }
  next();
};

```

**Comment by dougwilson** [comment]
Sorry, just following up here that this was released in the current 2.0 preview release. The final 2.0 is targeted to release sometime in March (this month).

**Comment by nabilzhafri** [comment]
@dougwilson can we also mention this breaking changes in the release notes? https://github.com/expressjs/body-parser/releases/tag/2.0.0. I broke my codes thinking that the only breaking changes was only Node.js 18 minimum requirement, until I had to dig into the repo's issues

**Comment by dougwilson** [comment]
Sorry I stopped being involved with this project before 2.0 was even relased, I am not sure what the details are for the release.
