### ISSUE TITLE
CSP report parsing by default?

### ISSUE THREAD

**Issue by bevacqua** [expressjs/body-parser#290]
It took me a tad of digging to figure out that CSP reports were coming up empty because `body-parser` was refusing to parse them unless I configured `type: ['application/json', 'application/csp-report']`. Should this be part of the defaults?

**Comment by dougwilson** [comment]
So the defaults used to be more open until a security vulunerability was filed against us and we changed them to be only a single specific type. I'm afraid my hands are tied here :/
