### ISSUE TITLE
parameterLimit - ok to set to more than 1000?

### ISSUE THREAD

**Issue by rdyar** [expressjs/body-parser#291]
Hi, I am trying to track down a `413 request entity too large` error in a file uploader app. Initially I thought this was a problem in Nginx but I have increased that and it doesn't seem to be my problem.

My app does use Express and body-parser but does not set the `parameterLimit` so I assume it is the default 1000.

My issue is with uploading large numbers of files - for instance 1000 1kb text files gave this error. If I do 500 it works fine.

If I increase the `parameterLimit` will I run into problems? is there something I should consider before doing this? if I set it to 5000 would that cause a problem in something else I am not thinking of?

Also, it is not clear to me what the 1000 limit actually is - I get the error at around 700 (still testing).

**Comment by dougwilson** [comment]
Yes, the `parameterLimit` defaults to 1000 (docs: https://github.com/expressjs/body-parser#parameterlimit). There is no issue making it larger or smaller; ideally you set it to fit your expected payload. Overall, the larger you make it, the larger the request the client can make is, with the ability for each request to consume more memory. You just need to account for accepting larger payloads is all 👍 

The parameterLimit is the maximum number of parameters accepted in your urlencoded request. A urlencoded request looks like `param1=value1&param2=value2`. It's the number of `param#` that can be in the request.

**Comment by rdyar** [comment]
awesome, thanks so much for the quick reply.
