### ISSUE TITLE
65535 bug

### ISSUE THREAD

**Issue by alpha-and-omega** [expressjs/body-parser#293]
Hello guys!
Any idea why body-parser can't handle POST values greater than 65535 bytes ?
I send POST with urlencoded body:
param1=looooong-string-with-length-70000-bytes&param2=same
It receives both parameters, but req.body.param1.length = 65535 and req.body.param2.length = 65535, and values are just truncated to this size.

**Comment by dougwilson** [comment]
Hm, I haven't seen that before. It's possible the underlying parser module we use may be doing this? Can you help provide all the following and we can dig in:

1. Version of Node.js
2. Version of this module
3. Complete code and instructions to reproduce, including the actual body content that is being posted.

Thanks!

**Comment by alpha-and-omega** [comment]
Oh. Sorry. Not a bug. Found error in other place. Thanks!
