### ISSUE TITLE
why boolean datatype is parased as string

### ISSUE THREAD

**Issue by leftluoyi** [expressjs/body-parser#294]
I have a express project which includes the bodyParser

```
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
```

I send a very simple json object 
```
$.post("http://ip:port/test",{data: true}, function(data) {
    feature_mapping = data
})
```
when parse the request body with`console.log(req.body)` , what I got is `{ data: 'true' }`, where `req.body.data` is a string, not boolean. How can I parse the req.body object with proper datatype?

**Comment by dougwilson** [comment]
Your request is sending as urlencoded, in which all values are strings. This is the nature of that serialization format. Instead, send it as JSON and the type will be kept since JSON supports that.
