### ISSUE TITLE
body-parser 'request size did not match content length'

### ISSUE THREAD

**Issue by kevinkassimo** [expressjs/body-parser#295]
Hi, I encountered a weird (yet probably silly I have to say) problem with body-parser when parsing JSON. I have a node script sending a POST request like the following:
```javascript
const postJSON = JSON.stringify({
    title: '3',
    body: 'POST 3'
});

const postOptions = {
    hostname: 'localhost',
    port: '3000',
    path: '/api/cs144/9',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(postJSON)
    }
}
let req = http.request(postOptions, (res1) => {
  //...
});
req.write(postJSON)
```
and on the backend, I have a Express server with body-parser:
```javascript
router.post('/:username/:postid', bodyParser.json({ type: '*/*' }), (req, res, next) => { /* ... */});
```
However, `req.body` is always found empty. Using
```
DEBUG=body-parser:json node main.js
```
always shows the following error:
```
body-parser:json content-type "application/json" +38s
body-parser:json content-encoding "identity" +0ms
body-parser:json read body +1ms
{ BadRequestError: request size did not match content length
    at IncomingMessage.onEnd (/home/cs144/shared/project4/blog-server/node_modules/raw-body/index.js:263:12)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'request size did not match content length',
  expected: 29,
  length: 29,
  received: 0,
  type: 'request.size.invalid' }
```
The same thing happens if I replace the request side with Python's `requests` module:
```python
ses = requests.Session()
response1 = ses.post('http://localhost:3000/api/cs144/9', json={"title": "3","body": "Post 3"})
```
What could have been the problem? Does is mean that `bodyParser.json()` does not wait for `req.on('data', (chunk) => { /*...*/ })` when executed? Thanks in advance!

**Comment by dougwilson** [comment]
Thanks for the information! I tried to replicate real quick, but it worked for me with your client script (I couldn't use the server script you provided, because it was incomplete, but I tried to make it as close to yours as possible). Here is the server script I used:
```js
var bodyParser = require('body-parser')
var express = require('express')

var app = express()
app.post('/:username/:postid', bodyParser.json({ type: '*/*' }), (req, res, next) => {
  res.send('I got a body: '  + JSON.stringify(req.body))
});

app.listen(3000)
```

If you run that and use your Node.js client and python client scripts, does it work for you? If it does, and also works for me, there must be something else going on in your full server that hasn't been shared yet. If you can provide a full example server (like I did above) that replicates the error, I'm sure we can track down the issue :) !

**Comment by dougwilson** [comment]
> Does is mean that bodyParser.json() does not wait for req.on('data', (chunk) => { /*...*/ }) when executed?

This module delegates that to the `raw-body` module you can see in the stack trace. It listens to `req.on('data', (chunk) => { /*...*/ })` and `req.on('end', (chunk) => { /*...*/ })` and all the other necessary events to accumulate the body. Since your error has `received: 0` it's almost like Node.js emitted the `end` event before any `data` events?

**Comment by kevinkassimo** [comment]
@dougwilson Thanks for the reply! I am starting to use your code to check if it works, and will post my updates here soon

**Comment by kevinkassimo** [comment]
Sorry for the wait! Just now I have tested your code, and things are becoming weirder:

At the first run, the server actually yields 404 for quite a while. After repeatedly killing and restarting node, suddenly status becomes 200 and everything looks as if normal.

After getting this 200, I went back to my old code, and ran both `requests` and node `http.request` scripts, and suddenly they both work now! The debug message also becomes normal:
```
body-parser:json content-type "application/json" +53s
body-parser:json content-encoding "identity" +1ms
body-parser:json read body +1ms
body-parser:json parse body +2ms
body-parser:json parse json +0ms
```

During the whole process I changed nothing with the code. This behavior further confuses me

**Comment by dougwilson** [comment]
I have no idea and don't have a Mac to test with. Not sure how to proceed here.

**Comment by kevinkassimo** [comment]
Yeah I am also feeling confused. I am still testing for more cases, will post updates soon

**Comment by kevinkassimo** [comment]
Cannot reproduce the issue any more, issue should not be related with Express/body-parser
