### ISSUE TITLE
Log raw body without messing up later parsers

### ISSUE THREAD

**Issue by iffy** [expressjs/body-parser#296]
Is there a way to get the raw body of the request while still allowing other later parsers to read the body?  All I want to do is log the raw body of every request to a file.  There are a variety of other parsers that occur later in the chain (which ones depend on the route).

I've tried the following:

1. This consumes the body, not letting future parsers have it.

```js
  app.use(bodyParser.raw({limit: '100mb', type: '*/*', verify:(req, res, buf, encoding) => {
    (req as any).rawBody = buf;
    return false;
  }}))
```

2. This fails.  Obvious now, but I thought from the docs that "abort" meant "I actually don't want to parse this. Nevermind.  Keep going."

```js
  app.use(bodyParser.raw({limit: '100mb', type: '*/*', verify:(req, res, buf, encoding) => {
    (req as any).rawBody = buf;
    throw new Error('abort');
  }}))
```

**Comment by dougwilson** [comment]
As far as my understanding of Node.js core HTTP server the body data can only be read once and after that it's been consumed. I'm open to ideas if you have a solution but I don't know of any, unfortunately.

**Comment by iffy** [comment]
One option would be if you could specify to bodyParser where to look for the stream (it defaults to the `request` but you could provide a getter or something to choose another one.  You could then do something like:

```js
app.use((req, res, next) => {
    req.newstream = new Readable();
    // read from req to get what I want.
    req.newstream.push(buf)
    next()
})

app.use(bodyParser.json({stream: (req) => req.newstream}))
```

**Comment by dougwilson** [comment]
Would that mean every other possible body parser for Express would need to all make the same changes? At a minimum, I assume at least all the multipart parsers would, since this module doesn't parse multipart many people use this module in conjunction with at least one other parser, right?

The other thing we should think about to get to a solution here is how to deal with the rest of the details we're reading off the request headers to understand the stream. If we take a custom stream, do we still read all that metadata, or ignore or? Or would some of it will be relevant or not?

**Comment by iffy** [comment]
> Would that mean every other possible body parser for Express would need to all make the same changes?

With what I suggested, I think it would. 

> If we take a custom stream, do we still read all that metadata, or ignore or?

I think the code still would read headers and metadata from the request object.

--- 

Another option that wouldn't require any changes to the other parsers would be something that can create dummy Requests (copy from the original requests but replace the stream).

**Comment by dougwilson** [comment]
> I think the code still would read headers and metadata from the request object.

But then your example wouldn't work for compressed request bodies, right? Because the headers would still have the data saying the request was gzip'd but the given stream is not gzip'd content...

> Another option that wouldn't require any changes to the other parsers would be something that can create dummy Requests (copy from the original requests but replace the stream).

Hm, interesting. How does this work?

**Comment by iffy** [comment]
Oh right... you'd have to be careful with gzipping.

> Hm, interesting. How does this work?

I dunno :)  Something like:

```js
let newreq = Request.clone(req)
req.replaceBody(new Buffer('foobar'))
```

I understand that this cloning/copying code probably doesn't exist, and I'm sure such code would probably be more complex than I'm imagining.  But  maybe that's better than expecting every bodyParser to accept a new argument.

**Comment by iffy** [comment]
And perhaps I should take a stab at the Request cloning option, because it would require no changes to bodyParser.  I'll try that tomorrow.

**Comment by iffy** [comment]
On second (third) thought, I'm just going to do the logging with a proxy server in front of express :)
