### ISSUE TITLE
Sending DELETE with empty payload to express using bodyParser.raw() parses to {} when using content-type: 'application/json'

### ISSUE THREAD

**Issue by peturh** [expressjs/body-parser#297]
I'm building a proxy, or what you can call it with express and bodyparser that is supposed to authenticate users and transferring the requests to our API (they can be binaries, json or whatever).

I'm using 

```
bodyParser.raw({
            type: '*/*',
            limit: '1000mb' // This has to be tested
})
```
We have a DELETE request that sends empty payload, using `content-type: application/json`  On the node server, this empty payload gets parsed to `{}`, all other requests become a Buffer that I can send. This request then breaks the server and throws `TypeError: First argument must be a string or Buffer` when I'm trying to send it.

My question is, who is doing it wrong? Is it bodyParser that parses an empty payload to `{}`? Is it the frontend sending empty body and saying it uses `content-type: application/json` or is it me that is assuming everything I get is a Buffer?

Best regards.

Edit: I found this in `/lib/json.js` 

```
  function parse (body) {
    if (body.length === 0) {
      // special-case empty json body, as it's a common client-side mistake
      // TODO: maybe make this configurable or part of "strict" option
      return {}
    }
```

Is this really correct?

**Comment by dougwilson** [comment]
This is an old behavior that will be fixed in 2.0 because folks have already coded it into apps. Here is the relevant part from the readme that describes what you're seeing:

> All middlewares will populate the req.body property with the parsed body when the Content-Type request header matches the type option, or an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.

I hope this helps!
