### ISSUE TITLE
Preserve compressed data

### ISSUE THREAD

**Issue by OrbitalOwen** [expressjs/body-parser#302]
Hello,

First time using js so bear with me.

I am sending gzipped data to my app. I would like to preserve that gzipped data to send it onwards.

However, bodyParser automatically inflates gzipped data. When the inflate setting is set to false it rejects the request.

Is there any way I can preserve the gzipped string, I'm keen to avoid having to immediately re-compress it.

Thanks

**Comment by OrbitalOwen** [comment]
Thanks for your response @dougwilson 

My desired setup is:

1) Receive gzipped body
2) Send this gzipped body (in string format) elsewhere

I do not need access to the uncompressed body.

I'm not sure if this is even feasible (and if zlib has support for converting to a string), but that would be the ideal setup.

**Comment by dougwilson** [comment]
Gotcha. Since the only reason to use this module is to do what you don't want to do (uncompress the request so you can access the contents), there is no reason to be involving this module. If you don't parse the request and want to send it forward untouched, just don't use the body parser :+1:
