### ISSUE TITLE
Does body-parser require express, or will it work with connect/vanilla node.js?

### ISSUE THREAD

**Issue by jwalton** [expressjs/body-parser#304]
I was pretty sure I already knew the answer to this.  :P  But, I've just started playing with typescript recently, and in typescript-land, the node.js "req" is a `http.IncomingMessage` object.  The "definitelytyped" types for body-parser claim that it returns a `"express-serve-static-core".RequestHandler`, which takes a req of type `Request`, which has all the fancy request methods and properties on it.  As a result, typescript is complaining that my `req` (which is just a vanilla `req`) doesn't match the signature of `RequestHandler`.

```ts
let bodyParserMiddlware: (
    req: http.IncomingMessage,
    res: http.ServerResponse,
    next?: Callback<any>
) => void;

bodyParserMiddlware = bodyParser.json(); // Typescript no-likey-likey
```

If `body-parser` really doesn't need an express-request, then I'll raise a PR against `@types/body-parser`.

**Comment by dougwilson** [comment]
This module doesn't require Express is any way and works on vanilla Node.js (check out our tests, even, no Express.js at all 😄).

**Comment by jwalton** [comment]
Thanks!  :)
