### ISSUE TITLE
function getCharset(req) is crashing because of missing null check

### ISSUE THREAD

**Issue by vitalii-svitla** [expressjs/body-parser#306]
In line 

```
function getCharset(req) {
  try {
    return contentType.parse(req).parameters.charset.toLowerCase()
```

I'm getting exception

> Exception has occurred: TypeError
> TypeError: Cannot read property 'toLowerCase' of undefined

Obviously a nullcheck is missing

**Comment by dougwilson** [comment]
I don't see that exact line in any file. Can you point to it in our source code on github?

**Comment by dougwilson** [comment]
Yea, I checked that file: https://github.com/expressjs/body-parser/blob/master/lib/types/json.js I don't see any line matching the source code you posted above. Which line number?

**Comment by dougwilson** [comment]
I'll probably just be easier if you can open a pull request with the fix, please 👍 Since you don't even have the steps and code to reproduce the issue posted here, I can't just make a fix myself.

**Comment by vitalii-svitla** [comment]
Its line 151.

Haha, actually you can close this ticker. We're using version "1.14.2 / 2015-12-16" xD
