### ISSUE TITLE
Body parser does not seem to be parsing

### ISSUE THREAD

**Issue by seancasaus** [expressjs/body-parser#307]
I have been on this issue for hours trying to find a solution to this problem I encountered in my udemy course.  I have tried using the instructor's code exact and it does not work in the same manner as his, so my guess is that things have changed since the course was made and the current way my code is structured no longer works. 

I installed body parser using: npm install --save body-parser

Here is my code: 
```
var express = require('express');
var bodyParser = require('body-parser');
var app = express();

app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json());

var ingredients = [
    {
        "id":"232kAk",
        "text":"Eggs"
    },
    {
        "id":"dkP345",
        "text":"Milk"
    },
    {
        "id":"dkcuu7",
        "text":"Bacon"
    },
    {
        "id":"73hdy",
        "text":"Frogs Legs"
    }
];

//gets the ingredients 
app.get('/ingredients', function(req,res) {
    res.send(ingredients); //json response
});

//adds an ingredient
app.post('/ingredients', function(req,res) {
    var ingredient = req.body;
    if (!ingredient || ingredient.text === "") {
        res.status(500).send({error: "Your ingredient must have text"});
    }
    else {
        ingredients.push(ingredient);
        res.status(200).send(ingredients);
    }
});

//replace ingredient with diffeent item
app.put('/ingredients/:ingredientId', function(req,res) {
    var ingredientId = req.params.ingredientId;
    var newText = req.body.text;
    console.log(req.body.text);

    if(!newText || newText === "") {
        res.status(500).send({error: "Must Provide Ingredient Text"});
    }
    else {
        for (var x = 0; x < ingredients.length; x++) {
            var temp = ingredients[x];

            if (temp.id === ingredientId) {
                ingredients[x].text = newText; 
                break;
            }
        }
        res.send(ingredients);
    }
});

//port 3000
app.listen(3000, function() {
    console.log("Running on port 3000");
});

```

My issue is that in the put function console.log prints out undefined no matter what body I enter into postman. I would greatly appreciate it if someone can explain what I am doing wrong here.

**Comment by dougwilson** [comment]
Nothing in the code looks wrong and running the code I saw a body come through. It would be really important to know exactly what you're putting in Postman to help you further, since it wasn't stated.

**Comment by seancasaus** [comment]
I did a put request using postman to this url: http://localhost:3000/ingredients/73hdy
And my raw inputed body is
```
 {
	"text":"Hash Browns"
}
```

**Comment by dougwilson** [comment]
That seems right. What content-type did you choose?

**Comment by seancasaus** [comment]
![screen shot 2018-04-30 at 4 39 35 pm](https://user-images.githubusercontent.com/17536911/39455415-21067b1e-4c95-11e8-90e8-a73907e1ebce.png)

**Comment by seancasaus** [comment]
maybe the screen shot of my postman page will help

**Comment by dougwilson** [comment]
Well, I've never used postman before, but your raw body is json so there has to be somewhere in postman you are saying it is json, otherwise this module won't parse it as json.

**Comment by dougwilson** [comment]
Just reading through the Postman help at https://www.getpostman.com/docs/v6/postman/sending_api_requests/requests it seems like that drop down next to "binary" you have set to "Text" is wrong. It should be selected to "JSON"

**Comment by seancasaus** [comment]
Omg you are right, I am new to both postman and body parser and I definitely thought the error was with my code so I have been going through stackoverflow threads on body parser for hours. Thank you for helping me through my very negligent issue.

**Comment by dougwilson** [comment]
It's no problem. The screenshot helped a lot!
