### ISSUE TITLE
JSON data getting corrupted at 8000 character point

### ISSUE THREAD

**Issue by samhaink** [expressjs/body-parser#308]
I'm using body-parser(1.18.2) within express(4.16.3) and seeing very odd behavior.  Its not consistent to all clients.

We have our json parser limit set to 50mb.

 bodyParser.json( {
                limit: '50mb'
            } ),

On some messages that are larger than 8000 bytes, I'm seeing type: 'entity.parse.failed' errors.

The JSON data printed at the same time looks fine, except for right at the 8000 point:

238135","data2":"052529019�k�\u000b\u0000\u0000\u0000\u0000\u0001\u0001\u001b!\u0014\u0000\u0000\u0000\u0001k\u0001����\u0001\u0000\u0000\u0000nextField":"56.00","data3"......

**Comment by dougwilson** [comment]
Very strange. I can't say I've ever seen this before. I would love to take a look. Can you provide complete code and exact steps to replicate the issue? I can then start digging in :+1:

**Comment by samhaink** [comment]
Very sorry to waste your time!  Determined one client was using an 8000 byte buffer deep in their logic and they are not properly chunking the data correctly.  Good to close!
