### ISSUE TITLE
body-parser JSON fails with primitive types

### ISSUE THREAD

**Issue by jvilk** [expressjs/body-parser#309]
As far as I am aware, `true`, `false`, `0`, and `"foo"` are valid JSON. However, body-parser's JSON parser fails to parse these bodies with the error message:

```
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/Users/jvilk/Code/bodyParserIssue/node_modules/body-parser/lib/types/json.js:157:10)
    at parse (/Users/jvilk/Code/bodyParserIssue/node_modules/body-parser/lib/types/json.js:83:15)
    at /Users/jvilk/Code/bodyParserIssue/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/Users/jvilk/Code/bodyParserIssue/node_modules/raw-body/index.js:224:16)
    at done (/Users/jvilk/Code/bodyParserIssue/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/jvilk/Code/bodyParserIssue/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:180:13)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

Is this by design? Does body-parser only support object and array payloads? I am using the latest version of `body-parser` and `express`.

## Code Demonstrating Issue

package.json:

```json
{
  "name": "bodyParserIssue",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "body-parser": "^1.18.2",
    "express": "^4.16.3"
  }
}
```

Server source code (`index.js`) (essentially the example in README):

```javascript
var express = require('express')
var bodyParser = require('body-parser')

var app = express()

app.use(bodyParser.json())

app.use(function (req, res) {
  res.setHeader('Content-Type', 'text/plain')
  res.write('you posted:\n')
  res.end(JSON.stringify(req.body, null, 2))
})

app.listen(9001)
```

Curl invocations to trigger issue:

```
curl --data "false" --header "Content-Type: application/json" --request GET  localhost:9001/test
curl --data "true" --header "Content-Type: application/json" --request GET  localhost:9001/test
curl --data "3" --header "Content-Type: application/json" --request GET  localhost:9001/test
curl --data '"foo"' --header "Content-Type: application/json" --request GET  localhost:9001/test
```

**Comment by dougwilson** [comment]
Yes, this is by design. Set the `strict` option (https://github.com/expressjs/body-parser#strict) to `false` to accept them.

**Comment by jvilk** [comment]
Thanks! Do you think the error message could be changed to be a bit clearer? Or is that infeasible from how `body-parser` is written?

**Comment by dougwilson** [comment]
Error message is from `JSON.parse`.

**Comment by jvilk** [comment]
Yes, but `JSON.parse` works on `"0"`, `true`, etc. I figured you are doing something special to filter out non-object/array types.

**Comment by dougwilson** [comment]
We are, but the message it intended to act exactly as if `JSON.parse` didn't accept them, so it looks exactly as terse as for example `JSON.parse('<gibberish>')`:
```
> JSON.parse('<gibberish>')
SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by jvilk** [comment]
From my perspective, the error message (understandably) made me think that I had sent malformed JSON. I spent 10 minutes double checking my code, which is using the clunky XMLHttpRequest interface (so a mistake is not out-of-the-question), and also whipped out WireShark to inspect the packets the code was generating, before isolating `body-parser` as the issue.

I personally think it is a misleading error message, as `body-parser` has consciously decided to reject a perfectly valid JSON string.

Anyway, I am just saying this so you understand my perspective, in case you decide to revisit this at some point. I am thankful for this library and the Express ecosystem in general. 😄

**Comment by dougwilson** [comment]
Sure, but all you're doing is arguing with someone who already agrees with you. I didn't write that into the module, I inherited it. I already plan to change that in 2.0, but I can't just suddenly issue a 1.x release in which data that was previously filtered out suddenly was not. This could cause security issues in applications that were relying on the existing filtering.
