### ISSUE TITLE
there's nothing in req.body 

### ISSUE THREAD

**Issue by BadmasterY** [expressjs/body-parser#310]
Oh, I'm a newcomer to Node.js.

Look at 《SMASHING Node.js :JavaScript Everywhere》. Many of the codes and API here are old. Now I'm using the Connect load file, which uses the body-parser middleware.

> req.body => {}

Here's my code. I think I did it wrong, but I don't know what caused it.
```
const connect = require('connect');
const http = require('http');
const morgan = require('morgan');
const serveStatic = require('serve-static');
const bodyParser = require('body-parser');

let app = connect();

app.listen(3000);

app.use(morgan('dev'));

app.use(bodyParser.text({inflate:false}));

app.use(function( req , res , next){
	if('POST' == req.method){
		console.log(req);
		res.end('POST!');
	}else{
		next();
	}
});	

app.use(serveStatic(__dirname+'/load-files'));

let server = http.createServer(app);
```

**Comment by dougwilson** [comment]
There is nothing wrong with the code above. If you can describe to me exactly how you're making the request or provide a Wireshark capture we can see what the request looks like to see what is happening.

**Comment by BadmasterY** [comment]
@dougwilson 
Emmmm,okay.
I have an HTML file that contains the following code.
```
        <form action="/" method="POST" enctype="multipart/form-data">
		<input type="file" />
		<button>Send file!</button>
	</form>
```
Then I uploaded a TXT file containing Hello World, but when I got the POST request, req.body didn't have any content, which made me very upset.

**Comment by dougwilson** [comment]
Ah, that's the issue. Your form is using `multipart/form-data`, but this doesn't support that: 

> This does not handle multipart bodies, due to their complex and typically large nature. For multipart bodies, you may be interested in the following modules:

And you can find the links to those modules at the top of the README 👍
