### ISSUE TITLE
What is the exact byte on express for client server communication?

### ISSUE THREAD

**Issue by Rizary** [expressjs/body-parser#311]
Hi, I have frontend using haskell and backend using nodejs (express) and i use the following code:
```
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended:true }));
```

On my frontend app, I use simple POST request to my server and below are the raw header that i got:
Request
```
Host: 192.168.1.19:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://192.168.1.19:8080/
Content-Type: application/x-www-form-urlencoded
Content-Length: 37
Connection: keep-alive
```

Response 
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 2491
Date: Mon, 07 May 2018 19:42:00 GMT
Connection: keep-alive
```

The problem is that when I send POST to the server, it cannot detect that I'm sending JSON like the following

`{"password":"aoeu","username":"oaeu"} |  ` and keep returning `{}`. How to diagnose this also?

thanks,
andika

**Comment by dougwilson** [comment]
Your request has the header

Content-Type: application/x-www-form-urlencoded

If your sending json, I assume your header should be the following:

Content-Type: application/json

If you want that type to be parsed as json, you can pass in the type parameter to the json parser like so:

app.use(bodyParser.json({ type: 'application/x-www-form-urlencoded' }));

I hope that helps!

**Comment by Rizary** [comment]
@dougwilson hi, Thanks!! can I ask you again? so in the backend, I have the following code:

``` 
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended:false, type: 'x-www-form-urlencoded' }));
```

can I use both at the same time?

**Comment by dougwilson** [comment]
Yep!

**Comment by Rizary** [comment]
I see, nice! @dougwilson 
One more thing, I have actually change it into "application/json;charset=UTF-8", however I got stuck on the status `pending`. I know that it is because the cors (maybe?). this `pending` status lead me to get `net::ERR_EMPTY_RESPONSE` in my console.

How to mitigate this? or could you direct me on what should I do?

**Comment by Rizary** [comment]
Hmm... I see, so when I got `pending` status when sending xhr data, i notice the following error in my console server:

```
POST /auth/login - - ms - -
BadRequestError: request aborted
    at IncomingMessage.onAborted (/nix/store/badlbckrdfl144s5isbm7px6rxrdjdp5-qoeifs-app/prod/node_modules/raw-body/index.js:231:10)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at abortIncoming (_http_server.js:424:9)
    at socketOnClose (_http_server.js:418:3)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:567:12)
POST /auth/register - - ms - -
```

Is this still relevant?

**Comment by Rizary** [comment]
![image](https://user-images.githubusercontent.com/7221768/39732364-16a5f2be-5297-11e8-8388-308bf327277c.png)

**Comment by Rizary** [comment]
@dougwilson  I try to enable cors by using `app.use(cors())` but nothing changed.

**Comment by dougwilson** [comment]
So request aborted means that the client disconnected before sending all the data. I can certainly take a look. Would you be able to provide all your code and instructions so I can reproduce the error? I may be able to debug through the issue to point you in the right direction or figure out if there is a bug.

**Comment by Rizary** [comment]
@dougwilson 

hi, sure, i have sent you invitation to the binary repo.

**Comment by Rizary** [comment]
@dougwilson 

It is basically a simple express app, there will be 2 menu in the landing page `Login` and `About`. You can click it and the menu will pop-up.

Then in the `Login` page there are 2 section, `Masuk` means `login` and `Daftar` means `register`. You might need mongodb running/installed.

**Comment by dougwilson** [comment]
Cool. I'm not home tonight but will try to pull it down and setup tomorrow. I never used mongodb so will look at how to get that setup as well.

**Comment by Rizary** [comment]
@dougwilson fwiw, i have setup simple API restful using python flask, and it works perfectly.

**Comment by dougwilson** [comment]
If that is working awesome :+1:

**Comment by Rizary** [comment]
I believe we can find the problem why using body-parser, return error like that. I hope we can still find solution re this.

**Comment by dougwilson** [comment]
Yea. I just got up and going to work now and so will look at your repo after I get off work :+1: probably in about 10 hours from now.

**Comment by Rizary** [comment]
@dougwilson hi... how are you? I hope you are fine. I want to ask about this issue if you dont mind.

**Comment by dougwilson** [comment]
Hi @Rizary I spent a bunch of time yesterday but didn't get it quite working yet. I was able to get it started and then for example I got to http://127.0.0.1:8080/ and it's just a blank page. I'll continue to poke around to find the area you're referring to, but if you have any specific instructions someone who knows nothing about how your project works gets to the area you're talking about that would help move this much quicker 👍

**Comment by Rizary** [comment]
@dougwilson  I just tested it today at 11AM UTC+7 and it works fine. We just install mongodb, run npm install and npm start which will serve index.html in static folder

**Comment by dougwilson** [comment]
Ok, the issue was my mongodb didn't setup right. So I just did it and saw no body. I made the change mentioned in https://github.com/expressjs/body-parser/issues/311#issuecomment-387182019 and it works correctly now.

**Comment by dougwilson** [comment]
```patch
diff --git a/app.js b/app.js
index 8a8be62..111d869 100644
--- a/app.js
+++ b/app.js
@@ -39,7 +39,7 @@ app.use((req,res,next)=>{
 
 // configure app
 app.use(logger('dev'));
-app.use(bodyParser.json());
+app.use(bodyParser.json({ type: 'application/x-www-from-urlencoded' }));
 app.use(bodyParser.urlencoded({ extended:true }));
 app.use(validator());
 app.use(express.static(path.join(__dirname, 'public')));
```

Then I see the following:
<img width="345" alt="screen shot 2018-05-09 at 09 39 44" src="https://user-images.githubusercontent.com/67512/39817802-29b6ff5c-536d-11e8-9c47-64c9cefd76d6.png">

**Comment by Rizary** [comment]
i have clean the code here: https://github.com/Rizary/QOEIFS-BIN

how about the registration? hmm... why we have to add x-www? because as you can see in my original code:

![image](https://user-images.githubusercontent.com/7221768/39817998-f9f329f0-53c9-11e8-99c1-ae106d109669.png)

is it states `Content-type =: "application/json"`

**Comment by Rizary** [comment]
anyway, what is the correct statement? `x-www-from-urlencode` or `x-www-form-urlencode`?

**Comment by dougwilson** [comment]
> hmm... why we have to add x-www?

Well, just like in your original post, your client request is sending that as the content-type header. I'm not sure what that code is you're showing me; it doesn't even look like JavaScript. The `body-parser` will filter the parse based on the `content-type` you're sending from the web browser to node.js. You don't have to set that if you send the content-type as `application/json` from your web browser request.

**Comment by dougwilson** [comment]
> anyway, what is the correct statement? x-www-from-urlencode or x-www-form-urlencode?

Both those seem like the same thing. It needs to be set to exactly what your content-type header it set to.

**Comment by Rizary** [comment]
`form` means `<form>` and `from` has another meaning?

**Comment by Rizary** [comment]
@dougwilson TIL, well it is haskell to javascript using [ghcjs](https://github.com/ghcjs/ghcjs) as compiler. Anyway, thanks for the help!!! I am not trying to ask another help, just out of curiosity.

It seems strange to me that my compile-to-js send `application/json` to the `body-parser` and it detect as other format, meanwhile the other library read the same. If it is possible can you point me where the `body-parser` detect it in the code? If you dont mind. Or maybe i'll look into it myself (though it will takes more time).

Again @dougwilson, thank you very much for the help.

**Comment by dougwilson** [comment]
It just detects it by looking at the variable `req.headers['content-type']` in the request. Add `console.log(req.headers['content-type'])` in there. Even when I use Chrome I see that your client side code is sending that header, just like you pasted at the top comment:

<img width="736" alt="screen shot 2018-05-09 at 09 56 56" src="https://user-images.githubusercontent.com/67512/39818765-a5b88ca4-536f-11e8-8057-1b5a1af6586b.png">

**Comment by Rizary** [comment]
Hmm right, well regarding my first pasted comment, i put `application/x-www-from-urlencoded` in my frontend code. But i will discuss this with the library maintainer that i use. thanks! :) 👍

**Comment by Rizary** [comment]
![capture](https://user-images.githubusercontent.com/7221768/39819181-0798fd3e-53cd-11e8-8c39-5aadd198017e.JPG)

for documentation. 👍

**Comment by Rizary** [comment]
![capture1](https://user-images.githubusercontent.com/7221768/39819282-403c8b7e-53cd-11e8-912b-ddec58d09bd0.JPG)

and this is for backend code.

**Comment by dougwilson** [comment]
I'm happy to help you, but you can see from my screenshot the code I seem to have is not working the same way as what you're showing. Why?

**Comment by Rizary** [comment]
anyway, very appreciate with your help. I am sure noone will help me like you do even for the open ticket!!

**Comment by Rizary** [comment]
re the code, i have updated my QOEIFS-BIN repo, with the newest code. if you have time, maybe you can take a look a bit, although for me it is solved right now. Thanks @dougwilson
