### ISSUE TITLE
Release new version for Node v10

### ISSUE THREAD

**Issue by felixbuenemann** [expressjs/body-parser#312]
As discussed in stream-utils/raw-body#59 it would be great to have a new npm release with the changes from master to get rid of `new Buffer()` deprecations on Node v10.

**Comment by dougwilson** [comment]
Sorry I didn't finish the changes before I had to leave. I'll get on finishing up now.

**Comment by felixbuenemann** [comment]
No problem, I just created an issue so it doesn't get forgotten.

**Comment by dougwilson** [comment]
Yea, I haven't forgotten :+1: friday a security issue was reported on a module publicly and that ended up derailing me, haha. I have some time today I'm planning to use if the person stops emailing me about cookies to spend tim on it :S

**Comment by dougwilson** [comment]
Just published as version 1.18.3 🎉
