### ISSUE TITLE
json limit 

### ISSUE THREAD

**Issue by sharmaanirudh007** [expressjs/body-parser#313]
I am sending a base64 encoded image in json body to my node server and i have set a limit of 50mb on my bodyparser json structure.  Yet only slightly bigger than 400kb data of image is getting uploaded. This is my code -
**app.use(bodyParser.json({limit:'50mb', type:'application/json'}));**
Node v : 0.10.25

Please help me figure this out.

**Comment by sharmaanirudh007** [comment]
i have figured it out.

**Comment by texas697** [comment]
@sharmaanirudh007 what was your solution
