### ISSUE TITLE
UnsupportedMediaTypeError: unsupported content encoding "aesgcm"

### ISSUE THREAD

**Issue by tateisu** [expressjs/body-parser#314]
UnsupportedMediaTypeError: unsupported content encoding "aesgcm"

app.use('/path', bodyParser.raw({
}))

can I support this content encoding  to same as 'identity' ?

**Comment by dougwilson** [comment]
I'm not familiar with that encoding, but we have the feature request https://github.com/expressjs/body-parser/issues/108 to allow custom content encodings, which would support your use case.

Duplicate if #108
