### ISSUE TITLE
typescript error on verify function ; rawBody is not defined

### ISSUE THREAD

**Issue by sujeshthekkepatt** [expressjs/body-parser#317]
Hai, @dougwilson since we are adding a new property to request object shouldn't we merge the type declarations for http.IncomingMessage? I am getting error 'rawBody is not on incoming message' in TypeScript

**Comment by dougwilson** [comment]
I guess? I'm not familiar with typescript, happy to make whatever changes make it work. What do I need to change?

**Comment by sujeshthekkepatt** [comment]
I think it is related to typescript definition for body-parser https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/body-parser. I am a newbie in typescript.

**Comment by dougwilson** [comment]
Ah looks like that is a different repo. Maybe open issue there :+1:
