### ISSUE TITLE
bodyParser.text returns empty object even when it should not parse

### ISSUE THREAD

**Issue by deep9** [expressjs/body-parser#318]
If request has body and should be parsed, the result is text, as expected.

But, if the body should not be parsed by the text parser (no content) it returns {}

In https://github.com/expressjs/body-parser/blob/e6ccf98015fece0851c0c673fc2776c30ad79e5d/lib/types/text.js#L64 the request body is set. I think it should be done only after (if ever) all the checks not calling next() are done. Also, it should return undefined or empty string.

**Comment by dougwilson** [comment]
Yes, I agree it should be undefined when not parsed. Check out the "2.0" branch if you want to see the progress towards a 2.0, which actually includes the change you're askin for :+1:
