### ISSUE TITLE
npm install of body-parser 1.18.3 fails due to HTTP 500 Internal Server ERror

### ISSUE THREAD

**Issue by Captainhat** [expressjs/body-parser#319]
Hello, currently when attempting to install body-parser 1.18.3 using "npm install body-parser" the install will fail when it attempts to fetch body-parser-1.18.3.tgz, throwing a HTTP 500 Internal Server error. 

```
193 http fetch GET 500 http://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz 70110ms attempt #3
194 silly fetchPackageMetaData error for body-parser@^1.17.1 500 Internal Server Error: body-parser@^1.17.1
```

Let me know if you need additional details.

**Comment by dougwilson** [comment]
You'll need to contact npm, as there isn't anything I can do as a module author.
