### ISSUE TITLE
request.body.result is undefined in firebase code

### ISSUE THREAD

**Issue by DivyaRamamoorthy24** [expressjs/body-parser#323]
Hi guys! I'm trying to save the user details which is entered in the dialogflow console into a database, For that reason I used a firebase cloud firestore to store details.In the firebase code,I am getting issue like request.body.result is undefined, which throws me a typeerror on action.

Here is my index.js code:
```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

var firestore = admin.firestore();

exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
      
    if (!request.body.result) {
        console.log('dhsjh' + request.body.result);
        console.log('Invalid Request' + JSON.stringify(request.body.result));
        return response.status(400).end('Invalid Webhook Request (expecting v1 or v2 webhook request)');
      }

    
     console.log('Request headers: ' + JSON.stringify(request.headers));
     console.log('Request body: ' + JSON.stringify(request.body));
   
 

    
    let action = request.body.result.action;

     

   
    let query = request.body.result.resolvedQuery;

    
    const parameters = request.body.result.parameters; // https://dialogflow.com/docs/actions-and-parameters

   
    const inputContexts = request.body.result.contexts; // https://dialogflow.com/docs/contexts

    if(action === 'save.name'){
      admin.firestore().collection('users').add({
                        name: name
                    }).then(ref => {
                        console.log('Added new user');
                    });
    elif
        {
        console.log("Specified action is not enabled");
        }
      }
 });
```

Error:

dialogflowFirebaseFulfillment | TypeError: Cannot read property 'action'

**Comment by dougwilson** [comment]
Hi @DivyaRamamoorthy24 sorry you're having trouble. I'm sorry I'm unfamiliar with firebase and what that is. I don't see you actually using this module anywhere in your code above, though (no require('body-parser')` is there, for example). Is it possible you can provide the following information so we can take a look?

1. Version of Node.js you're using
2. Version of this module you're using
3. Complete code that we can copy and paste and run without modification to replicate the issue. If this includes other modules besides `body-parser` either try and remove them to get a quicker diagnosis or list out all the exact versions so we can set it up
4. Complete instructions for how to replicate the issue. Typically this is the exact instructions on how to get the said code running and then the exact request to make to the code (complete with all headers, body, etc.)

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
