### ISSUE TITLE
Body Parser clarity on parsing the value "" as valid json.

### ISSUE THREAD

**Issue by ndaljr** [expressjs/body-parser#324]
Why does body-parser not consider the value `""` as valid json when `JSON.parse('""')` does? 

I'm currently working on a side project where the third party I'm working with returns the value `""` as json in a post request and I don't want to argue with them since they say that the value `""` is valid json. Reason being that when they pass that value on JSONLint.com, the website indicates that its valid json. 

Somehow, when express receives this value as a request, it throws an error.

**Comment by dougwilson** [comment]
Just set strict: false in the .json options and it will parse primitive types. Example:
```
app.use(bodyParser.json({ strict: false }))
```
