### ISSUE TITLE
Body-parser doesn't not return res.body

### ISSUE THREAD

**Issue by mahmoudZakaria90** [expressjs/body-parser#328]
# Issue
while making a POST request from a mini front-end app in the same folder and goes successfully but no return from `res.body`

check this repo please 
https://github.com/mahmoudZakaria90/RestAPI

**Comment by dougwilson** [comment]
The issue is that on your code you used the json parser yet when I look at the browser network tab you are submitting urlencoded to the server.

You need to either use the urlencoded parser in your server or send json from the browser.

**Comment by mahmoudZakaria90** [comment]
I'm not encoding any url, if you looked again at the network tab you will find `status: 200 OK` that's mean that ajax request success the returned data are from Mongoose and they are default fields like `_id`.

anyway I tried all the ways to send data as a literal `{}` or `JSON` but nothing.
I guess there is something with the `bodyParser` maybe I'm not sure.

**Comment by mahmoudZakaria90** [comment]
Worked! thanks a lot @dougwilson yeah it's the urlencoded-parser
