### ISSUE TITLE
Seeing https://github.com/expressjs/body-parser/issues/299 in production

### ISSUE THREAD

**Issue by kirankashalkar** [expressjs/body-parser#331]
Hi,

We are seeing the same symptoms as per https://github.com/expressjs/body-parser/issues/299.
In our case though the BadRequestError is not getting caught and seems to be wreaking havoc in AWS (reporting as service degradation)

We are also getting this only in production and not on our development/staging systems.
I would prefer not to publicly list prod URLs, so if there is a way for me to PM someone when looking at the issue, I will.

Thanks!

**Comment by dougwilson** [comment]
You can email me if you need, but as per the issue you linked, there isn't anything I can even look into unless you can provide steps to reproduce, otherwise there isn't anything for me to debug. If you can provide a reproduction case I can look into, I can re-open this issue.

**Comment by kirankashalkar** [comment]
Thank you.
I have emailed you.
