### ISSUE TITLE
Recuest Aborted

### ISSUE THREAD

**Issue by Maeu26** [expressjs/body-parser#335]
Todo iba bien hasta ahora que me aparece el error Recuest Aborder cuando intente subir una imagen a un usuario que estoy creando en mi proyecto. 
![sin titulo](https://user-images.githubusercontent.com/44483068/47534023-dfb07900-d883-11e8-88fc-f944e2759620.png)

Este es el código que tengo cuando me dirijo hasta donde me indica el error:
```js
var self = this;
  req
    .on('error', function(err) {
      self._error(err);
    })
    .on('aborted', function() {
      self.emit('aborted');
      self._error(new Error('Request Aborted'));
    })
    .on('data', function(buffer) {
      self.write(buffer);
    })
    .on('end', function() {
      if (self.error) {
        return;
      }

      var err = self._parser.end();
      if (err) {
        self._error(err);
      }
    });

  return this;
};
```

**Comment by dougwilson** [comment]
https://github.com/expressjs/body-parser#request-aborted

**Comment by dougwilson** [comment]
You're not even using this module.

**Comment by dougwilson** [comment]
For Node.js help: https://github.com/nodejs/help

**Comment by Maeu26** [comment]
Estos son los módulos que estoy usando
"dependencies": {
    "body-parser": "^1.18.3",
    "connect-busboy": "0.0.2",
    "cookie-session": "^2.0.0-beta.3",
    "express": "^4.16.3",
    "express-formidable": "^1.2.0",
    "express-logger-unique-req-id": "^1.0.4",
    "express-session": "^1.15.6",
    "jade": "^1.11.0",
    "method-override": "^3.0.0",
    "mongoose": "^5.3.2",
    "shortid": "^2.2.13"

**Comment by dougwilson** [comment]
The stack trace us coming from the module "formidable", not this module.
