### ISSUE TITLE
Error catching

### ISSUE THREAD

**Issue by saa432** [expressjs/body-parser#344]
How catch error via using as local-midleware?

`` const bodyParser = require("body-parser").json({limit:'10mb',extended:true});

async function CheckParamsValid(req,res,next){
    if(!validLogin(req.body)){
        return res.status(403).
                                send({"error": true, "message": "Some error "});
    }
    else{next();}
}

async function EndPoint(req,res,next){
    return res.status(200).send({"error":false,"message":"Ok"});
}

Router.post('/login',bodyParser,CheckParamsValid,EndPoint);

{
	"login":123"ek43",

	"password":"abcdef"
}``

Can you show example with that code?

**Comment by dougwilson** [comment]
This is an Express.js middleware, as such you catch errors the same way as you would any Express.js middleware. See section "Writing error handlers" in the Express.js documentation http://expressjs.com/en/guide/error-handling.html

**Comment by saa432** [comment]
> This is an Express.js middleware, as such you catch errors the same way as you would any Express.js middleware. See section "Writing error handlers" in the Express.js documentation http://expressjs.com/en/guide/error-handling.html

that's f*cking stupid way to handle error's
