### ISSUE TITLE
Provide source (unchanged) body as property (rawBody as example)

### ISSUE THREAD

**Issue by borovik96** [expressjs/body-parser#348]
I need to have access to an unchanged body to calculate the checksum. And at the same time, I need a parsed body. I know that I can put my route before `body-parser` middleware and parse body myself, but it seems like a workaround.

**Comment by dougwilson** [comment]
Hi! Just pass a function to the "verify" option to calculate your checksum off the raw body. That is the purpose of that option.

Does that option not work for you? If so, why, and perhaps we can improve it.

**Comment by borovik96** [comment]
Yes, I think it does, thanks!
