### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 3

### ISSUE THREAD

**Issue by temurih** [expressjs/body-parser#354]
I have just installed `"body-parser": "^1.18.3"`, and I added `express.use(bodyParser.json());`. Without using the `body parser` my routes work fine, but of course `req.body` is always `undefined`. I am not using `JSON.parse` anywhere inside my app, and I am certain that the error is coming from the package itself.

```
<pre>
    SyntaxError: Unexpected token e in JSON at position 3
    <br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)
    <br> &nbsp; &nbsp;at parse (C:\Users\Hafiz\Desktop\NowHiring\backend\node_modules\body-parser\lib\types\json.js:89:19)
    <br> &nbsp; &nbsp;at C:\Users\Hafiz\Desktop\NowHiring\backend\node_modules\body-parser\lib\read.js:121:18
    <br> &nbsp; &nbsp;at invokeCallback (C:\Users\Hafiz\Desktop\NowHiring\backend\node_modules\raw-body\index.js:224:16)
    <br> &nbsp; &nbsp;at done (C:\Users\Hafiz\Desktop\NowHiring\backend\node_modules\raw-body\index.js:213:7)
    <br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\Hafiz\Desktop\NowHiring\backend\node_modules\raw-body\index.js:273:7)
    <br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:182:13)
    <br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1094:12)
    <br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)
</pre>
```

**Comment by temurih** [comment]
UPDATE: I just realized that I am missing quotes in the json I was sending down. Its dumb that it throws an exception when someone sends a wrong json. Wouldn't it crash the server if someone tries to attack it? 😕

**Comment by dougwilson** [comment]
The error is passed to the Express error handing mechanism http://expressjs.com/en/guide/error-handling.html

**Comment by 4s1ckb0y** [comment]
i had the same issue and i turned out to have missed a comma in the json request i have sent , being really frustrated for 2 days, this is so dumb !!!
