### ISSUE TITLE
400 error using urlencoded on POST requests larger than 4096

### ISSUE THREAD

**Issue by johnennewdeeson** [expressjs/body-parser#357]
On our production server we are seeing the following errors:

```
BadRequestError: request aborted
  at IncomingMessage.onAborted (node_modules/express/node_modules/raw-body/index.js:231:10)
   at emitNone (events.js:106:13)
   at IncomingMessage.emit (events.js:208:7)
   at abortIncoming (_http_server.js:412:9)
   at socketOnClose (_http_server.js:406:3)
   at emitOne (events.js:121:20)
   at Socket.emit (events.js:211:7)
   at TCP._handle.close [as _onclose] (net.js:554:12)
```

It appears to happen on POST requests where the request body is large, in fact it happens as soon as the Content-Length goes over 4096.

We cannot replicate the issue off of the server despite using the same versions of node and express (node 8 and express 4.16.4).  Everything work fine sending any size of POST to a local running version of the app.

The app.js code is as follows.

```
var express = require('express');
var app = express();
app.server = require('http').createServer(app);

app.use(express.urlencoded({
    extended: false,
    limit: '100MB'
}));

app.server.listen(3000);

```

We are guessing it is something to do with the hosting (we host with Platform.sh) and have a ticket logged with them to see if they are truncating body requests in some way.

Looking at how the body is loaded through urlencoded, a 400 error seems to be thrown if the readStream() function fails.  I can't seem to be able to do any futher debugging past what we are seeing, it just seems to be reading the stream that fails when the size grows beyond 4096.

Can anyone suggest anything else we can look into? Is there something about how the stream chunks the input that happens around 4096 bytes of input?

**Comment by johnennewdeeson** [comment]
Think its the same issue these guys were having https://github.com/expressjs/body-parser/issues/299 - doesn't look like they had any success (or if they did they didn't say!)

**Comment by dougwilson** [comment]
Without a reproduction case, I don't really know why the socket is closing on your Node.js HTTP server. The error you're getting means that the socket was closed but there were not enough bytes recieved.

**Comment by dougwilson** [comment]
Under the hood, the module relies to Node.js to shuttle the bytes. They have some documentation here if it helps debug: https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/#request-body

**Comment by johnennewdeeson** [comment]
Thanks for your reply, confirms what we are seeing.

**Comment by johnennewdeeson** [comment]
After further analysis by the hosting provider, this was the web application firewall (WAF) altering the POST body based on its ruleset.  In our case we had an _application/x-www-form-urlencoded_ request which included a single key in the body over 4096 bytes which was enough for the WAF.  It doesn't just fail though, the request makes it into the Node application where it eventually fails in the body-parser library where it can't get the whole contents of the body.  

Anyway, leaving this here for others pulling their hair out as it might point to a solution for them.

**Comment by dougwilson** [comment]
Awesome, thanks for following up!

**Comment by KayHS** [comment]
@johnennewdeeson I am experiencing the same problem now. So what was the solution for you guys?

My experience is that requests made individually around 7mb in size will go through.

However im running a performance tests (10 requests concurrently) and i get this error. 

> BadRequestError: request aborted at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10) at IncomingMessage.emit (events.js:189:13) at abortIncoming (_http_server.js:449:9) at socketOnClose (_http_server.js:442:3) at Socket.emit (events.js:194:15) at TCP._handle.close (net.js:600:12)
