### ISSUE TITLE
Front end document with nested objects 

### ISSUE THREAD

**Issue by nicolas15000** [expressjs/body-parser#364]
Hello,

This is my Frontend , the club document contains nested object 
`$http.post('http://localhost:3000/updateClub',club, {headers: {'Content-Type': 'application/json'} })`

Changed my node.js back end code to this :

```
const jsonParser = bodyParser.json()
app.use(bodyParser.json({
    inflate: true,
    strict:false
}));
```

The Json parser still doesn't parse my club nested objects, so i can't update , this is a console.log(req.body) example,please notice [Object] instead of the real data :

adresse:

```
 { address_components:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     adr_address:

```

This is my back end, the update fails because the json parser doesn't parse the nested objects

```
app.post('/updateClub', function (req, res) {
	
	console.log(req.body); // Can see the object in the console with some [object] instead of the realdata !

	myClub = req.body;

	
	MongoClient.connect('mongodb://localhost:27017', { useNewUrlParser: true }, (err, client) => {
		
		var x = myClub._id;
		 if (err) throw err;
		var db = client.db('myDb');
		// db.collection('clubs').insert( myClub )
		try {
		db.collection('clubs').replaceOne({"_id":myClub._id},myClub)
		} catch (e){
		   print(e);
		}
	})
})
```

Pleas help me, i've got 25 clubs in my mongoDb Db, the import with Studio 3 t has worked well.

**Comment by dougwilson** [comment]
By default, the Node.js `console.log` only shows to a depth of 2. Example:
```
$ node -e 'console.log([{ address_components: [ {foo: "bar"}, {fizz: "buzz"} ] }])'
[ { address_components: [ [Object], [Object] ] } ]
```

**Comment by nicolas15000** [comment]
Wow thanks, but  do you have any idea why db.collection('clubs').replaceOne({"_id":myClub._id},myClub) fails silently ?

**Comment by dougwilson** [comment]
You can have Node.js print the entire object using `console.dir` instead with `Infinity` set for the `depth`:
```js
console.dir(req.body, { depth: Indinify })
```

As far why that fails, I really think that is beyond this module. If you use the `console.dir` method and do see all your data, then you may need to seek help from the mongo folks.

**Comment by nicolas15000** [comment]
Thanks a lot !

**Comment by nicolas15000** [comment]
**EDIT 9 : SEMI SOLVED**

I ended  up with this code, but i dont think it's the best thing to do, ive  added a second identifier who was coming from my old bdd, so i use it as a filter, and delete the mongoDb generated _id who was generating an error, then the replace is working:

  

     ```
 app.post('/updateClub', function (req, res) {
        	
        
        	myClub = req.body;
        
        	delete myClub._id;
        
        	MongoClient.connect('mongodb://localhost:27017', { useNewUrlParser: true }, (err, client) => {
        		
        		
        		if (err) throw err;
        		var db = client.db('myDb');
        		
        		try {
        		db.collection('clubs').replaceOne({"identifiant":myClub.identifiant},myClub)
        		} catch (e){
        		   print(e);
        		}
        	})
        })
```

**Comment by nicolas15000** [comment]
Ok i've found an explanation there :
https://litote.org/kmongo/dokka/kmongo/org.litote.kmongo/com.mongodb.client.-mongo-collection/replace-one-with-filter.html

Well, I need to use _id to be able to replace one, it 's more convenient.

**Comment by nicolas15000** [comment]
Added delete myClub._id; !Please take a look it is so WEIRD ; I really dont understand why i have to do that but it is logical , cause the object still contains the _id !

```
const express = require('express')
    const app = express()
    var mongodb = require('mongodb');
    const { MongoClient, ObjectID } = require('mongodb');
    var url ="mongodb://localhost:27017"

    app.post('/updateClub', function (req, res) {


        myClub = req.body;


        MongoClient.connect(url, { useNewUrlParser: true }, (err, client) => {


            var db = client.db('myDb');

            var ObjectId = require('mongodb').ObjectID; //working
            var idObj = ObjectId(myClub._id); //working
            typeof(idObj); // Nothing on screen
            delete myClub._id;
            try {
            db.collection('clubs').replaceOne({'_id':idObj},myClub)
            } catch (e){
               console.log(e);
            }
        })
    })
```

**Comment by dougwilson** [comment]
I'm not familiar with mongo stuff unfortunately.
