### ISSUE TITLE
body parser not correctly detecting request body when received through Ambassador API Gateway

### ISSUE THREAD

**Issue by digressionary** [expressjs/body-parser#365]
I have a very simple express app running in a Kubernetes ecosystem.  All requests go first to an Ambassador API gateway, and then through that directly to an express app.

My ecosystem:
  node: 10.16.0
  express: 4.17.1
  body-parser: 1.19.0
  concat-stream: 2.0.0
  Docker: 19.03
  Kubernetes: 1.14.1
  Ambassador API Gateway: 0.72.0

Here is the app:
https://gist.githubusercontent.com/digressionary/86c48ccf89fc210d05ae5e76d8390b7d/raw/fa66d729927ce594ee146cf444b168eec170fc32/index.js

Here is the request:
```curl -X POST \
  http://localhost/example/ \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: a00e1ecc-c567-4df1-94ee-c2d39c6618e8' \
  -H 'cache-control: no-cache' \
  -d '{"username":"redacted","password":"redacted"}'
```

When I use a debugging tool to see the request coming out of Ambassador and into the express app, it looks like this:

```Request served by echo-deployment-b6b6878c-7vmnh

HTTP/1.1 POST /example/

Host: localhost
Content-Length: 45
X-Forwarded-For: 192.168.65.3
X-Envoy-Internal: true
Accept: */*
Accept-Encoding: gzip, deflate
X-Envoy-Expected-Rq-Timeout-Ms: 3000
Content-Type: application/json
X-Forwarded-Proto: http
X-Request-Id: 72329b5e-37cd-46e4-9d5f-d4eebc7a4de3
X-Envoy-Original-Path: /example/
Cache-Control: no-cache
Postman-Token: fb6df4bc-b8af-4b51-b3bd-5d60a5127a60
User-Agent: PostmanRuntime/7.6.0

{"username":"redacted","password":"redacted"}
```
However, when I look at the console.log of the express app, it says that the req.body parameter is an empty object.

I adjusted the Express app to use a home-grown body parser:
https://gist.githubusercontent.com/digressionary/8898b55177ee5a1a8ebd0d143b3ee0c8/raw/b540d9e522ffd48d98896ea201795b11f64543db/index.js

With this change, req.body is populated with a JSON object.

I suspect this is a very low-level encoding/decoding anomaly, and I'm cross-posting it for the Ambassador folks as well.

**Comment by dougwilson** [comment]
https://github.com/expressjs/express/issues/3990#issuecomment-504054239

> Hi @digressionary please don't cross post this in multiple repos of ours, as that just creates noise and disjoined discussions.

I am adding a temp block for you to our org so you have time to get this message before opening yet another issue, as it doesn't seem like you got my quick response before posting this one.

**Comment by dougwilson** [comment]
So this issue has more information, and the request you are using coming out of Ambassador is missing the `Content-Type` header, which is why you're getting `req.body` as `{}`. Per the readme:

> All middlewares will populate the req.body property with [...] an empty object ({}) if [...] the Content-Type was not matched [...].

Without any content-type header, the content-type will never match the configured `application/json` type of the `bodyPraser.json()` used in your example app.

If you want it to parse _all_ requests, regardless of the `content-type` header like your second app does, you have specific a function for the `type` option: `bodyParser.json({ type: () => true })`
