### ISSUE TITLE
Body-parser parse JSON with array as a string.

### ISSUE THREAD

**Issue by lukaswilkeer** [expressjs/body-parser#367]
When receiving JSON with array objects the body-parser interprets as a string.

Ex:
```
console.log(typeof 'req.body.itens') is a String not an Array
```
so 
```
const intes = req.body.itens
req.body.itens.map(fn)

```
is
```
results on a TypeError: req.body.itens.map is not a function
```

Is interpreted as:
```
{ user: 'tobi', itens: "[1,2,3]"}
```

When change the POST data of test/json.js 'should parse json' scenario case to:
 ```
'{"user":"tobi", "itens": [1, 2, 3]}'
```

they return an error.

![erorMessage](https://user-images.githubusercontent.com/1809628/62548513-4e702900-b83d-11e9-9c2a-0beb1603b6ad.png)

I expect to treat JSON with arrays as an Array, without need to convert or parse the string.

**Notes** 

- urlencoded is set to true.
- body-parser version: 1.18.3

**Comment by wesleytodd** [comment]
Hi @lukaswilkeer, can you post examples of the request you are sending?

**Comment by lukaswilkeer** [comment]
Updated the info needed to clarify the problem I had.

**Comment by dougwilson** [comment]
Thanks for updating, @lukaswilkeer . There still is not enough information; the screenshot you showed is showing the exact behavior you wanted -- that the `[1,2,3]` is parsed as an array of ints and not as a string (it would be surrounded in `"` on the right-hand side if it was a string).

**Comment by lukaswilkeer** [comment]
HI @dougwilson. There's a mistake on my question. I updated the test scenario to give the write answer, ant't no response.

Test scenario:
`  it.only('should parse JSON', function (done) {
    request(createServer())
      .post('/')
      .set('Content-Type', 'application/json')
      .send('{"user":"tobi", "itens": [1, 2, 3]}')
      .expect(200, '{"user":"tobi", "itens": [1, 2, 3]}', done)
  })
`

Response are the same.

**Comment by dougwilson** [comment]
There still is not enough information; the code you just gace is showing the exact behavior you wanted -- that the [1, 2, 3] is parsed as an array of ints and not as a string (it would be surrounded in " in the expect if it were a string).

**Comment by dougwilson** [comment]
Maybe to make it easier, here is a better self-contained test that uses this module in a real context (express) and may be better to understand since it will show `req.body` directly:
```js
var bodyParser = require('./index')
var express = require('express')
var http = require('http')

var app = express()

app.use(bodyParser.json())

app.post('/', function (req, res) {
  console.log(req.body)
  console.log('type of req.body: %s', typeof req.body)
  console.log('type of req.body.itens: %s', typeof req.body.itens)
  console.log('is req.body.itens an array?: %s', Array.isArray(req.body.itens))
  console.log('type of first array element: %s', typeof req.body.itens[0])
  res.end()
})

var server = app.listen(3000, function () {
  http
    .request({
      headers: {
        'content-type': 'application/json'
      },
      host: '127.0.0.1',
      method: 'POST',
      port: 3000
    })
    .end('{"user":"tobi", "itens": [1, 2, 3]}')
    .on('close', function () {
      server.close()
    })
})
```


And then running that produces the following:
```
$ node test.js
{ user: 'tobi', itens: [ 1, 2, 3 ] }
type of req.body: object
type of req.body.itens: object
is req.body.itens an array?: true
type of first array element: number
```
