### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by kirillgroshkov** [expressjs/body-parser#368]
Related to: https://github.com/expressjs/body-parser/issues/329

We want to have control over timeout of `body-parser`, to give it some limited time to receive the request body, or fail with a timeout. Right now there's no way/option to do that. Or am I missing something?

**Comment by dougwilson** [comment]
Right now it just inherits the timeout for a request set on your Node.js server module.exports.default

**Comment by dougwilson** [comment]
Duplicate of #207
