### ISSUE TITLE
Introduce YAML Input Format

### ISSUE THREAD

**Issue by mykiimike** [expressjs/body-parser#369]
Hello,

It would be nice to have **YAML support** in body-parser supporting input mimes like : 
* text/yaml
* text/x-yaml
* application/yaml
* application/x-yaml

All the best

**Comment by wesleytodd** [comment]
Interesting ask.  I have not seen any discussion about http api's accepting yaml.  Can you point to some examples?

**Comment by mykiimike** [comment]
I do not have an example for input data. But some APIs respond in YAML.

In my case, I would liked the support of YAML input to avoid a stupid operation (YAML> JSON) that I do to read sent YAML configurations.

So, I added the YAML support with an express.use() to avoid doing this translation.

I thought it could be interesting for body-parser

**Comment by dougwilson** [comment]
Since there is no straight forward way to convert a YAML text into a JavaScript object, it becomes very opinionated for there to be a way to add it here. The best would be to use to text parser and then use one of the many YAML parsers and settings combinations that works best for your application to parse req.body.

**Comment by mykiimike** [comment]
Okay up to you. To me, i have no issue to convert YAML to JSON but that could add a dep to this project.

all the best

**Comment by wesleytodd** [comment]
While I agree that there is not simple *single* configuration, if we did want to add this someday we could probably just use the default settings of [`js-yaml`](https://www.npmjs.com/package/js-yaml).

I will close this for now, as I do not think this is a common requirement (as most api's are json), but if anyone wants to follow up this topic we can re-open.
