### ISSUE TITLE
JSON request returns empty body object

### ISSUE THREAD

**Issue by Tedowski** [expressjs/body-parser#371]
This is my first time using express and body-parser so consider me an amateur.

Put simply, JSON POST request returns empty body object. Only x-www-ulrencoded works and returns desired output.
None of the solutions anywhere seem to help me, but I am pretty sure it's just me missing something.

### package.json
```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "./node_modules/nodemon/bin/nodemon.js src/app.js --exec 'npm run lint && node'",
    "lint": "eslint \"**/*.js\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "morgan": "^1.9.1",
    "nodemon": "^1.19.2"
  },
  "devDependencies": {
    "eslint": "^6.3.0",
    "eslint-plugin-vue": "^5.2.3"
  }
}
```
### app.js file
```js
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors'); 
const morgan = require('morgan');

const app = express();

app.use(morgan('combined'));
// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))
// parse application/json
app.use(bodyParser.json({
    type: 'application/json'
}))
app.use(cors());

app.post('/register', (req, res) => {
    res.send({
        message: `Hello ${req.body.email}! You have been registered succesfully`
    })
});

app.listen(8081);
```

**Comment by dougwilson** [comment]
Hi @Tedowski sorry you are having issues. This quote near the top of the readme may be relevant to your situation:

> All middlewares will populate the req.body property with [...] an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.

Is it possible you can show here what the complete request looks like that you are sending, complete with all the headers, etc?

**Comment by wesleytodd** [comment]
One thing you could do is use `res.json` instead of `res.send`.  But in order to know for sure you should also provide an example request (a curl command would work).

**Comment by Tedowski** [comment]
Thanks for the quick reply all of you @dougwilson @wesleytodd. Could I get a how-to so I could provide you with more relevant info? I never used a curl command before. Although I am simply testing the backend with Postman

**Comment by dougwilson** [comment]
If you are using Postman, perhaps just a screenshot of your Postman configuration for the request will be enough to get all the information. In fact, I think when you click to send in Postman, there is a tab to see the request it sent, which should have all the information we need.

**Comment by Tedowski** [comment]
Ok so I added headers to the post request in Postman where I specified 'Content-type' 'application/json' and it indeed worked as intended. 

Now it is obvious I am not sending proper headers from my axios POST request, which is not body-parser related.

Thanks for the help anyways 

![Screenshot 2019-09-05 at 20 16 32](https://user-images.githubusercontent.com/26543624/64368290-452fd300-d01a-11e9-982d-9e9f14f6454e.png)

**Comment by wesleytodd** [comment]
@Tedowski, glad you got it worked out.  Just so you know, postman can export in many formats.  On the right near the top there is a link `code`.  If you click that you can copy the request you make in postman in many different formats, including `curl`.  Hope that helps!
