### ISSUE TITLE
OOM on node 10 while using body-parser 1.19.0

### ISSUE THREAD

**Issue by moshevi** [expressjs/body-parser#375]
I'm getting an OOM exception on my node production server, this is my relevant error stack:
```
Security context: 0x31199cd9e6e9 <JSObject>
1: exec [0x31199cd89239](this=0x3b5bb1b22481 <JSRegExp <String[23]: ^[\x20\x09\x0a\x0d]*(.)>>,0x348a25f69489 <Very long string[829959]>)
2: parse(aka parse) [0xb999deff909] [/app/node_modules/body-parser/lib/types/json.js:~71] [pc=0x8bc8ce93f76](this=0x14d5a66826f1 <undefined>,body=0x348a25f69489 <Very long string[829959]>)
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
This is how I use my bodyParser object:
```js
const bodyParser = require('body-parser');
app.use(bodyParser.json({limit: '10mb'}));
app.use(bodyParser.urlencoded({extended: true, limit: '10mb'}));
```
Do you have a clue why is it exploding? Is it a memory leak on node/V8/body-parser ?
Maybe it's because 10mb is a buffer to big to accommodate a single post body request while there's a lot of these happening simultaneously?

Thanks.

**Comment by dougwilson** [comment]
It's hard to say off hand, especially an OOM without a heapdump provided at the time of the exception to see what was in the memory. Is it possible to provide a reproduction case? We can help debug what the issue is and then what component is the cause.

**Comment by moshevi** [comment]
Hey @dougwilson .
It will take some time to get that...
In the meantime, can you asses according to my inputs (Failing on JSON.parse on body-parser module, my request body here is 829959 length) ?
Any comments regarding my assumptions on the 10mb limit?
Thanks.

**Comment by dougwilson** [comment]
I routinely use this module on approx 20 mb bodies without an issue. Our test suite also tests large bodies around the size of your example without issue.

But it's always possible the content of the body itself matters, so if you can provide the specific body that causes that error, that would be probably the next step for me to be able to test further.l, as I have already tested with just the length you provided without issue.
