### ISSUE TITLE
Modify error format

### ISSUE THREAD

**Issue by HopefulLlama** [expressjs/body-parser#377]
Currently it seems that there isn't any way to customize the format or the message returned in an error case from body-parser. It'd be nice if this was possible through passing options to the body-parser.

**Comment by dougwilson** [comment]
Can you give an example for what type of modification you want to do any why you cannot do it in an express error handler?

**Comment by HopefulLlama** [comment]
Sure, I guess there are a few parts to this which I'll try to address one by one.

**What type of modification?**
The current behaviour is to return any errors or exceptions as a response with status `400` and `Content-Type: text/html`.

It would be great if I were able to pass an option to simply specify that instead of HTML, I'd like some form of plain text which is more suitable for a RESTful API. 

In addition, it would also be useful (but less important) to add a prefix or suffix to the exception.

**Why you cannot do it in an Express error handler?**

While most of it should be possible, it would still be nice to have this available through options or APIs to simplify simple changes such as just the Content-Type. 

Other than that, there's no formal documentation on how to handle errors. For example, currently I am making use of `console.log` in the error handler, to determine what information I have available. 

Also, it seems like in the error handler, I have lost most of the information regarding the actual error itself. I may possibly be looking in the wrong places, but it seems that the only information I have is `error.type: "entity.parse.failed"`, whereas with the default behaviour, the original stack trace is sent as a response. This information would also be useful, in an Express error handler, but seems to have been lost.

**Comment by dougwilson** [comment]
> The current behaviour is to return any errors or exceptions as a response with status 400 and Content-Type: text/html.

So this module would not be the place to modify this behavior, as this module never writes a response at all; it simply returns an error objects which doesn't include anything about what content type to use.

> Other than that, there's no formal documentation on how to handle errors. For example, currently I am making use of console.log in the error handler, to determine what information I have available.

> Also, it seems like in the error handler, I have lost most of the information regarding the actual error itself. I may possibly be looking in the wrong places, but it seems that the only information I have is error.type: "entity.parse.failed", whereas with the default behaviour, the original stack trace is sent as a response. This information would also be useful, in an Express error handler, but seems to have been lost.

The Error object contains everything that is in the response, as this module is not producing the html reaponse you are seeing; that is being done by express itself, outside of this middleware. This module creates JavaScript Error objects and the stack track is always at error.stack property, for example. 

I'm not sure what you mean here. Like is there not enough information about what properties are on the Error objects this module produces at https://github.com/expressjs/body-parser/blob/master/README.md#errors ?

**Comment by HopefulLlama** [comment]
Ah, I was mistaken. I didn't realise Express would response with errors. That's my bad.

I was also mistaken in that, from the documentation, I did not realise that these `Error` objects, are the original errors with additional properties added on. It seemed like there were simply objects that had the mentioned properties, and nothing else. 

It seems that in this case, I'm happy for this issue to be closed as mostly a misunderstanding on my part.

**Comment by HopefulLlama** [comment]
Oh, thank you for the quick and insightful replies!
