### ISSUE TITLE
Parser removes numeric object keys smaller than 100

### ISSUE THREAD

**Issue by Acr0most** [expressjs/body-parser#381]
Hey there,

i've got some strange behavior in parsing body that contains an object with numeric properties.
When i parse sth. like
```json
{
    "payload": {
        "templates": {
            "29": "my text template"
        }
    }
}
```

it will return only

```json
{"payload": { "template": ["my text template" ]}}
```

after some testing szenario i knew it depends on the key in the templates-object. When the key is 101 or greater it the parsed body also has an object including key and value.

Someone else have had this issue? 

Using body-parser v.1.19.0

**Comment by dougwilson** [comment]
Hi, thanks for the report. Can you post which parser you are using and the options you have set for it?

**Comment by Acr0most** [comment]
Hi,

after creating a new express test app in node and also in typescript, i can not reproduce the behavior. Very strange. 
At the moment i cannot say if the bug is somewhere else in my code or in express (or bodyparser).

I will check this tomorrow again and reply when i found a solution.

**Comment by HarshithaKP** [comment]
@Acr0most Is this issue still appearing for you ?

**Comment by Acr0most** [comment]
@HarshithaKP Hey - no I fixed it. But it wasn't an error in the body parser lib.
