### ISSUE TITLE
Converting datatype of ids in payload (string to integers)

### ISSUE THREAD

**Issue by AhmadRaza786** [expressjs/body-parser#382]
I am using body-parser with loopback. I need to hit my api endpoint from any third party source. that third party source is sending a payload that i am getting in body as `req.body`. But the problem is that there are some ids in payload. 3rd party source sending those ids as strings but I am getting these Ids as numbers. Its converting the Ids from string to numbers like `parseInt()` thats why, it is changing the value as well. like 
3rd party sending the 
```
{
  "subscription_id": "2011068000000264609"
}
```
But I am getting in req.body as 
```
{
  "subscription_id": 2011068000000264700
}
```
How can i resolve this issue ?

**Comment by dougwilson** [comment]
I don't seem to be able to reproduce the issue with body parser. Can you provide the following information please?

1. Version of node.js this module and any other you are using.
2. Complete code that I can copy and paste and run without any modification to see the issue.
3. Complete instructions on how to run the above code and exactly how to replicate the issue.

Thank you.

**Comment by AhmadRaza786** [comment]
@dougwilson 
1. Node.js version => 6.0.0 , body-parser version => 1.18.2 , loopback version => 2.38.3
2. ```
    PricingModal.remoteMethod('autoSync', {
        http: { path: '/autoSync/', verb: 'post' },
        accepts: [
            { arg: 'req', type: 'object', http: { source: 'req' } }
        ],
        returns: { arg: 'data', type: 'object', root: true },
        description: 'auto sync data'
    });

    PricingModal.autoSync = async (req: any) => {
        console.log(req.body)  //logged value { "subscription_id": 2011068000000264700 }
    }

3. Just create an endpoint like above code and hit this endpoint containing body as
```
    { "subscription_id": "2011068000000264609" }

**Comment by dougwilson** [comment]
Thanks for the response. Your code does not run when I copy and pasted it and doesn't even use this module anywhere. If you can provide complete code that I can copy and paste and run without any modification to see the issue I can reopen this issue.
