### ISSUE TITLE
About a spanish translation

### ISSUE THREAD

**Issue by LautaroJayat** [expressjs/body-parser#388]
I would like to make a contribution to the project making a spanish translation of the README.md file, but I dont know if that is the work of the ExpressJS team.

As the [expressjs.com repo](https://github.com/expressjs/expressjs.com/blob/gh-pages/CONTRIBUTING.md#contributing-translations) says:

> 
> ## Contributing translations
> **IMPORTANT**: We have professional translations of the Express documentation into:
> 
> - German
> - French
> - Italian
> - Spanish
>  - Brazilian Portuguese
> - Japanese
> - Simplified Chinese
> - Traditional Chinese
> - Russian
> - Korean
> 
> Therefore we can no longer accept community translations for these languages, except for corrections to the existing translations and updates to align with changes or additions to the English documentation.
> 

Please let me know if there is no problem. I would be glad to contribute.

**Comment by dougwilson** [comment]
Hello! I believe you may have accidentally opened this on the wrong repo; code repos just have a single readme in english only. Translations of various items would go onto the expressjs.com site directly. If you want to translate body-parser then it would still go there, as the site hosts the body-parser docs :+1:
