### ISSUE TITLE
HTTP errors for invalid JSON payload

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [expressjs/body-parser#391]
Since `body-parser` sets response status code on certain conditions when the headers don't meet exceptations, wouldn't it be good if it set `400` (`Bad request`)  if there is a JSON parse error? Right now `body-parser` throws and it will end up as `500` (`Internal server error`) unless manually caught and handled in an express application.

If this proposal sounds good, we're voluntary to create a PR for this. Since this would be a breaking change I'd propose a new configuration option `handleSyntaxErrror` and then in a new major version (If any) this functionality could be made default.

**Comment by dougwilson** [comment]
Using the example app in the README you can see it already provides a 400 response. If you can provide a reproduction case to show it doing a 500 we can run, we can look into it.

**Comment by dougwilson** [comment]
Here are the tests we have if it helps: https://github.com/expressjs/body-parser/blob/968995bfef5ae42084c6ece65f3aa20bb0a3d6f6/test/json.js#L72

**Comment by natlibfi-arlehiko** [comment]
We have a custom error handler which didn't consider the error created using `http-errors`. Although I don't really understand how it works without a custom error handler since Express' docs don't specify that errors with `status` and `message` are interpreted.

**Comment by dougwilson** [comment]
> We have a custom error handler which didn't consider the error created using http-errors.

Ah. Please let us know if/how we can improve our documentation around errors https://github.com/expressjs/body-parser/blob/master/README.md#errors

> Although I don't really understand how it works without a custom error handler since Express' docs don't specify that errors with status and message are interpreted.

If there is something missing in the Express documentation, please report (and perhaps contribute to resolving) the issue at https://github.com/expressjs/expressjs.com
