### ISSUE TITLE
bodyParser.raw blocking Node event loop

### ISSUE THREAD

**Issue by logidelic** [expressjs/body-parser#393]
Hey all,

I've recently been obsessing about what causes blocking in some of my node servers, and have been trying to find and fix all the causes. One thing I've seen sporadically, in all of my servers, is that _sometimes_, but not always, `bodyparser.raw` inexplicably blocks for a bit. To try to narrow it down I did something like:

```
var parserRaw  = bodyParser.raw({limit:...});

app.use((req, res, next) => {
        debug('raw-beg');
        parserRaw(req, res, () => {
            debug('raw-end');
            next();
        });
    });
});
```

As a random example of what I'm seeing:

- Body size is ~71KB
- `Content-type` is `application/octet-stream`
- No `Content-encoding`
- Blocks the server (once in a blue moon only) for ~200ms
 - Node v12.16.1 , body-parser 1.19.0

Obviously the raw body parser isn't (shouldn't be) doing anything cpu-intensive, so this is kind of mind-boggling. Has anyone seen anything similar? 

I wonder if it's somehow a variation of what is described [here](https://github.com/nodejs/node/issues/31953), but then again, that could only really happen if the socket's `data` handler, were doing something at least slightly interesting and in this case it's just appending a buffer...

**Comment by dougwilson** [comment]
Thanks for the report! I really have no leads on what could be doing it, unless there is some underlying issue in Node.js itself that is causing it?

Do you have any suggested changes to make in this module or a reliable way to reproduce the issue in order for one of us to diagnose?

**Comment by logidelic** [comment]
I'm planning to do some debugging in the module itself to see if I can spot the exact cause, but until then I thought I'd post just in case someone else knew something. :)

I'll post again when I have time to investigated further.

Thanks!

**Comment by dougwilson** [comment]
Sounds good. It sounds like there isn't any action we can take here, including investigation with a lack of that reproduction steps. I'm going to close this for the time being, but can always re-open when enough information becomes available where someone from this project or elsewhere can pick this up given the information in the ticket.

**Comment by dougwilson** [comment]
Just thinking about it, it could even be possible that the append to Buffer operation could be causing it? Like maybe it sometimes needs to move a bunch of memory around i the middle of the sync append operation? Just pulling at strings 😄 for some ideas

**Comment by logidelic** [comment]
Yep, I was wondering the exact same thing. I will test the theory when I find the time.
