### ISSUE TITLE
limit设置没有生效？

### ISSUE THREAD

**Issue by Hugohui** [expressjs/body-parser#395]
app.use(bodyParser.json({limit: '100000kb'})); // for parsing application/json
app.use(bodyParser.urlencoded({extended: true,limit: '100000kb'})); // for parsing application/x-www-form-urlencoded

**Comment by wesleytodd** [comment]
Hi @Hugohui, I think we need a bit more info, can you explain more the behavior you are seeing?

For others like me who do not read Chinese (as detected by google translate), the title is "limit setting does not take effect" (as translated by google translate).

**Comment by Hugohui** [comment]
Thank you very much. The problem is solved.
Express service is deployed in k8s, which is k8s limit,not express!
