### ISSUE TITLE
Empty request body

### ISSUE THREAD

**Issue by CalebDelbridge** [expressjs/body-parser#408]
### Information
body-parser: v1.19.0
express: v4.17.1

### Expected Result 
For `body-parser` to parse the json data correctly and for the body to be readable

#### server.js
```
const express = require('express');
const path = require('path');
const cors = require('cors');
const bodyParser = require('body-parser');

const app = express();

app.use(bodyParser.json());

app.use(cors());
app.get('(offline.html|.js|.css)', (req, res, next) => {
  if (req.get('Accept-Encoding').includes('br')) {
    req.url += '.br';
    res.set('Content-Encoding', 'br');
    next();
  } else {
    req.url += '.gz';
    res.set('Content-Encoding', 'gzip');
    next();
  }
});
app.use(express.static(path.join(__dirname, '../dist')));
app.get('/', (req, res) => {
  res.sendFile(path.join(path.join(__dirname, '../dist'), 'index.html'));
});
app.post('/api/test', (req, res) => {
  res.send(`Got the info ${req.body.email}`);
});
app.listen(3000, () => {
  console.log('listening on 3000');
});
```

### Postman Config
![](https://cdn.discordapp.com/attachments/730550740174766082/736775716728864768/Screen_Shot_2020-07-25_at_10.43.35_PM.png)

![](https://cdn.discordapp.com/attachments/730550740174766082/736775748920279040/Screen_Shot_2020-07-25_at_10.43.44_PM.png)

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble @CalebDelbridge . I am not the most familiar with Postman, but I installed it and used the same app you provided as well as the same config shown in the Postman screenshots and it is working just as expected:
![image](https://user-images.githubusercontent.com/67512/88470538-90213600-cecb-11ea-82ba-529fff05b733.png)

**Comment by CalebDelbridge** [comment]
How strange well I'll keep trying to see if I get any different results

**Comment by CalebDelbridge** [comment]
Seems to be working now must of been a small issue with the postman config thank you for your reply @dougwilson
