### ISSUE TITLE
Request.body is empty

### ISSUE THREAD

**Issue by hydroper** [expressjs/body-parser#409]
**body-parser version:** 1.19.0

I inject the following into my endpoint:

```javascript
bodyParser.urlencoded({ extended: true });
```

I send an axios request like this:

```javascript
axios.post(url, new FormData, {
    responseType: 'json',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
});
```
![image](https://user-images.githubusercontent.com/52384977/90345014-9b601100-dff4-11ea-9be2-eacd199ba2b6.png)

`console.log(request.body);` prints `{}`.

I've also tried to inject together these, but still results in empty:

```
bodyParser.text(),
bodyParser.json(),
bodyParser.raw();
```

Related sources:
- [Register](https://github.com/siteblade/starterapi/blob/master/src/controllers/Register.js)
- [com.siteblade.validation.Validator](https://github.com/siteblade/com.siteblade.validation/blob/master/index.js#L45)
- [com.siteblade.formHelpers.submitForm](https://github.com/siteblade/com.siteblade.formHelpers/blob/master/index.js#L12)

**Comment by hydroper** [comment]
Just to update, I've tried manually sending a XMLHttpRequest instead of axios. It made no difference.

**Comment by hydroper** [comment]
Not sure... Guess I'll have to make my alternative against Express.

**Comment by hydroper** [comment]
And yet yet I tried Polka instead of Express. Same thing.

**Comment by sayhicoelho** [comment]
Try to remove FormData and pass an `application/json` as Content-Type.

**Comment by hydroper** [comment]
Thanks @sayhicoelho, I ended up with using multer as you said. I don't know this repository got stars as useless as it is.

**Comment by hydroper** [comment]
Issue not resolved with body-parser, resolved with multer, so it can't be closed.

**Comment by dougwilson** [comment]
Hi @hydroper sorry if there is confusion; `body-parser` module supports various types of bodies as noted in the readme, but it does not support multipart bodies. There are modules that _only_ support multipart bodies, of which `multer` is one of. Both of these middlwares are part of Express.js organization because they offer _different_ things. If you think the readme can be clearer, we're happy to help. Here is the except at the top of the readme:

> This does not handle multipart bodies, due to their complex and typically large nature. For multipart bodies, you may be interested in the following modules:
> 
> busboy and connect-busboy
> multiparty and connect-multiparty
> formidable
> multer
