### ISSUE TITLE
empty body from POST data

### ISSUE THREAD

**Issue by bigalnz** [expressjs/body-parser#413]
I am trying to access some post data that is sent like so:

POST {
  host: '192.168.78.243:3000',
  accept: '*/*',
  'content-length': '1178',
  'content-type': 'multipart/form-data; boundary=------------------------f519f81dc2e1d562'
}
--------------------------f519f81dc2e1d562
Content-Disposition: form-data; name="event"; filename="event_3913.json"
Content-Type: application/octet-stream

{"packetCounter":"3913",
"capture_timestamp":"1600677267347",
"datetime":"20200921 204027000",
"stateUTF8":"ABC123",
"stateASCII":"ABC123",
.....

If I access this data with a simple http, chunk and concat routine I can see the data:

let buffers = [];
const http =require('http')
http.createServer((request, response) => {
    console.log('Now we have a http message with headers but no data yet.');
    if (request.method === 'POST' && request.url === '/test') {
        console.log('Hit');
    }
    request.on('data', chunk => {
        console.log('A chunk of data has arrived: ', chunk);
        buffers.push(chunk);
    });
    request.on('end', () => {
        console.log('No more data');
        let body = Buffer.concat(buffers);
        console.log(String(body));
    })
}).listen(3000)

If I try to access this data using body-parser I get a empty body:

const express = require('express');
const bodyParser = require('body-parser');

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.use(express.static('public'));

app.get('/', (req, res) => {
    res.sendFile('public/index.html');
});

app.post('/test', (req, res) =>{
    if (req.method === 'POST') {
        console.log('post ip', req.ip);
        console.log('post params', req.params);
        console.log('post bodyused', req.bodyUsed);
    }
    console.log(req.body);
    res.status(200).send('It works');
});

app.listen(3000, () => console.log('server started'));

I am unsure if this is a bug, to do with the data or my approach.

**Comment by dougwilson** [comment]
Hi! This module does not support multipart bodies, as notes at the top of the readme. You will need to use one of those listed module to parse that particular type of body.
