### ISSUE TITLE
JSON parser fails silently when content header type missing

### ISSUE THREAD

**Issue by mhamas** [expressjs/body-parser#415]
My assumption was that when `application/json` content header is missing, the body parser throws an error when json body is provided. However, this is not so and the parser just continues silently, setting the body to an empty object.

This is where it continues silently: https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L119

Is this a bug or a feature? Seems like a bug to me.

**Comment by dougwilson** [comment]
Hi! No, this is not a bug, as it is critical in accepting multiple different types for the same endpoint. It is documented in the README:

> All middlewares will populate the req.body property with the parsed body when the Content-Type request header matches the type option, or an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.
