### ISSUE TITLE
req.body is empty on POST/JSON query

### ISSUE THREAD

**Issue by sandro971** [expressjs/body-parser#420]
Hello
I don't know if it's a bug, security fail or a mistake but, when a i make a post/JSON request, my extension can't read req.body fields.

my request parser :
```js
const bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))`

my ajax code : 

`var fdata = new FormData()
fdata.append('avatar60', blob60)
fdata.append('avatar400', blob400)

$.ajax({
	type: 'POST',
	url: '/settings/account/avatar/send',
	data: fdata,
	xhr: function() {
		var myXhr = $.ajaxSettings.xhr();
		return myXhr;
	},
	processData: false, 
	contentType: false, 
	cache: false,
	dataType: 'json'
})
.done(function(res){
	location.reload()								
})
```

Thanks ! 👍

**Comment by dougwilson** [comment]
Hi @sandro971 your example ajax code is sending a multipart request, which this module does not support. You can see a few different middlewares you can use to parse those kinds of requests at the top of the readme 👍
