### ISSUE TITLE
PayloadTooLargeError: request entity too large for anything above 10MB.

### ISSUE THREAD

**Issue by sstamoulas** [expressjs/body-parser#421]
I ran into the same issue. PayloadTooLargeError: request entity too large. For anything above 10MB. Because I am working with `firebase functions` I must use `busboy`. `Multer` is not recommended to use with `firebase functions`.

    app.use(bodyParser.json({ limit: '1gb' }));
    app.use(bodyParser.raw({ limit: '1gb' })); 
    app.use(bodyParser.urlencoded({
      limit: '1gb',
      extended: true,
    }));

_Originally posted by @sstamoulas in https://github.com/expressjs/body-parser/issues/400#issuecomment-767856557_

**Comment by dougwilson** [comment]
Hello, sorry you have having an issue. The default value for the limit in this module is not even 10MB, it is 100KB. There is likely something parsing the body with a limit of 10MB before you declared your middlewares you pasted above. If you provide the entire app with reproduction, we can trace where that is happening.

**Comment by sstamoulas** [comment]
Thanks for your quick response @dougwilson. Here is the link to the repo https://github.com/sstamoulas/british-time/blob/master/functions/index.js. 

Here is the stack trace of the error. You can run the entire repo with the command `firebase emulators:start` in the root directory.
    i  functions: Beginning execution of "api"
    >  PayloadTooLargeError: request entity too large
    >      at readStream (/usr/local/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:155:17)
    >      at getRawBody (/usr/local/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:108:12)
    >      at read (/usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/read.js:77:3)
    >      at rawParser (/usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/raw.js:81:5)
    >      at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    >      at trim_prefix (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:317:13)
    >      at /usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:284:7
    >      at Function.process_params (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:335:12)
    >      at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:275:10)
    >      at urlencodedParser (/usr/local/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/urlencoded.js:100:7)

**Comment by dougwilson** [comment]
Hi @sstamoulas thanks for that. The `firebase` command line you are using is limiting your requests to 10MB (https://github.com/firebase/firebase-tools/blob/030307c7524271f3695848354d70ae0daf6554ca/src/emulator/functionsEmulatorRuntime.ts#L826). You will either need to stop using their command line tool or open an issue with them to ask how to increase the limit.

**Comment by sstamoulas** [comment]
Thanks @dougwilson. I did more browsing and found that firebase overrides the body-parser request size limit and strictly keeps it at 10MB. Apparently, this is not editable. https://firebase.google.com/docs/functions/quotas#resource_limits.

**Comment by sstamoulas** [comment]
> Hi @sstamoulas thanks for that. The `firebase` command line you are using is limiting your requests to 10MB (https://github.com/firebase/firebase-tools/blob/030307c7524271f3695848354d70ae0daf6554ca/src/emulator/functionsEmulatorRuntime.ts#L826). You will either need to stop using their command line tool or open an issue with them to ask how to increase the limit.

Thanks @dougwilson. I did more browsing and found that firebase overrides the body-parser request size limit and strictly keeps it at 10MB. Apparently, this is not editable. https://firebase.google.com/docs/functions/quotas#resource_limits.
