### ISSUE TITLE
deprecated, but in favor of what?

### ISSUE THREAD

**Issue by ChrisMiami** [expressjs/body-parser#433]
```
// for docs go to https://github.com/expressjs/body-parser/tree/1.19.0#body-parser

/** @deprecated */
declare function bodyParser(
    options?: bodyParser.OptionsJson & bodyParser.OptionsText & bodyParser.OptionsUrlencoded,
): NextHandleFunction;
```

The TS type defs say it's deprecated but there's no mention there or here on this site about to what one is supposed to transition.

**Comment by dougwilson** [comment]
Hi @ChrisMiami we don't maintain any TS type defs. You may want to report this to whoever you are getting the defs from.
