### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by wuyang049679** [expressjs/body-parser#435]
![image](https://user-images.githubusercontent.com/20410029/116176046-08ab7080-a744-11eb-9887-b967471efd3c.png)
![image](https://user-images.githubusercontent.com/20410029/116176090-1d880400-a744-11eb-8bd9-2ddf9304cf48.png)

I can't solve this problem. I see many similar problems on Lssues, but I still haven't found a solution. help me

**Comment by dougwilson** [comment]
Hi @wuyang049679 sorry you are having trouble. Looking at the stack trace, Node.js is raising the abort event on the request, so this module just passes it though as an error. You would need to either determine why the client is aborting the request or it may be a bug in Node.js.

We can help investigate further, but you will need to explain the exact steps to replicate the issue so we can debug it.

**Comment by wuyang049679** [comment]
Thank you for your help. At the beginning, there was no error until my client introduced this library https://github.com/github/fetch The server reports this error after using the post JSON method
And the server side joined the cross domain mode
![image](https://user-images.githubusercontent.com/20410029/116181669-9b9cd880-a74d-11eb-9e27-9d449719825b.png)

**Comment by dougwilson** [comment]
Hi @wuyang049679 sorry you are still having it. Unfortunately it is Node.js that is signaling the abort, and this module is just bubbling it up. Without providing the exact code and steps to reproduce, there isn't anything for us to debug.
