### ISSUE TITLE
backslash decoding issue

### ISSUE THREAD

**Issue by alexey-shakura** [expressjs/body-parser#438]
Hi! 

I have a simple POST request with json body which I send from UI:
`{ username: 'test@email.com', password: 'k*Xs1?De23dsU-ffQx&fb\\-UE'' }`

For some reason when request arrives to server I get deserialized object:
`{ username: 'test@email.com', password: 'k*Xs1?De23dsU-ffQx&fb\\\\-UE'' }`
As you see I get **4 backslashes instead of 2.** 

My parser options are straightforward:
`this.app.use(express.json({ limit: '100kb' }));`

Why does deserialization go wrong with 2 backslashes? I don't use any special content-encoding

body-parser version `1.19.0` 
Node LTS

**Comment by dougwilson** [comment]
The parser takes the request body and passes it to `JSON.parse`. That is the jist of what the json parser does.

**Comment by alexey-shakura** [comment]
Yeah, I know about escaping backslashes, JSON.stringify will add backslash to escape `\` character. But JSON.parse should remove them, isn't it?

**Comment by alexey-shakura** [comment]
I mean the issue is that after `body-parser` I still have 4 backslashes instead of 2...

**Comment by dougwilson** [comment]
I would guess? It's hard to really see what exactly is going on in your specific situation without code to reproduce the issue. I just tried a simple test and got back the right number of backslashes.

**Comment by alexey-shakura** [comment]
yeah, sure. please checkout:

Request headers:
![Screen Shot 2021-05-27 at 7 09 54 PM](https://user-images.githubusercontent.com/14031187/119860609-2c1e3280-bf1f-11eb-9236-64cc43d32043.png)

Response headers:
![Screen Shot 2021-05-27 at 7 10 35 PM](https://user-images.githubusercontent.com/14031187/119860719-4bb55b00-bf1f-11eb-8ebe-da894cbd3f54.png)

what kind of info you also need?

**Comment by dougwilson** [comment]
I mean, ideally I would need the actual code to reproduce the issue so I could debug it. But if you want to provide the request and response, that may work, but I would need to actually see the json in it.

**Comment by alexey-shakura** [comment]
Body of request:
![Screen Shot 2021-05-27 at 7 18 21 PM](https://user-images.githubusercontent.com/14031187/119861668-52909d80-bf20-11eb-808a-25317221f716.png)

I can't publish all code because of GDPR... but `body-parser` is the first one which I pass to `app.use`. I've also put some console.log into source code of `body-parser` itself and after `JSON.parse` I see this issue. perhaps it's kind of decoding problem?

**Comment by alexey-shakura** [comment]
interesting note: when I do `JSON.stringify` and after that `JSON.parse` I see equal results (which is behavior by ECMAE spec) but for some reason when `body-parser` gets variable `body` in `getBody` callback (read.js file) JSON.parse ignores escaping backslashes and leaves them as is. I mean with inline string literal it's ok but when it decodes from stream body itsn't ok

**Comment by dougwilson** [comment]
Unfortunately that requwst body is not json (notice the lack of double quotes around the keys). If you can get the actual json that is sent to the server in the request body we can see what happens. Otherwise I need some way to reproduce the issue in order to help you by debugging it. If you cannot provide any kind of specific reproduction steps, unfortunately that leavs only you in the position to be able to debug and diagnose the issue, as I don't have anything to work with.

**Comment by alexey-shakura** [comment]
source request body:
![Screen Shot 2021-05-27 at 7 32 24 PM](https://user-images.githubusercontent.com/14031187/119863518-51607000-bf22-11eb-84af-3750969ef800.png)

**Comment by dougwilson** [comment]
Thank you. So in that body, the password key's value as two literal backslashes in it (each one is escaped with a backslash, so thus four total in the raw payload). Passing that though `JSON.parse` produces a JavaScript string with just two literal backslashes, but of course if you where to `console.log` the entire object, `console.log` will then add back two backslashes again, resulting in 4. Is this why you are seeing 4 backslahes? Does `console.log(req.body.password)` instead display the correct 2 backslashes?

**Comment by dougwilson** [comment]
This is an app I created to demonstrate:
```js
const express = require('express')
const bodyParser = require('body-parser')

const app = express()

app.use(bodyParser.json())

app.post('/', (req, res) => {
  console.log('console.log(req.body) = ')
  console.log(req.body)
  console.log('console.log(req.body.password) = ')
  console.log(req.body.password)
  res.end()
})

app.listen(3000)
```

Then you can make a request to it. For example here is using cURL with the password and backslashes:
```
$ curl http://localhost:3000 -d'{"password":"k*Xs1?De23dsU-ffQx&fb\\\\-UE"}' -H'content-type: application/json'
```

And then the server logs demonstrate the difference for how `console.log` writes the output when backslashes are involved:
```
console.log(req.body) =
{ password: 'k*Xs1?De23dsU-ffQx&fb\\\\-UE' }
console.log(req.body.password) =
k*Xs1?De23dsU-ffQx&fb\\-UE
```

**Comment by alexey-shakura** [comment]
I've added console logs + decided to check equality by comparing parsed password with inline string literal

Code:
![Screen Shot 2021-05-27 at 7 55 31 PM](https://user-images.githubusercontent.com/14031187/119866475-86ba8d00-bf25-11eb-8a58-93d8f2f6775f.png)


Logs:
![Screen Shot 2021-05-27 at 7 56 03 PM](https://user-images.githubusercontent.com/14031187/119866643-afdb1d80-bf25-11eb-868e-da2ccbcd423d.png)

**Comment by alexey-shakura** [comment]
so for some reason it logs the correct version but the string itself still contains 4 backslashes 🤔  (otherwise the comparison is true)

**Comment by dougwilson** [comment]
Hi @alexey-shakura your comparison above is incorrect, as you are only comparing to a single backslash. You can see this is type by adding `console.log("k*Xs1?De23dsU-ffQx&fb\\-UE'")` which will only log a single backslash. This is because your JavaScript string literal sees the first backslash as an escape sequence and then the second one as the item to escape, resulting in a single backslash in the actual string.

**Comment by dougwilson** [comment]
You can also use `console.log(req.password.length)` vs `console.log("k*Xs1?De23dsU-ffQx&fb\\-UE'".length)` to better visualize in your mind the difference between the raw strings. You'll notice that the `req.password.length` results in a length such that there could only be two backslashes while `"k*Xs1?De23dsU-ffQx&fb\\-UE'".length` results in a length such that there could only be one backslash.

**Comment by alexey-shakura** [comment]
@dougwilson omg, I got you, you're right. I totally missed that point...
now the issue is irrelevant, all is working fine
looks like allowing backslash for passwords is bad idea because it has special behavior by JS engine, sorry for disturbing you, perhaps you have some thoughts about it?

**Comment by dougwilson** [comment]
It's no problem, happy to help 👍 . I have never had an issue or needed to special case accepting backslashes in fields like passwords, so don't unfortunately have any tips. Asking on StackOverflow will get you a large audience with a vast knowledge base who can better when with a generic question like that, though.
