### ISSUE TITLE
Request Aborted Error in firefox

### ISSUE THREAD

**Issue by shiva-mlk** [expressjs/body-parser#439]
I want to send a form with files that upload in there to my email. it works fine in chrome but in firefox email sent without media because axios send me a Request Aborted in firefox. any one knows how can i fix it?

**Comment by dougwilson** [comment]
Hi @shiva-mlk this issue has been open for a while and it seems like there isn't anyone who happens to know. If you believe there is an issue in this module, please provide information for us to reproduce the issue and diagnose.
