### ISSUE TITLE
Reporting potential security issues is not so easy

### ISSUE THREAD

**Issue by declaresub** [expressjs/body-parser#441]
There is no email address that I can find for reporting a potential security issue in body-parser.  Suggestions?

**Comment by dougwilson** [comment]
You can find the author contacts for any module directly on npm, which is the best method as not all npm modules have a copy on github. For those that do (like ours) you can find then in the license or even the package metadata https://github.com/expressjs/body-parser/blob/480b1cfe29af19c070f4ae96e0d598c099f42a12/package.json#L6

If all else fails, you can always ask the project for contact information like you did here.
