### ISSUE TITLE
verify the request even if it has no body

### ISSUE THREAD

**Issue by soufyakoub** [expressjs/body-parser#445]
I have this simple Express app:

```node
import crypto from "crypto";
import express from "express";
import env from "env-var";

const {json, urlencoded} = express;
const app = express();

// Verify that the request came from Facebook.
function verifyRequest(req, res, buf) {
	const signature = req.headers["x-hub-signature"];
	const APP_SECRET = env.get("APP_SECRET").required().asString();
	const expectedSignature = "sha1=" + crypto.createHmac("sha1", APP_SECRET).update(buf).digest("hex");

	if (signature !== expectedSignature) {
		throw new Error("Invalid request signature.");
	}
}

app.use(json({verify: verifyRequest}));
app.use(urlencoded({verify: verifyRequest, extended: true}));

app.post("/messenger/webhook", (req, res, next) => {

	// `req.body.entry` is expected to be an array of message entries according to Facebook's docs.
	const tasks = req.body.entry.map(async (entry) => {
		// handle each entry
	});

	Promise.all(tasks)
		.then(() => res.sendStatus(200))
		.catch(next);
});

export default app;

```

I want to only accept requests from Facebook by verifying the `x-hub-signature` header, but the `verify` function is not called in this case.

I used curl to send a POST request with no body to the `/messenger/webhook` route, and I got a **500 Internal Server Error** because `req.body` is an empty object, so `req.body.entry` is `undefined`.  According to the Express docs:

> A new body object containing the parsed data is populated on the request object after the middleware (i.e. req.body), or an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.

Here's the curl command I used:

`curl -i -H "Content-Type: application/json" -X POST "localhost:3000/messenger/webhook"`

I'm not sure if this is intended or if it is a bug, but shouldn't all requests with a header of `content-type: application/json` be verified when a `verify` function is provided in the options object?

Waiting for your response.

**Comment by dougwilson** [comment]
This may be an issue with facebook, but this module is operating correctly. In HTTP a request can have a body or not. Having a body that is zero length is different from having no body at all. The content-type header does not determine if a request has a body or not, at least not according to the HTTP specification. If you wanted to send a zero length body in your example request, you would need to add content-length: 0 or send using chunked transfer encoding with a single zero length chunk.

The verify option of this module is designed to verify a body; in your example there is no body, so there is nothing to verify. A zero length body would trigger the function, as that is a valid body.

**Comment by dougwilson** [comment]
To add, the reason for your 500 error is because `req.body` is the empty object since your exame request has no body to parse.

**Comment by soufyakoub** [comment]
> The verify option of this module is designed to verify a body; in your example there is no body, so there is nothing to verify. A zero length body would trigger the function, as that is a valid body.

This is what I'm looking for. Thanks for the quick answer.
