### ISSUE TITLE
req.body could not be accessed when send as form data, but works fine with JSON

### ISSUE THREAD

**Issue by MikhilMC** [expressjs/body-parser#452]
I was testing a form of only two values in Postman. When I tried to send data as form-data, req.body is not capturing by the server. But when I tried to send by pure JSON data, only then it is accepting. I had set header Content Type as application/json. I tried looking at the postman console. In there, the content of the form data is showing. But that data could not be accessed in node.js server. Please help me with this.

**Comment by dougwilson** [comment]
Hi @MikhilMC sorry your issue was not responded to earlier. If you are still needing help, please send some screenshots of what your Postman screen looks like when it is not working and what your `body-parser` code looks like.

**Comment by dhatrishdixit** [comment]
can anyone tell me what is the issue i am still facing it
