### ISSUE TITLE
body-parser vulnerable to gzip bomb for unnecessary CPU consumption

### ISSUE THREAD

**Issue by villekurkinen** [expressjs/body-parser#454]
Request body reading in read.js always resumes the stream regardless if an error in reading the raw body was detected and 
raw-body called the callback: 

* https://github.com/expressjs/body-parser/blob/master/lib/read.js#L93

```
// read off entire request
stream.resume()
```

Problem with this is that if the request body is too large (exceeds the "limit" set to the parsers options) and raw-body 
detects it and stops reading the data and returns error ("entity.too.large") to the above callback, the whole request body gets
still read by the server. The data is silently discarded so it does not consume extra memory, but it consumes extra CPU and network resources.

Combined with transfer encoded (gzip/deflate) requests, this means that the entire request is decompressed, causing significant extra CPU load to the server (as the stream processed by raw-body works on the gunzip stream where original request is piped to).

Now, this makes Express body-parsed vulnerable to gzip bombs when request inflation is enabled:

Sending suitable crafted small gzipped request payload may decompress to tens of GBs of data. With the current implementation of body-parser's raw-body callback, this means decompressing the whole tens of GBs and thus resulting to a significant increase in CPU consumption, regardless how small "limit" is set to the body-parser. 

Locally tested by patching read.js's getBody callback like: 
    
```
    if (error.type !== 'entity.too.large') {
        stream.resume()
    } else {
      next(createError(413, _error));
      return;
    }
```

This allows server to respond e.g. in 1GB gzip bomb where input is 1MB in 0.3 secs instead of ~2 seconds in moderate setup, providing 10 x faster response times.

Worth noting that also without request inflation enabled, the body-parser reads the whole request even if configured limit has been reached and detected.

The body-parser should probably be fixed so that it does not enable input stream in case of "entity.too.large" error.

**Comment by dougwilson** [comment]
Hi @villekurkinen and thank you for your report.in the future, please report issues based on https://expressjs.com/en/advanced/best-practice-security.html .

I am removing this issue while it can be looked in to / worked on. You are welcome to email if you would like to be kept in the loop.

**Comment by dougwilson** [comment]
It looks like github does not provide a way to delete the original title, so i have to delete the issue entirely. We have received the issue, though. Please contact via email if you want to follow up on it.
