### ISSUE TITLE
 body-parser throws errors with ES6 / Babel 7 setup

### ISSUE THREAD

**Issue by Windrill** [expressjs/body-parser#456]
depd throws an error with Babel 7 setup
```
index.js:252
  var file = callSite.getFileName() || '<anonymous>'
                      ^

TypeError: callSite.getFileName is not a function
```

The bug was fixed in version 2.0.0 depd, and compiling with Babel 7 exposes the error

**Comment by dougwilson** [comment]
Hi @Windrill sorry you are having this problem. I don't recall ever fixing such a bug in `depd`. Can you provide the specific steps to reproduce the error? Or link to which specific in `depd` or which changelog entry fixed the issue in question.

**Comment by Windrill** [comment]
Thanks for investigating this. It might be hard for you to find information or to easily replicate this from your side at first sight. 


This thread discussed behavior differences regarding that stacktrace from depd 1.1.2 vs 2.0.0: 
https://github.com/oracle/graaljs/issues/269


I was also able to similarly observe it using the following environment / command / config:
(Node v10.19.0 also works)
`
package.json (including the relevant lines)
{
  "main": "index.js",
  "scripts": {
    "run": "./node_modules/.bin/babel-node --config-file .babelrc index.js"
  },
  "dependencies": {
    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "node": "^17.4.0",
    "@babel/core": "^7.16.12",
    "@babel/preset-env": "^7.16.11"
  },
  "devDependencies": {
    "nodemon": "^2.0.7",
    "@babel/cli": "^7.16.8",
    "@babel/node": "^7.16.8"
  }
}


.babelrc (enables es6)
{
  "presets": [
    "@babel/preset-env"
  ]
}
`

Babel 7's transpiler invokes the relevant function to produce the stack trace above.
After changing depd's version to 2.0.0 (from version 1.1.2) in expressJS's package.json, the error is no longer observed from expressJS though the same stack trace can be found in bodyparser's node_modules (also depd 1.1.2).

**Comment by dougwilson** [comment]
Hi @Windrill thanks for that link. The solution says _and used the browser version of depd by overwriting the version node.js would normally use_. That version in the same in 1.1.2. It doesn't say that just upgrading to 2.0.0 fixed the issue, that the user still had to perform that additional action.

I created a project with those two files, but then what do I run on the command prompt to actually reproduce the error?

**Comment by dougwilson** [comment]
Anyway, the reason I'm asking is because I just want to make sure. I plan to upgrade it, no problem. But if it still doesn't work after I upgrade it, there is nothing further I can do.

**Comment by Windrill** [comment]
I think for them copying depd 2.0.0 repository in node_modules filesystem which should be the same as package management via package.json fixed it. Reproducing it is probably more important though

Try "let express = require('express');" in index.js, and run "./node_modules/.bin/babel-node --config-file .babelrc index.js".

Hmm see if you're able to reproduce this, actually you have a point that this might not be the cause of the error.

**Comment by dougwilson** [comment]
Hi @Windrill , running those two commands does not produce the error you have provided. Is that error something that you are seeing as the output to the `babel-node` command on your end?

**Comment by Windrill** [comment]
Hi @dougwilson, happy to share, I am using this environment on my system: https://drive.google.com/file/d/1FVki5KAXrFGEgUP27YPE6eGn5vlBxrZ1/view?usp=sharing

`windrill@windrill:~/JS/express_es6$ ls
index.js  node_modules  package.json  package-lock.json
windrill@windrill:~/JS/express_es6$ ./node_modules/.bin/babel-node --config-file .babelrc index.js
/home/windrill/JS/express_es6/node_modules/depd/index.js:252
  var file = callSite.getFileName() || '<anonymous>'
                      ^

TypeError: callSite.getFileName is not a function
    at callSiteLocation (/home/windrill/JS/express_es6/node_modules/depd/index.js:252:23)
    at depd (/home/windrill/JS/express_es6/node_modules/depd/index.js:111:14)
    at Object.<anonymous> (/home/windrill/JS/express_es6/node_modules/body-parser/index.js:14:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/home/windrill/JS/express_es6/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/windrill/JS/express_es6/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
windrill@windrill:~/JS/express_es6$ 

`

**Comment by dougwilson** [comment]
Thank you. I downloaded and unzipped that and then ran your command above. I got the following error:
```
Error: Cannot find module '../lib/babel-node'
```

I then tried `rm -rf node_modules && npm i` and can it again, but now got the following error:
```
Error: Cannot find module '.babelrc'
```

**Comment by dougwilson** [comment]
Ok, so I changed your command to the following:
```
./node_modules/.bin/babel-node --config-file ./.babelrc index.js
```

(notice I added `./` in front of `.babelrc`)

After that, it runs and gives zero output. I'm not sure if that is expected or not...

**Comment by dougwilson** [comment]
Ok, I modified `index.js` to include `console.log("OK")` and the output prints `OK`, so I guess then it is working fine. I tried on two different machines. I'm not sure how else to help, as without being able to reproduce the issue, I cannot help determine the cause. I would perhaps encourage one of the following courses of actions:

1. Try on a different machine, from your ZIP; see if it reproduces or not (I tried on Windows and Mac OS X). It may be something wrong with the environment on your one machine if you've only tried it on one place.
2. Open a PR that adds a test case to the module that demonstrates it failing in the CI. This gives a common ground place to see the failure and begin to debug that we both have access to.
3. Open a PR with a fix for the issue after you have debugged it and determined the case.

I'm sorry I don't have anything better than the above, but without being able to reproduce the issue, I am unable to help determine a fix :(

**Comment by dougwilson** [comment]
FWIW, `depd` 2.0 is coming in the new minor release of this module, so if you truly believe that will fix your issue, then you'll have a fix within the next 7-ish days anyway 👍

**Comment by Windrill** [comment]
Thanks for confirming this, and also for suggesting the possible follow-up mechanisms. Surprised that the error didn't carry across machines with same node_module libraries, I'll update through those methods in further action.

Looking forward to the new release, will be sure to check that out too :smile:

**Comment by dougwilson** [comment]
FYI the `master` branch now has `depd` 2.0.0, if you wanted to test it prior to release. Otherwise the release should come out as a minor sometime this week.
