### ISSUE TITLE
Error of type-is when installing with `npm ci`

### ISSUE THREAD

**Issue by naquiroz** [expressjs/body-parser#458]
I'm using **Nuxt Auth** which uses as dependency `body-parser`. The issue, is that when I install the dependencies of my app with `npm ci` for CI purposes.  The issue is that when installing with `npm ci` I get the following error:

```
npm ERR! type-is not accessible from body-parser
```

**Comment by dougwilson** [comment]
Hi @naquiroz sorry you are having trouble. This is nothing this module can change; it is `npm` indicating you have a corrupted tree saved in your `package-lock.json` file.

**Comment by naquiroz** [comment]
Thanks! Is there a way of fixing this without deleting the `package-lock.json`?

**Comment by dougwilson** [comment]
That I am not sure of. Probably a question for npm support.
