### ISSUE TITLE
Cannot parse top-level numbers or strings

### ISSUE THREAD

**Issue by ericvicenti** [expressjs/body-parser#461]
Hi, strings wrapped with `"` and number literals are valid JSON, according to the JSON spec.

When a string or number is passed in the request body, the body parser outputs an empty object!

Instead I expect it to parse the string or number correctly, and set it on `req.body` like usual.

I notice arrays work, in addition to objects. Why doesn't body-parser support other root JSON types?

**Comment by dougwilson** [comment]
https://github.com/expressjs/body-parser#strict
