### ISSUE TITLE
possible memory leak between v1.19.2 and v 1.20.0

### ISSUE THREAD

**Issue by southbite** [expressjs/body-parser#466]
hi guys, this very much could be a combination of how we use body-parser and the library itself, or some dependency issue I am unaware of, but we are leaking IncomingMessage objects when we use body-parser 1.20.0, I. am unable to decipher exactly why, it may be my inexperience with heapdump analysis, but it is not easy to see what the issue is.

I would have preferred to email about this first, instead of announcing this without deeper knowledge, but I believe what I am seeing could be a leak.

I can supply you with heapdumps, that I created with 1.19.2 and 1.20.0 if you require them, all you have to look for is IncomingMessage objects - with v1.19.2 I have the expected amount, as they are linked to websocket upgrades and should remain in memory, with v1.20.0 - all of the http requests my tests do are causing a retained IncomingMessage object, so the GC is unable to remove them. Retainers are a bit obscure, it looks like something contextual.

I ran the heapdump tests and could demonstrate the difference by only swapping out the body-parser node module (old for new ad vice versa), so no npm install.

I also went through all of the commits between 1.19.2 and 1.20.0 and I cannot see anything glaring there, unless you have a badly behaved introduced dependency. But I may be unfamiliar with your code, and you may see something that could be retaining req or res.

**Comment by southbite** [comment]
Thanks, Doug, yes I am doing a gc before I do the dump, I can try and set up a test that does not involve anything except maybe connect and parse-body, it may be how we are using parse-body or some kind of dependency interaction that is specific to our setup, hence you not seeing anything on your side. This may take some time though as I need to get a release out with 1.19.2

**Comment by dougwilson** [comment]
No problem. I'll go ahead and close this is the meantime, as there is not enough for us to act on and I don't want someone to be alarmed about an issue like this without being able to do anything, if it's there. I can reopen once there is enough information to be able to act on from our side 👍 . You're also always welcome to make a pull request instead of a reproduction if you are able to find the issue, of course!

**Comment by southbite** [comment]
of course, and totally agree regarding closing - I am sorry about having to post an issue, but I didn't have another channel

**Comment by dougwilson** [comment]
It's no problem. When you do have some more info we can use to help investigate, you're welcome to post it here or even a new issue, whatever you feel like 👍
