### ISSUE TITLE
Testing with Jest leaves open handles

### ISSUE THREAD

**Issue by Vinlock** [expressjs/body-parser#473]
See a similar issue here: https://github.com/visionmedia/supertest/issues/772

I have tested on:
- `1.19.2` - PASS ✅ 
- `1.20.0` - FAIL ❌ 
- `1.20.1` - FAIL ❌ 
- `2.0.0-beta.1` - PASS ✅ 

Only the ❌ cause open handles to remain after the tests exit.

**Comment by dougwilson** [comment]
Thank you for your report. Please send a PR with a fix or provide detailed instructions so I can reproduce the issue.

**Comment by dougwilson** [comment]
Closing due to no response.
