### ISSUE TITLE
JSON not parsed if Content-Type ends with "; utf-8"

### ISSUE THREAD

**Issue by lucdetellis** [expressjs/body-parser#474]
If a JSON request is sent with `Content-Type: application/json; utf-8`, `req.body` is just an empty object.

Removing `; utf-8` from the `Content-Type` fixes the problem, but I have a webhook that uses `; utf-8` and I can't change it.

Here are the options I'm using:
```
app.use(bodyParser.json({
  limit: '20mb'
}));
```

Even when valid JSON is sent, in my route `console.log(req.body)` always prints `{}`.

**Comment by dougwilson** [comment]
Hi @lucdetellis thanks for your report! That is very strange, as we have multiple tests that verify that should work (https://github.com/expressjs/body-parser/blob/dad8f345c7d8424cb71b18a6060198040ad5ec04/test/json.js#L605). But of course the tests are not always perfect and can miss things. Can you please provide us the following so we can reproduce the issue?

1. The version of Node.js you are using
2. The version of this module you are using
3. A complete app (it doesn't need to be your real app -- even just modify one of the examples from the readme) that we can run and reproduce the issue with
4. Step by step instructions for how to reproduce the issue; include all the details to recreate the exact same http request as sometimes that can make all the difference

Thank you!

**Comment by dougwilson** [comment]
Oh, nevermind. I just realized you said `application/json; utf-8`, not `application/json; charset=utf-8`. Yes, the parser expects a valid content-type by default. After the semi-colon is required to be key-pair values, not just plain text.

Youn can pass in the `type` option a custom function to check for your content-type and then be able to use anything you want, even mal-formed content-type headers, like so:
```js
app.use(bodyParser.json({
  limit: '20mb',
  type: (req) => return /* condition to check your content-type header */
}));
```

**Comment by lucdetellis** [comment]
@dougwilson Thank you for the solution! That's strange the webhook I'm using is sending an invalid content-type.
