### ISSUE TITLE
Update iconv-lite to latest 0.6.3

### ISSUE THREAD

**Issue by jperelli** [expressjs/body-parser#476]
In a project I work we use body-parser and mysql2 as dependencies.
We are running a very common combination of prisma+mysql2 / expressjs+bodyparser in vercel, and every bundle kb is important in cold start lambda functions.

mysql2 depends on iconv-lite: 0.6.3 and body-parser depends on iconv-lite: 0.4.24

I think it can be upgraded in body-parser to have the same library and avoid code duplication. This would save around 600kb (~500kb of duplication + ~100kb of improved bundle size in 0.6.0).

Thank you for this great project!

**Comment by dougwilson** [comment]
Hello, and sorry for the delay on responding; I didn't realize I never did. I took a look and it seems that there are some breaking changes in that upgrade path. I will, however, work to get it fully upgraded in our 2.0 branch 👍

**Comment by RahulGautamSingh** [comment]
Maybe using a automatic dependency bot like: [renovate ](https://github.com/renovatebot/renovate)or [dependabot ](https://github.com/dependabot/dependabot-core)can be useful? I would be happy to set them up if that's okay.☺

**Comment by dougwilson** [comment]
Hi @RahulGautamSingh I'm not sure how that would help here, as it is not upgraded in 1.x because it has breaking changes that requires a major version bump for body-parser.

**Comment by RahulGautamSingh** [comment]
Regular update PRs will help keep all deps up-to-date, and if some dep-updates require version bump then those can be targeted to the branch which is under work ie. `2.0` branch.

**Comment by dougwilson** [comment]
Thanks, but I don't think having that is necessary.

**Comment by dougwilson** [comment]
Sorry, I meant I forgot to reply to this issue; not that I forgot to update the dep. I already know it was out of date but incompatible.

**Comment by Luzgan** [comment]
2.0 is still ongoing right? I am asking because now I happened to need newer version of iconv, since there is a need to support ISO-8859-1, which is not included in older version :)

**Comment by wesleytodd** [comment]
Please open a PR against the 2.x branch (#66) if it is not already updated in there.
