### ISSUE TITLE
Released `2.0.0-beta.1` version depends on qs 6.9.6 

### ISSUE THREAD

**Issue by Lordfirespeed** [expressjs/body-parser#490]
The problem has already been resolved (the `2.x` branch now shows dependency as `6.9.7` but changes haven't been released to NPM. 
Would an NPM release of `2.0.0-beta.2` be possible to fix this issue?

**Comment by dougwilson** [comment]
Hi @Lordfirespeed I can make a release of the beta to npm, yes. What issue are you referring to?
