### ISSUE TITLE
Relaxed versions

### ISSUE THREAD

**Issue by daveisfera** [expressjs/body-parser#496]
Currently, specific versions are used. Could `^` or `~` be used so users have more flexibility in which version is installed?

**Comment by dougwilson** [comment]
Hi @daveisfera ! Yes, they are typically pinned, which is the policy for all of our projects across our organizations. One reason this is a huge help is in support: folks report a specific version of one of our modules and we can understand the dependency tree without much back and forth. This also was enacted to combat dependency hijacks attack, of which the Express.js project was targeted multiple times, saved by pinned dependencies.

Those are just two of the various reasons, and we think they are appropriate tradeoffs for our position in the community.
