### ISSUE TITLE
body parser is breaking base64 string

### ISSUE THREAD

**Issue by lucksp** [expressjs/body-parser#500]
I am sending a base64 string from my mobile app to my Express server via `POST` request. The image is sent to a Google client endpoint, but it's is returning an error: `Provided image is not valid`

> code: 400,0|index | errors: [0|index | {0|index | message: 'Provided image is not valid.',0|index | domain: 'global',0|index | reason: 'badRequest'0|index | }0|index | ]

"dependencies": {
    "@types/body-parser": "^1.19.2",
    "@types/express": "4",
    "@types/node": "18",
    "body-parser": "^1.20.2",
    "express": "^4.18.2",
  },

- Here is sample log showing base64 on the client:
![image](https://github.com/expressjs/body-parser/assets/15162169/a2263c1d-c4e1-4e5e-acba-0b09ea396099)

You can see the highlighted string includes text of: `CZjs+EJ+/+I`.

- Now, here is the log of the same asset on the server as seen logging `req.body`:
![image](https://github.com/expressjs/body-parser/assets/15162169/7c5fcd98-29a4-4aee-8d54-c904b1b965cd)

You can see the highlighted string includes text of `CZjs EJ / IC` instead. the `+`'s have been stripped and turned in to spaces.

I think it has to do with the body-parser breaking my stringified base64 body from client side to server endpoint.

On the client:

```js
const body = typeof data === 'string' ? data : JSON.stringify(data); // data is base64 string;

const response = await fetch(path, { // this goes to the Express Server
      method,
      body,
      headers: {
        ...headers,
      },
    });
```
- Here is a gist of a sample base64 from the client: https://gist.github.com/lucksp/0a831684c34271424309096172ccb79a#file-clientbase64-js

Here is my Express server code.

```js
const app = express();
app.use(bodyParser.json({ limit: '20mb' }));
app.use(
  bodyParser.urlencoded({
    limit: '20mb',
    extended: true,
    parameterLimit: 50000,
  })
);
app.use(bodyParser.text({ limit: '200mb' }));
async function callPrediction({
  endpoint,
  data,
}: {
  endpoint?: string | null;
  data: string;
}) {
const auth = new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  });
  const client = await auth.getClient();
const body = JSON.stringify({
    instances: [
      {
        content: data,
      },
    ],
    parameters: {
      confidenceThreshold: 0.5,
      maxPredictions: 5,
    },
  });

  const res = await client.request({
    method: 'POST',
    url,
    body,
    headers: { 'Content-Type': 'application/json' },
  });

  return res;
};

// Server endpoint receives original request
app.post('/verify', async (req, res) => {
  // calls the google service now
  // console.log(req.body) // data is corrupted here.
  const results = await callPrediction({
    endpoint: endpoints[0].name,
    data: req.body, // comes in as a stringified JSON. Also fails if parsing here.
  });

  return results;
}
```

What's really odd is that the same base64 sent from **Postman** works fine.

Am I doing something wrong with bodyParser or is it the base64 itself?

**Comment by dougwilson** [comment]
Hi @lucksp and sorry you are having trouble. Off hand I'm not sure what inside thia module would change your plus signs to spaces, and especially that it would not do it for Postman, but would for your other client. That sounds like either thee other client itself is doing thay somewhere or there is some other difference between your Postman request and the actual client request.

Without having all the steps to replicate the issue, and not really knowing what inside this module would make such a change, I'm not sure where to go from here.

Perhaps you could put together a complete app and test case with steps by step instructions so we can reproduce? Then we can debug through it. Otherwise you are always welcome to debug it on your code base and we very much would welcome a pr if you figure it out.

**Comment by lucksp** [comment]
Thanks @dougwilson 
Is there a different base64 body encoder/decoder I should use than what I listed above in my snippet?

**Comment by dougwilson** [comment]
Hi, I'm sorry, I don't see any base64 encoder or decoder in your snippets. Maybe I am just miasing them. Can you point them out?
