### ISSUE TITLE
Body is object instead of string with `express.text`

### ISSUE THREAD

**Issue by someden** [expressjs/body-parser#507]
There is a case with `express.text` middleware when body can be an object instead of string:
[Demo on codesandbox](https://codesandbox.io/p/sandbox/intelligent-goldwasser-svqdv7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp2sobhw00073b5wqnen9gpi%2522%252C%2522sizes%2522%253A%255B51.79396092362344%252C48.20603907637656%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp2sobhw00033b5wwjudr9aj%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp2ssmri010i3b5wqiajs8lo%2522%257D%255D%252C%2522sizes%2522%253A%255B54.26664800942615%252C45.73335199057385%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp2sun0v01py3b5wwpij5uqm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp2sobhw00063b5wavlo2o8v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B67.84313725490196%252C32.15686274509804%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp2sobhw00033b5wwjudr9aj%2522%253A%257B%2522id%2522%253A%2522clp2sobhw00033b5wwjudr9aj%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522id%2522%253A%2522clp2ssldu00yh3b5wvnos5ds6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp2ssldu00yh3b5wvnos5ds6%2522%257D%252C%2522clp2sobhw00063b5wavlo2o8v%2522%253A%257B%2522id%2522%253A%2522clp2sobhw00063b5wavlo2o8v%2522%252C%2522activeTabId%2522%253A%2522clp5rgvb701gb3b5wgfb2jc3z%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3010%252C%2522id%2522%253A%2522clp5rgvb701gb3b5wgfb2jc3z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clp2ssmri010i3b5wqiajs8lo%2522%253A%257B%2522id%2522%253A%2522clp2ssmri010i3b5wqiajs8lo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522id%2522%253A%2522clp5shz8y00x43b5wqxtih197%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp5shz8y00x43b5wqxtih197%2522%257D%252C%2522clp2sun0v01py3b5wwpij5uqm%2522%253A%257B%2522id%2522%253A%2522clp2sun0v01py3b5wwpij5uqm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clp2t3s5401d73b5wmrwjf4rl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp2t3s5401d73b5wmrwjf4rl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

It's when body is `null` on fetch

Looks like here is when we get object: https://github.com/expressjs/body-parser/blob/ee91374eae1555af679550b1d2fb5697d9924109/lib/types/text.js#L64

<img width="1529" alt="Screenshot 2023-11-19 at 21 28 59" src="https://github.com/expressjs/body-parser/assets/7009699/614afc18-7206-4b0c-bcc3-4d5524a916cf">

**Comment by dougwilson** [comment]
Yes, this is intended with 1.x series. It is no longer the case on the 2.x series, however.
