### ISSUE TITLE
Update  debug to Newest version (4.3.4)

### ISSUE THREAD

**Issue by marianamohr** [expressjs/body-parser#508]
## Overview

Debug on version  below 4.3.4 has a problem related to has a Memory Leak when creating `debug` instances inside a function which can have a significant impact in the Availability.

So is necessary to update this package. 

Something else related, [issue opened](https://github.com/debug-js/debug/issues/678) and [PR solving the issue](https://github.com/debug-js/debug/pull/699)

**Comment by dougwilson** [comment]
Please if you can, follow our security policy https://github.com/expressjs/body-parser/blob/master/SECURITY.md to report security issues in the future.
