### ISSUE TITLE
how to do JSON.parse? in body-parser ?

### ISSUE THREAD

**Issue by Bimbimz** [expressjs/body-parser#533]
on the client side I use jquery:

```
let data = {
    email: 'myemail@domain.com',
    password: 'test1234'
}
$.post('http://localhost:3000/auth', {
    data: JSON.stringify(data)
}, function (res) {
    console.log(res)
})
```

**Comment by wesleytodd** [comment]
Sorry your question is not clear. Body parser will decode this json data, so unless you can provide some more information about the issue you are having we cannot really help you. Please re-open this if you have more info to provide.
