### ISSUE TITLE
Allow setting of qs depth option

### ISSUE THREAD

**Issue by aez** [expressjs/body-parser#55]
The qs module has a nesting limit, which defaults to 5. This can be overriden with an option; however within the body-parser module there is no way to set that. Body-parser should expose that option via config somehow.

See https://github.com/hapijs/qs#parsing-objects for more info on the qs option.

**Comment by dougwilson** [comment]
Version 1.11.0 doesn't allow you to set the depth, but there is no longer a limit, so it's not necessary to control the value.
