### ISSUE TITLE
"express route-specific" example is not working

### ISSUE THREAD

**Issue by lukescott** [expressjs/body-parser#67]
The "express route-specific" example is not working, specifically `req.body` always contains a value so this condition is always false:

``` javascript
 if (!req.body) return res.sendStatus(400)
```

And this is because of this:

``` javascript
  return function jsonParser(req, res, next) {
    if (req._body) return next()
    req.body = req.body || {} // <- A value is set to a blank object even if typeis fails

    if (!typeis(req, type)) return next()
```

Which is here:
https://github.com/expressjs/body-parser/blob/df1d88aaa33c36ccced4a0d0788a0ab92e56875a/lib/types/json.js#L81

So two questions that I have is:
- If the user does not set a Content-Type header at all, how do I default to application/json so I always get a populated object instead of an empty one? Or at the very least how do I tell them they are missing that Content-Type header?
- If the Content-Type is set, how do I determine that it is not correct and send them an appropriate error?

**Comment by chandara** [comment]
Sorry, I am new to node and express, and I have tried the "express route-specific" with express router, but it doesn't work. Is it correct behavior? if so, is there any solution that I can use the body-parser for specific route in router?

**Comment by dougwilson** [comment]
Hi @chandara , I'd be happy to help. Please open a new issue at https://github.com/expressjs/body-parser/issues/new and explain your question, including the definition of "it doesn't work" and we'll proceed from there :)
