### ISSUE TITLE
qs' depth

### ISSUE THREAD

**Issue by chielkunkels** [expressjs/body-parser#71]
Hi there,

I'm using express + body-parser in my app and I ran into some very odd issue with deeper keys in a nested object coming out with brackets surrounding the keys, took me a while to figure out what was causing it.

Apparently `qs` accepts a `depth` option in order to go deeper... is there any support planned for this, or should I write my own qs parser in that case?

Cheers

**Comment by joshdickson40** [comment]
+1 I ran into this issue this morning and took forever to trace it back to this. 5 is completely arbitrary and I never found it in docs. Frustrating.

What is the suggested work around for this? I see PR pending with this but don't see a comment on when this might be out.

**Comment by dougwilson** [comment]
I'm' planning on removing the depth limit completely with 1.11.0. It's not documented anywhere because we don't set the limit anywhere in this module.

**Comment by chielkunkels** [comment]
Yup, 5 is simply the default set by the `qs` module itself. Removing it probably gets rid of people seeing this behaviour as a bug though.

**Comment by joshdickson40** [comment]
What's the timeframe for 1.11? I see tracker for 2.0 but not 1.11

**Comment by dougwilson** [comment]
Probably tonight (US time)

**Comment by joshdickson40** [comment]
That would be outstanding, thank you.

**Comment by dougwilson** [comment]
So I just wanted to update you that the "probably tonight" may end up slipping to a definitely Friday night, I'm sorry :(

**Comment by chielkunkels** [comment]
Cheers for the feedback and thanks for your hard work. :)

**Comment by joshdickson40** [comment]
It had to be last night! You've broken our code base!

Tonight is just fine, thanks again :)

**Comment by dougwilson** [comment]
Main conversation/question over here: https://github.com/expressjs/body-parser/issues/76#issuecomment-72304885

**Comment by dougwilson** [comment]
Sorry, wrong thread :)

**Comment by joshdickson40** [comment]
Cheers thanks

**Comment by dougwilson** [comment]
Version 1.11.0 doesn't allow you to set the depth, but there is no longer a limit, so it's not necessary to control the value.

**Comment by joshdickson40** [comment]
Already have it in QA and works great for me, thanks again.

**Comment by dougwilson** [comment]
Great, no problem :) I resisted lifting that for a while because the `qs` authors say to "keep it at a reasonable small number", but I did a bunch of performance testing with this change and I don't see any reason why it cannot be Infinity.

**Comment by AndersonZacharyT** [comment]
@dougwilson Hey Doug--thanks for all of your work! I am facing this issue, using Express/LoopBack, and even though my Express is > 1.11 I seem to have hit this wall... anything coming to mind?

**Comment by dougwilson** [comment]
Hi @AndersonZacharyT , I don't think that file has anything to do with the `body-parser` module. If you are talking about the query string in Express, then you can do the following:
```js
app.set('query parser', function (str) {
  return qs.parse(str, {
    allowPrototypes: true,
    limit: 10
  });
})
```
