### ISSUE TITLE
Passing a boolean value 

### ISSUE THREAD

**Issue by efkan** [expressjs/body-parser#74]
Hello, 

I've been trying to pass a bool value to Node.js but I couldn't.
My json object like { archive: false } before an ajax process. I can get as { "archive": "false" }. I want to use as a bool value in my database.

Is it possible? Can I get as a bool value?

**Comment by efkan** [comment]
Heelo @JoeWagner. Thank you for your response.
Yes I've tried and it didn't work normally.
I should to learn a lot of things :) 
I've learned today that;
Nobody passes a bool or numeric value to Node.js using REST API. Because it works with strings.
Therefore, there are lots of ODM (Object Document Mapper) tools.

Hopefully you will say "you're wrong. You can".. Otherwise, I have to re-write my controllers using Mangoose :)

I'm closing the issue. Thanks again..

**Comment by dougwilson** [comment]
You can 100% pass in bools using JSON with this library. Here is an example:
```js
var bodyParser = require('body-parser')
var express = require('express')
var util = require('util')

var app = express()

app.post('/', bodyParser.json(), function (req, res) {
  res.type('text')
  res.write('request posted the following:\n')
  res.write(util.inspect(req.body) + '\n')

  res.write('and the archive property is a ' + typeof req.body.archive + '\n')
  res.end()
})

app.listen(3000)
```

Then make a JSON post:
```
curl -XPOST -H'Content-Type: application/json' -d'{"archive":false,"foo":"bar"}' http://localhost:3000/
request posted the following:
{ archive: false, foo: 'bar' }
and the archive property is a boolean
```

Most likely you are not actually sending JSON like you think you are (you can verify using HTTP sniffing like Fiddler or something similar) _or_ you are sending JSON, but something on your client is changing the boolean to a string and it's being sent over the wire as `{"archive":"false"}` (you can also verify this using something like Fiddler).

**Comment by qwemaze** [comment]
@dougwilson yeah, but it'll only work with PUT/POST requests, because `bodyParser.json` doesn't parse `req.query`, and `bodyParser.urlencoded` doesn't seem to parse numbers/booleans.

**Comment by dougwilson** [comment]
Hi @qwemaze, I'm not sure what the comment you made means. This is `body-parser`, which only parses request bodies, thus it of course wouldn't parse `req.query`, that would be non-sense. The urlencoded format is parsed by the `qs` module, so you can always bring up the issue there and whatever changes they make we'll pull in here.
