### ISSUE TITLE
Add smarter handling for jQuery arrays

### ISSUE THREAD

**Issue by the-t-in-rtf** [expressjs/body-parser#80]
jQuery does two things somewhat oddly regarding arrays, it would be really helpful if the body parser took these into account.

First, in modern versions of jQuery (>= 1.5), arrays that are included in AJAX data are passed with square brackets appended to their name.  This can be overridden by adding the `traditional: true` parameter on the client side.  Even with that parameter, a single array parameter is interpreted as a string.

Ideally, body parser should have tests specifically to cover jQuery's use of arrays, and should treat any parameter whose name has trailing square brackets as an array regardless of the number of elements.

**Comment by dougwilson** [comment]
Does `bodyParser.urlencoded({ extended: true })` not work?

**Comment by dougwilson** [comment]
Let me know what you find out :)

**Comment by dougwilson** [comment]
@the-t-in-rtf I'm closing this because I haven't heard anything back about how jQuery works or anything actionable. Please feel free to provide the information and I can re-open the ticket :)

**Comment by the-t-in-rtf** [comment]
@dougwilson, I was not at work yesterday and didn't see your responses.  For now, I have a workaround, and we can leave it closed.  If it keeps coming up or other people encounter it, I can write a test that should illustrate the problem.

**Comment by dougwilson** [comment]
Ok. Feel free to write a test eve if we never hear from anyone else, though :) I'd be happy to check it out.
