### ISSUE TITLE
Ensure bodyParser.urlencoded doesn't transform request body to json

### ISSUE THREAD

**Issue by charyorde** [expressjs/body-parser#81]
From #39 
How can I ensure the raw request body is what is sent? Here's what I'm toying with:
```
var bodyParser = require('body-parser');

router.use(function(req, res, next) {
    var data = '';
    req.on('data', function(chunk) {
            data += chunk;
        }); 
    req.on('end', function() {
            req.rawBody = data;
            next();
        }); 
});
// retrieve all request body objects
router.use(cookieParser());
router.use(bodyParser());
router.use(methodOverride());

router.post('/login', function(req, res) {
  console.log(req.rawBody);
  if (!req.body) return res.sendStatus(400);

  var options = httpconn.httpOptions({
    resource: 'uaa',
    resourcePath: '/uaa/login.do',
    method: 'POST',
    headers: {'Referer': httpconn.buildUri('uaa') + '/uaa/login'}
  });
  var httpRequest = application.httprequest(options, function(response) {
      if(response.statusCode == 302) {
        res.send(response.headers);
      } 
  });
  httpRequest.write(qs.stringify(req.rawBody));
  httpRequest.end();
```
To use the `req.rawBody` middleware, I needed to use `-H 'Content-Type: text/plain'`.

I want to ensure that a request with `application/x-www-form-urlencoded` maintains the request body as `username=myname&password=mypass` without transforming to `{'username':'myname','password':'mypass'}`

**Comment by dougwilson** [comment]
How about just `app.use(bodyParser.text({ type: 'urlencoded' }))`? It should provide you the URL-encoded body as a string in `req.body`, then.

**Comment by charyorde** [comment]
Thanks @dougwilson 
Tired that but still getting json response `{'username':'myname','password':'mypass'}`

**Comment by dougwilson** [comment]
Ok. It would be easier if I had fully complete code to run. This is the code I have that works for me:
```js
var bodyParser = require('body-parser');
var express = require('express');

var app = express();
app.post('/login', bodyParser.text({ type: 'urlencoded' }), function(req, res) {
  console.log(req.body);
  if (!req.body) return res.sendStatus(400);

  var options = httpconn.httpOptions({
    resource: 'uaa',
    resourcePath: '/uaa/login.do',
    method: 'POST',
    headers: {'Referer': httpconn.buildUri('uaa') + '/uaa/login'}
  });
  var httpRequest = application.httprequest(options, function(response) {
      if(response.statusCode == 302) {
        res.send(response.headers);
      } 
  });
  httpRequest.write(req.body);
  httpRequest.end();
```

**Comment by dougwilson** [comment]
Basically, the body can only be parsed _one time_ so your `bodyParser.text({ type: 'urlencoded' })` needs to be _exclusive_ so it doesn't conflict with your `bodyParser()`. Ideally the best practice on the readme is you only ever use `bodyParser` middleware on the routes themselves (like above) rather than globally. This helps prevents conflicts.

**Comment by charyorde** [comment]
Awesome. Works now. Thanks

**Comment by kagan94** [comment]
In my case, the content-type of incoming requests was 'text/plain', so on the backend side I needed to parse it from that format:  
```
app.use(parser.text({type: 'text/plain'}))
```
