### ISSUE TITLE
Parsing complex json structure

### ISSUE THREAD

**Issue by charyorde** [expressjs/body-parser#82]
How to parse this:

```
{
    "schemas":["urn:scim:schemas:core:1.0"],
    "userName":"bjensen",
    "name":{
        "formatted":"Ms. Barbara J Jensen III",
        "familyName":"Jensen",
        "givenName":"Barbara"
    },
    "emails":[{
        "type":"home",
        "value":"email@test.org"
    }],
}
```
Here's what I'm working with:
```js
var jsonParser = bodyParser.json({ type: 'application/*+json' } );
router.post('/create-account', jsonParser, function(req, res) { 
  console.log(req.body)
});
```

**Comment by dougwilson** [comment]
That works just fine for me. Can you provide some more details, like what isn't working, or what the error is, or what the parse looks like to you?

**Comment by charyorde** [comment]
`console.log(req.body)` simply returns `{}`.
The full route looks like this:
```
var router = express.Router();
var validator = require('express-validator');
router.use(validator());

var jsonParser = bodyParser.json({ type: 'application/*+json' } );

router.post('/create-account', jsonParser, function(req, res) {
  console.log(req.body); // This returns {}
  if (!req.body) return res.sendStatus(400);

  req.checkBody('userName', 'required').notEmpty();
  req.checkBody('name', 'required').notEmpty();

  var errors = req.validationErrors();
  if (errors) {
    res.status(400).send('There have been validation errors: ' + util.inspect(errors));
    return;
  }
```
I know body-parser has nothing to do with validation(used express-validator), but since you asked for details, on validation, the json fields couldn't be validated because `req.body` returns empty.
```
There have been validation errors: [ { param: 'userName', msg: 'required', value: undefined }, { param: 'name', msg: 'required', value: undefined }]
```

**Comment by dougwilson** [comment]
Gotcha. It would seem the reason `req.body = {}` for your case is because of one of two reasons (both of which I cannot confirm because will app code wasn't pasted):

1. The request's content-type is not `application/stuff+json`; if it is just `application/json` then your `jsonParser` will ignore it
2. The `jsonParser` you have there will only ever work _as long as something prior to your code is not reading the bdoy_, as in perhaps somewhere outside what you posted there is a `app.use(bodyParser)` or similar?

The following code works perfectly fine for me:
```js
var app = express();
var router = express.Router();

var jsonParser = bodyParser.json({ type: 'application/*+json' } );

router.post('/create-account', jsonParser, function(req, res) {
  console.log(req.body);
});

app.use(router);
app.listen(3000);
```

**Comment by charyorde** [comment]
Thanks

I don't have 'app.use(bodyParser())' anywhere in my code. Moreso, I'm reading the json data from a file like so:

`curl -v -H "Content-Type: application/json" -d @/tmp/create-account.json http://localhost:3000/auth/create-account`

Could it be that there's something wrong with how the request is constructed? What's your request content-type?

**Comment by dougwilson** [comment]
Ah. Your cURL command has the wrong content type, as `application/json` _does not match_ `application/*+json`. You need to change one or the other. If you want to use `application/json`, then set that in your code, otherwise send a content-type in cURL that matches `application/*+json`.

**Comment by charyorde** [comment]
Okay. I simply changed the request to `curl -v -d @/tmp/create-account.json http://localhost:3000/auth/create-account` and code as:

```
var urlencodedParser = bodyParser.urlencoded({extended: false } );

router.post('/create-account', urlencodedParser, function(req, res) {
  console.log(req.body);
});
```

**Comment by charyorde** [comment]
Well, just for enhancement purposes for the library, a request like so:
`curl -v -H "Content-Type: application/json" -d @/tmp/create-account.json http://localhost:3000/auth/create-account` and code like so:
```
var jsonParser = bodyParser.json({ type: 'application/json' } );
router.post('/create-account', jsonParser, function(req, res) { 
  console.log(req.body)
});
```

gives this error:
```
SyntaxError: Unexpected token }
    at Object.parse (native)
    at parse (/Users/osx/projects/nodescripts/useraccountservice/node_modules/body-parser/lib/types/json.js:84:17)
    at /Users/osx/projects/nodescripts/useraccountservice/node_modules/body-parser/lib/read.js:102:18
    at IncomingMessage.onEnd (/Users/kayodeodeyemi/projects/nodescripts/useraccountservice/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by dougwilson** [comment]
It's because you're sending invalid JSON.

**Comment by dougwilson** [comment]
Feel fee to post the contents of `/tmp/create-account.json` and I can point out where the JSON is invalid (you can always check yourself by running the file through `JSON.parse`, part of core JavaScript.

**Comment by charyorde** [comment]
```
{
    "schemas":["urn:scim:schemas:core:1.0"],
    "userName":"bjensen",
    "name":{
        "formatted":"Ms. Barbara J Jensen III",
        "familyName":"Jensen",
        "givenName":"Barbara"
    },
    "emails":[{
        "type":"home",
        "value":"email@test.org"
    }],
}
```

**Comment by dougwilson** [comment]
That very last trailing command is illegal is JSON.

**Comment by dougwilson** [comment]
That very last trailing comma is illegal is JSON.

**Comment by charyorde** [comment]
Awesome. Merci!
