### ISSUE TITLE
Better error logging

### ISSUE THREAD

**Issue by analytically** [expressjs/body-parser#85]
```
SyntaxError: Unexpected token $
  at Object.parse (native)
  at parse (/etc/acme/webauth/node_modules/body-parser/lib/types/json.js:84:17)
  at /etc/acme/webauth/node_modules/body-parser/lib/read.js:102:18
  at IncomingMessage.onEnd (/etc/acme/webauth/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:180:16)
  at IncomingMessage.emit (events.js:92:17)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:486:13)
```

This doesn't help much in debugging the request. Is there a way to catch this and log a simple warning message?

**Comment by dougwilson** [comment]
This is just the message from JSON.parse, part of the JavaScript language. If you have any suggestions, I'm all ears :)

**Comment by dougwilson** [comment]
I tagged this issue as help wanted because someone will need to do a PR to improve this.

**Comment by analytically** [comment]
I was thinking try/catch with console.log with more information (HTTP method + path + body limited to 100 chars?).

**Comment by dougwilson** [comment]
Oh, this is already 100% for you to do. I'm turning on my computer and I'll post you an example.

**Comment by analytically** [comment]
Sure I'll do a PR. Is console.log acceptable in body-parser? Other logging solutions?

**Comment by dougwilson** [comment]
No, this is something you simply implement yourself in your own code as part of Express error handling, nothing you need to change in this module. I mis-understood your original request.

**Comment by dougwilson** [comment]
Simply add this to your application:
```js
app.use(function logJsonParseError(err, req, res, next) {
  if (err.status === 400 && err.name === 'SyntaxError' && err.body) {
    // Display extra information for JSON parses
    console.log('JSON body parser error!')
    console.log(req.method + ' ' + req.url)
    console.log(req.body.slice(0, 100).toString())
  }

  next(err)
})
```

**Comment by dougwilson** [comment]
Sorry, modified the code above, because I accidentally put `req.body` instead of `err.body`.

**Comment by analytically** [comment]
Great, thanks!

**Comment by dougwilson** [comment]
This is what the output looks like :) Feel free to tweak as needed. Basically the main thing to note here is that in this module, when we have a parse error, we put the full decoded body in the `body` property on the `err` object so you can inspect it later :)
```
JSON body parser error!
PUT /
{"bob":$foo}
SyntaxError: Unexpected token $
    at Object.parse (native)
    at parse (node_modules\body-parser\lib\types\json.js:84:17)
    at node_modules\body-parser\lib\read.js:102:18
    at IncomingMessage.onEnd (node_modules\body-parser\node_modules\raw-body\index.js:136:7)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by dougwilson** [comment]
And, if you cannot get it to work, please feel free to post back here and I'm happy to help :) And I'm of course sorry again for misunderstanding the question initially :)

**Comment by analytically** [comment]
Thanks a lot!

**Comment by JuanDelgadillo** [comment]
Thaks a lot! too :)
