### ISSUE TITLE
Parse response body and detect charset from HTML meta

### ISSUE THREAD

**Issue by JexCheng** [expressjs/body-parser#90]
I think it can be adapted to parse response body get from `http.request` response event. It is IncomingMessage instance too. In this case, the charset maybe hide in HTML meta tag like this:
```html
<meta charset="GBK"/>
```
Or CSS:
```
@charset "GBK";
```

The code:
```coffeescript

getCharsetFromBody = (req) ->
  body = req.body.toString("utf-8")
  ct = req.headers["content-type"]
  if /\btext\/html\b/i.test ct
    body = body.replace /<!--[^]*?-->/g,"" # remove html comments
    m = /<[^>]+\btext\/html;\s+charset=([\w-]+)[^>]*>/i.exec body
    m = /<meta\s+charset=["']?([\w-]+)[^>]*>/i.exec body if !m
  else if /\btext\/css\b/i.test ct
    body = body.replace /\/\*[^]*?\*\//g,"" # remove css comments
    m = /^@charset\s+["']([\w-]+)["']/im.exec body

  return m[1] if m
```

**Comment by JexCheng** [comment]
Additionally, the type of body is confusing. In my mind, the type of `req.body` returned by   `bodyParser.text`  should be always `string` on success . But sometimes I've got an empty object `{}`. So what does that  mean? Does `{}` mean parse failed? Does `{}` mean the incomingMessage doesn't have a body?

At last I found it: https://github.com/expressjs/body-parser/blob/master/lib/types/text.js#L60
```
    req.body = req.body || {} # if the req.body exists,use old value,why?

    // skip requests without bodies
    if (!typeis.hasBody(req)) {
      return debug('skip empty body'), next()
    }

    debug('content-type %j', req.headers['content-type'])

    // determine if request should be parsed
    if (!shouldParse(req)) {
      return debug('skip parsing'), next()
    }
```

So if the IncomingMessage doesn't have body or its mime type doesn't fit specified `options.type`, I will get `req.body` as `{}`.  I think it should change to `null` when `bodyParser` doesn't do parse at all.

**Comment by dougwilson** [comment]
@JexCheng for your comments on the empty object behavior (`{}`), there is an issue at #89 and it's already been changed on the 2.x branch for when the 2.0 release comes out.

**Comment by dougwilson** [comment]
To me, I have generally felt that actually understanding HTML and CSS is beyond the scope of this library (you can always just get a `Buffer` and do whatever charset detection and decoding you need using this library already). I certainly would never add regular expressions to do the task. For example, if a user can control text in the response, then they can trick your regular expression into decoding the response as UTF-7 and cause a lot of security issues.
