### ISSUE TITLE
Document what happens when the limit is exceeded

### ISSUE THREAD

**Issue by tmcw** [expressjs/body-parser#91]
There's a `limit` option for bodyParser - it would be useful to explicit about what it does: does it defer with an error? What sort of error?

**Comment by dougwilson** [comment]
Sounds fine, we can add more docs :) And in case you didn't know so this was also a question, the answer is it does whatever `raw-body` is doing.

**Comment by dougwilson** [comment]
@tmcw hopefully the new errors section is to your liking :)

**Comment by tmcw** [comment]
Awesome, thanks! Docs make the world a better place

**Comment by dougwilson** [comment]
Indeed :)
