### ISSUE TITLE
Option for bodyParser.json() for custom invalid errors

### ISSUE THREAD

**Issue by MattyKuzyk** [expressjs/body-parser#95]
Spitting out the entire trace to the user when JSON is invalid is kind of gross. Obviously I can manually make middlware before I use bodyParser that checks if the content type is JSON, and then checks if it's valid JSON, THEN throws my custom error, but why bother? I think it would be very useful to have an `invalid` option in bodyParser.json() that takes an object with a message and an error code.

**Comment by dougwilson** [comment]
Thu is functionality of Express, not this module. Simply add a custom Express error middleware or change your Express not to be in development mode.

**Comment by MattyKuzyk** [comment]
But I can't even get access to the body cleanly without including body-parser (which automatically returns its own error) or including an external module purely for this one function. Using express middleware here is super gross. I don't really see how that's not considered to be functionality of this module, but whatever. It's really useful to have for API design.

Thanks for the speedy reply, anyway.

**Comment by dougwilson** [comment]
There is nothing in this module that ever writes a response to the client, so there isn't a way we can not write the stack trace. If you can show what you are trying to accomplish, I can provide some code, unless you are asking that every single Express middleware ever needs to add this feature.

**Comment by MattyKuzyk** [comment]
Ahh, I see. I suppose I was merely misinformed.

Thanks!

**Comment by dougwilson** [comment]
Basically, what you described is already possible, though I need more details in order to provide you a code example, if that's what you're looking for.

**Comment by MattyKuzyk** [comment]
I'm sure I can figure it out, I just need error middleware after body parser to check if there was a parsing error. Cheers.

**Comment by dougwilson** [comment]
Ok. Sorry for he brevity earlier, I was on a phone, which is impossible to type code and I want to help people not be blocked as soon as possible. So now that I'm on a computer, I can post some code. So all the various types of errors we (finally) got listed in the readme: https://github.com/expressjs/body-parser#errors

The most basic way to handle is using an Express error middleware:
```js
// placed somewhere after body-parser
app.use(function (err, req, res, next) {
  if (err.status === 415 || err.status === 400) {
    return res.end('something is bad with the request')
  }

  // otherwise use the net error handler/default express one
  return next(err)
})
```
